### ISSUE TITLE
Problem with HxInputFile

### ISSUE THREAD

**Issue by zabanet** [havit/Havit.Blazor#1]
Hi. Thanks for the great work! The HxInputFile works great when I'm uploading files from the same machine where the site is hosted, but refuses to work when I initiate upload from another PC. I get preflight timeouts in chrome developer console. I suppose that it has something to do with CORS as my UploadUrl is on another port (and will be on another IP in the future), but I set  my API to enable requests from any origin. Did you test you component in such a scenario?

**Comment by jirikanda** [comment]
Hi zabanet,

the component works well in out production environment.

I guess there is something wrong with your CORS settings. So at first please check your settings and try it again. If it does not fix the problem, please provide us some steps to reproduce it.

It could be:
1. simple github repository (not a complex project, please)
2. use Fiddler (https://www.telerik.com/fiddler/fiddler-classic) to catch the communication between client and server (and save it as *.saz), do not compromise sensitive data
3. anything else...

**Comment by hakenr** [comment]
Closing due to lack of response. Feel free to add comments.
