### ISSUE TITLE
[HxInput] Apply InputSize to inputs with input-group (Was: Allow Input controls to add styles to the InputGroup)

### ISSUE THREAD

**Issue by robertmclaws** [havit/Havit.Blazor#103]
Please add an `InputGroupCssClass` property to `HxInputBaseWithInputGroups` and leverage it where appropriate to let me implement [this feature of Bootstrap](https://getbootstrap.com/docs/5.1/forms/input-group/#sizing).

**Comment by crdo** [comment]
This could be achievable with `InputGroupCssClass` or (my preferred solution) `InputGroupSize="InputGroupSize.Large"` that would be applied only if `InputGroupStartTemplate` or `InputGroupEndTemplate ` is present. @hakenr what do you think?

**Comment by robertmclaws** [comment]
So, using a string property instead an enum would also let you implement the "nowrap" feature just above the link I provided. I think that people are going to need to add classes to the input group, and just letting you manipulate the string covers more scenarios than having to implement specific enums for each feature on that Bootstrap documentation page.

**Comment by crdo** [comment]
I think that we will end up with both. But as far as we set the Input and Buttons sizes with Enums, we should stick with it in this scenario as well. For the "nowrap" case the `InputGroupCssClass` si clear.

**Comment by robertmclaws** [comment]
Makes sense! Thanks for making this happen :)

**Comment by hakenr** [comment]
Will look into it. I think we should not add `InputGroupSize` but rather use `InputSize` and apply the requested size correctly to input-groups scenario.

**Comment by hakenr** [comment]
Current state: `InputGroupCssClass` is already there (comes from `IFormValueComponentWithInputGroups`) and should be rendered whenever set. Now we have to adjust the `InputSize` usage to set correct input-group-size when set.

**Comment by hakenr** [comment]
@Harvey1214 Use `IInputWithSize.InputSizeEffective` and add `input-group-sm` or `input-group-lg` as needed (see https://getbootstrap.com/docs/5.1/forms/input-group/#sizing)
