### ISSUE TITLE
Date Formatting on HxInputDate - MMM-dd-yyyy

### ISSUE THREAD

**Issue by stayboy** [havit/Havit.Blazor#114]
![image](https://user-images.githubusercontent.com/10756019/162952260-96d06db1-2296-47c1-b2b4-64cd27cef36d.png)

Date Display Formatting on Input with UTC Cultures

**Comment by hakenr** [comment]
@jirikanda, what do you think?

(Reminder to myself: There exist `@bind-Value:format="dd-MMM-yyyy"` and `@bind-Value:culture="en-US"` modifiers.)

Related links:
https://github.com/dotnet/aspnetcore/issues/15400

**Comment by DaleCam** [comment]
This would be very helpful!

**Comment by hakenr** [comment]
I carried out extensive research on the `@bind-Value:format` functionality and concluded that it is not suitable for our components. The format is not passed to the component as there's no `ValueFormat` convention similar to `ValueExpression`. Furthermore, the format is only applied externally, before binding the parameter and after retrieving the value.

Certainly, if we want to support something like a format-string beyond the scope of `CultureInfo.CurrentCulture`, we would need to introduce an additional parameter, for instance, `FormatString`.

From what I've seen, the majority of existing Blazor date-pickers operate using `CultureInfo` (the .NET standard for globalization), and thus, at this moment, I do not consider `FormatString` to be necessary.

**Comment by hakenr** [comment]
To emphasize, our implementation of `HxInputDate` and `HxInputDateRange` fully respects `CultureInfo.CurrentCulture`. Based on its settings, it formats the date and displays month names, among other things.

...I will add this to documentation.
