### ISSUE TITLE
Set range programmaticly of input forms

### ISSUE THREAD

**Issue by TeaTime762** [havit/Havit.Blazor#115]
Hey all,

when using validation you show on your example that one has to use the range attribut (https://havit.blazor.eu/components/Inputs)
But what if I want so set the range during runtime? As far as I know I can not set the value of an attribute at runtime.
I want to assign the max value for example through a parameter of a component.

I know the range attribut is from asp .net core but is there some wrapper in your library to solve that problem?

**Comment by TeaTime762** [comment]
Thank you so much for all the explaining and samples.

Do I understand that right that you will think about to add something like this in your library as you moved it to discussion?

**Comment by hakenr** [comment]
We currently use "Discussion" milestone as a marker for supportive discussions with the users without expected impact on the library itself.
