### ISSUE TITLE
HxSelect Null Detection For Empty String, Zero or non-existing value

### ISSUE THREAD

**Issue by stayboy** [havit/Havit.Blazor#116]
![image](https://user-images.githubusercontent.com/10756019/163347126-9eec0fec-bbaf-419c-bcbe-de44c9ab8530.png)

HxSelect giving out errors when binding value is zero, null or empty string or non-existing value. Error must either be mute or component must by default default to Nullable for Zero(0) and Empty String Values

**Comment by hakenr** [comment]
@jirikanda Can you please take a look at this issue?

**Comment by jirikanda** [comment]
Reprosteps are super simple:
```
<HxSelect Data="@data" @bind-Value="value" />

 @code {
    private List<int> data = new List<int> { 1, 2, 3, 4 };
    private int value = 0;
 }
 ```
 
The `Data does not contain item for current value` exception is thrown when the `value` is not found in the `data` and the `value` is not `null` (never for `Int32`).

@hakenr Should we change the code and consider not only `null` but also `default` as "null/empty" value?

**Comment by hakenr** [comment]
For now, we decided to stick with the `null` logic as the only special case when `Nullable` is set to true (and where we render `NullText`). (We also used to use this logic for out former ASP.NET WebForms components for years without any frustration.)
All the other cases (`0`, `String.Empty` or just `default(T)`) should be easy to map to this logic.

We might get back and review the decision if there will be more users asking for such change.

**Comment by wes-mytrailmate** [comment]
So what is the correct way to work around this?

**Comment by hakenr** [comment]
> What is the correct way to implement the example that @jirikanda posted?

You should use nullable `int?` type for TItem and set the default value to `null`:

```razor
<HxSelect Data="@data" @bind-Value="value" Nullable="true" NullDataText="-choose value-" />

 @code {
    private List<int?> data = new List<int?> { 1, 2, 3, 4 };
    private int? value = null;
 }
```
