### ISSUE TITLE
[HxTabPanel] breaks input spacing

### ISSUE THREAD

**Issue by Apskaita5** [havit/Havit.Blazor#119]
When using HxTabPanel to group inputs for a form, input spacing is broken (no spaces between inputs). Quick and dirty solution is to add `<br />` after each input. But it would be nice not doing that.

**Comment by hakenr** [comment]
@crdo, can you please take a look and asses this issue?

**Comment by crdo** [comment]
@Apskaita5 the default spacing of the inputs depends on the structure of your form and only works if the inputs are direct descendants of the form. 
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/1410922/164083984-b1d60ae5-af2d-4540-b1ab-285a2c21dedc.png">
If there is a more complex structure of your forms you have to add your own styles or use Bootstrap utility classes for spacing.
The combination of HxTabPanel and inputs is used in the documentation itself and the spacing is working.
If you still think there is some issue, please submit a reproducing repository.

**Comment by Apskaita5** [comment]
I meant the case when a form wraps a HxTabPanel, not vice versa. As I understand in this case it's impossible to avoid loosing form style?
I solved it by wrapping tab content in div and using css class:
.formpart {
    display: flex;
    flex-direction: column;
    gap: 1.25rem;
}
Would it be possible to allow setting css class for HxTab (content)? It would allow to skip div.

**Comment by crdo** [comment]
Sure, I am closing this div and please create a separate issue for the HxTab(Content) CSS class.
