### ISSUE TITLE
Unnecessary Downstream Dependencies

### ISSUE THREAD

**Issue by robertmclaws** [havit/Havit.Blazor#12]
Installing `Havit.Blazor.Components.Web.Bootstrap` (should probably be named `Havit.Web.Components.Bootstrap` for consistency with Microsoft's namespacing, but that's another issue) takes a dependency on Havit.Core, which apparently brings with it the following:

![image](https://user-images.githubusercontent.com/1657085/135727934-51349683-f34f-4328-9f82-0dccd0649000.png)

Everything below that should be unnecessary, especially if it has "Windows" in the package name.

Thanks!

**Comment by hakenr** [comment]
Hi @robertmclaws, thanks for highlighting the potential issue. We will investigate this deeper and eventually split the Havit.Core package into several smaller ones to avoid unnecessary dependencies.

**Comment by hakenr** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/12828888/136544960-fc358fe6-6019-48de-8cc8-2003b4a5d45d.png)

Published in release v1.4.2.
