### ISSUE TITLE
[HxAutosuggest] Tweaks to be able to use it as searchable select

### ISSUE THREAD

**Issue by Apskaita5** [havit/Havit.Blazor#120]
Could you add a searchable select component to your collection (e.g. https://github.com/Blazored/Typeahead)?
It's the only missing component for CRM apps (e.g. for selecting a client in a form).

**Comment by hakenr** [comment]
Hello @Apskaita5,
please take a look at **HxAutosuggest** (https://havit.blazor.eu/components/HxAutosuggest). It is designed to cover those scenarios.
Can you please add more information on what specific features are you missing?

**Comment by Apskaita5** [comment]
Blazored/Typeahead component allows for both selecting from a list and search. HxAutosuggest only allows search, not selection from a list. HxSelect allows selection from a list, not search.

**Comment by hakenr** [comment]
If you set `MinimumLength="0"` and `Delay="1"` (this is something we want to change to allow `0`) you should get a selection from list (see similar demo for HxInputTags https://havit.blazor.eu/components/HxInputTags#StaticSuggestions).

Is that what you need?

**Comment by Apskaita5** [comment]
That would be great except for two details:
- the dropdown doesn't have it's own scrollbar, which is a problem for long lists (just try it with your example, it has item collection big enough to demonstrate graphical result);
- the dropdown does not appear on focus when a value is already selected, which could be misleading for an end user.

;)

**Comment by hakenr** [comment]
@Apskaita5 Got it.
There are some additional tweaks needed to be able to use `HxAutosuggest` as searchable select.
This is valid usage scenario and we will make the adjustments needed.
If you find any additional issues, please let us know.

cc @crdo @jirikanda

**Comment by hakenr** [comment]
@Apskaita5 In the discussion we had today with the team, we decided to stick with the current behavior regarding the "dropdown does not appear on focus when a value is already selected" request. The referenced Typeahead component also does not open (it has a separate caret to open the dropdown).

We might reconsider the decision later, but for now, we think the current UX is better for most scenarios.
