### ISSUE TITLE
[HxInput*] - Some Components Not Rendering Additional Attributes

### ISSUE THREAD

**Issue by erikporter** [havit/Havit.Blazor#121]
I'm trying to add an `id` attribute to a `HxInputDate` (though appears all inputs do this) to line it up with the `for` on a `label` (that's dynamically rendered), but the component ignores any additional attributes and doesn't render them. The built in Input* components in Blazor do this, but Havit components don't. Is my assumption correct that this should work or is this a bug? I'm using version 2.3.0.

**Comment by hakenr** [comment]
Confirmed for `HxInputDate` and  `HxInputDateRange`. To be reviewed for all HxInputXy components (especially those forwarding the rendering to internal components - HxAutosuggest, HxInputTags, etc.).

**Comment by hakenr** [comment]
@erikporter Not sure this fix will solve your scenario, but it will be part of next release (you can already try with 2.5.0-pre4).
