### ISSUE TITLE
[HxInputNumber] Feature request: Support more datatypes for validation

### ISSUE THREAD

**Issue by TeaTime762** [havit/Havit.Blazor#122]
I would really appreciate it if you consider to implement more datatypes for validation. At the moment I think there are only double and int.
For example I am looking forward to validation for signed and unsigned int to validate the sign.
Another example would be int16 to validate the size of an int16.

**Comment by hakenr** [comment]
cc @jirikanda

**Comment by jirikanda** [comment]
Supported types: byte (Byte), sbyte (SByte), short (Int16), ushort(UInt16), int (Int32), uint(UInt32), long (Int64), ulong(UInt64), float (Single), double (Double) and decimal (Decimal).

**Comment by hakenr** [comment]
done
