### ISSUE TITLE
[HxInputNumber] Remove exception when Decimals are specified on integer

### ISSUE THREAD

**Issue by TeaTime762** [havit/Havit.Blazor#123]
I would suggest to remove the exception when you specify the deicmals parameter on HxInputNumber and instead set internally the decimals to zero when int is specify in the TValue parameter.
As a result it allows me to write components that are more reusable as I can use one component for both int and double inputs.

**Comment by hakenr** [comment]
@TeaTime762 Our motivation was to provide the users as much guidance as possible in such invalid combination.
Can you please provide us with some sample code where it would be helpful not to throw the exception and change the explicitly set value quietly instead?

cc @jirikanda

**Comment by TeaTime762** [comment]
Ok I show you a code sample want I want to achieve but what is actually not possible with you library. It goes along with my issue #122.

I am writing a component that allows a input and writes it to a specific node in a server.
The server needs to know which datatype the user wants to send which goes along with validation.

```
@inject IClientPlcConnectionService OpcUaWebService
<HxInputNumber Label="Layer number to start" TValue="Type" Decimals="Decimals" @bind-Value=EnteredNumber />

@code {

	public void InputChanged(int value)
	{

		if (Type == typeof(Int16))
		{
			OpcUaWebService.WriteNode(NodeId, Convert.ToInt16(value));
		}
		else if (Type == typeof(Int64))
		{
			OpcUaWebService.WriteNode(NodeId, Convert.ToInt64(value));
		}
		else
		{
			OpcUaWebService.WriteNode(NodeId, value);
		}


	}
	private int _enteredNumber;
	public int EnteredNumber
	{
		get { return _enteredNumber; }
		set
		{
			_enteredNumber = value;
			InputChanged(value);
		}
	}

	[Parameter]
	public int Decimals { get; set; }


	[Parameter]
	public string NodeId { get; set; }

	[Parameter]
	public Type Type { get; set; }


}
```

First problem is, when I specify int as TValue it throws always exception because of you exception.
Second problem is that I can specify in TValue only int32 and double but I would like to specify also int64, int 16 and so on. This is related to #122.

Did I explain well or does it only make sense in my head? :)

Looking forward you answer.

**Comment by hakenr** [comment]
I think your code probably won't for other additional reasons. You should either inherit your component directly from HxInputNumber (and add the InputChanged logic to `override InvokeValueChanged` method) or create a generic wrapper where the `Type` won't be a parameter but rather a generic type parameter `@typeparam` the `Decimals` parameter (or other appropriate lifecycle method such as `OnParametersSet`) should contain the the Decimal vs. Type synchronization logic.

BUT! We will adjust the `HxInputNumber.Decimal` setter to throw the exception only if non-zero value is being set for integer-types.

**Comment by TeaTime762** [comment]
Thank you very much for your detailed explanation and tips!
