### ISSUE TITLE
[HxListLayout] Multiple DataTemplate sections + Tabs navigation

### ISSUE THREAD

**Issue by crdo** [havit/Havit.Blazor#125]

**Comment by hakenr** [comment]
Same filter for all sections?

**Comment by crdo** [comment]
Each tab should have separate logic for searching and filtering, CommandsTemplate/DetailTemplate, etc...

**Comment by crdo** [comment]
@hakenr Adding screenshot with desired outcome.
<img width="910" alt="image" src="https://user-images.githubusercontent.com/1410922/165534101-b04c32d7-48cd-4390-b043-77a793c5de02.png">

**Comment by crdo** [comment]
@hakenr so you might be right - if I give the HxListLayout CssClass border-0, it makes it "naked" and I could just wrap it with another card with tabs navigation.

**Comment by crdo** [comment]
@Harvey1214 pleas add a demo for this layout to the docs. Thanks.

**Comment by Harvey1214** [comment]
@crdo sure thing - https://dev.azure.com/havit/DEV/_git/002.HFW-HavitBlazor/commit/e934340c3c8425d36bdf31792a93b04566ffd5ca
