### ISSUE TITLE
[HxModal] dispose/hide issues

### ISSUE THREAD

**Issue by stayboy** [havit/Havit.Blazor#126]
![image](https://user-images.githubusercontent.com/10756019/165713174-71a444d4-4967-4580-b1c6-a13c85e3239a.png)

Kindly check your queue mechanism in close HxModal. It seems to get fired at the wrong time. Dispose is called on the Modal Instance and another call is made after to cleanUp when the this._element had already been disposed

**Comment by hakenr** [comment]
Reproduced (put `<a href="">test</a>` into the body and the issue appears).
