### ISSUE TITLE
[HxSideBar] Collapse doesn't hide brand name

### ISSUE THREAD

**Issue by vinod-vetrivel** [havit/Havit.Blazor#127]
When the sidebar is collapsed, the brand name overflows. 

Screen grab from the demo site:
![image](https://user-images.githubusercontent.com/64571006/165920120-44063387-ff1f-43e9-8f2f-d7f03c80da59.png)

**Comment by crdo** [comment]
Hi @vinod-vetrivel [vinod-vetrivel](https://github.com/vinod-vetrivel), fix for this issue has been done already and will be part of the forthcoming release.

**Comment by hakenr** [comment]
Can be tested in 2.5.0-pre4 release.

**Comment by vinod-vetrivel** [comment]
Thank You
