### ISSUE TITLE
[Documentation] ButtonGroup and ButtonToolbar docs broken

### ISSUE THREAD

**Issue by robertmclaws** [havit/Havit.Blazor#13]
Just a heads up, the docs in the following locations are broken:

https://havit.blazor.eu/components/HxButtonGroup
https://havit.blazor.eu/components/HxButtonToolbar

Tried to fix them myself and submit a pull request, but I could not find the problem.

Thanks!

**Comment by hakenr** [comment]
Hi @robertmclaws, the page is already fixed (that's why you were not able to find the problem), but the fix has not been deployed to production yet. Next release is planned today/tomorrow.
Thanks for your patience and willingness to help.
