### ISSUE TITLE
InputFileDropZone is not work in FireFox

### ISSUE THREAD

**Issue by rqx110** [havit/Havit.Blazor#140]
as title

**Comment by hakenr** [comment]
@Harvey1214 Can you please confirm and provide more details on the issue?

**Comment by rqx110** [comment]
I am using Firefox v100.0 on windows 10 x64, see below GIF image, after drop a file it has nothing in the dropzone but open a new tab.
![ff1](https://user-images.githubusercontent.com/1829209/167520963-35e6450c-08d3-412e-81c5-9b8b5a3a9f75.gif)

**Comment by hakenr** [comment]
Strange. Do the "other" drag&drop file upload implementations work in your browser?
I found many posts related to Firefox/Mozilla issues with drag&drop uploads, e.g.
* https://www.google.com/search?q=upload+file+drag+drop+firefox&oq=upload+file+drag+drop+firefox - Google Search
* https://stackoverflow.com/questions/54474158/drag-and-drop-upload-not-working-in-mozilla
* https://stackoverflow.com/questions/53370893/drag-and-drop-file-upload-not-working-in-firefox
* https://superuser.com/questions/1652723/why-i-can-no-longer-drag-and-drop-files-into-firefox - Windows UAC? Might this be the difference in between the two Firefox instances you are using?

To be honest, Firefox is currently not on our priority list, although we would like to have the library as compatible as possible. Which means, if there is any chance for simple fix (which won't affect other browsers or maintainability), we will accept that.

Feel free to submit a pull-request if you find any solution.

**Comment by rqx110** [comment]
Found it is because my localize(zh-CN) Firefox version which download from https://www.firefox.com.cn/, which will install some extesions as default, and one of extesion cause this issue.
so close this issue.
thanks of your great componet!
