### ISSUE TITLE
[Question] Is there a parameter that is equivalent to the ref parameter from blazor?

### ISSUE THREAD

**Issue by TeaTime762** [havit/Havit.Blazor#143]
Hello,

is there a parameter where I can assign the the ref parameter?

`    <HxButton @ref="button" Text="@ButtonText" Size="ButtonSize.Regular" Color="ThemeColor.Primary" OnClick="async () => await CallMethod()"  CssClass=@Style @onfocusout="LostFocus"/>`

When assigning it to @ref, the compiler tells me following error:

Cannot implicitly convert type 'Havit.Blazor.Components.Web.Bootstrap.HxButton' to Microsoft.AspNetCore.Components.ElementReference'

**Comment by hakenr** [comment]
The `button` field in your class has to be `HxButton` type (I guess it is `ElementReference` in your code now).

**Comment by TeaTime762** [comment]
yeah, you are right, thank you. 
But then I can access the methods I had in ElementReferenceExtensions, for example 
`        //
        // Summary:
        //     Gives focus to an element given its Microsoft.AspNetCore.Components.ElementReference.
        //
        // Parameters:
        //   elementReference:
        //     A reference to the element to focus.
        //
        // Returns:
        //     The System.Threading.Tasks.ValueTask representing the asynchronous focus operation.
        public static ValueTask FocusAsync(this ElementReference elementReference);
`

**Comment by hakenr** [comment]
`HxButton` currently does not publish the ElementReference to the underlying `<button />` element, nor has an own `FocusAsync()` method.
In current state (subject to change), you can derive you own button component by inheriting from `HxButton` and that gives you access to a protected field called `buttonElementReference` where you can apply you `FocusAsync()` extension method, e.g.
```csharp
public class MyDerivedButton : HxButton
{
  public Task FocusAsync() => buttonElementReference.FocusAsync();
}
```

Please note that the protected `buttonElementReference` field is not officially supported and may disappear in any future version of our library.

**Comment by TeaTime762** [comment]
Oh ok cool.
What a pity that it may be disappear.
Do you plan a substitute property/ field or do you plan not to expose buttonElementReference at all and neither any substitue methods in HxButton?

**Comment by hakenr** [comment]
No plans.
The field was introduced when we realized we need the ElementReference in our own derived component - the `HxDropdownToggleButton`. It probably should have been marked as `private protected`, but it was not. We probably won't remove it any soon, but as it does not satisfy design guidelines for public-API, we don't promise it won't change any later. The change will probably still have to offer an alternative property/field as we need it for `HxDropdownToggleButton`.

**Comment by TeaTime762** [comment]
Sounds good, thanks!
