### ISSUE TITLE
[HxInputFile] Feature proposal: binding to stream

### ISSUE THREAD

**Issue by Apskaita5** [havit/Havit.Blazor#144]
I use UI binding to my domain objects. Some of them include relatively complex structures with Stream properties for various business entity specific file uploads. To avoid manual binding with HxInputFile I have created
1. a lightweight Stream descendant that wraps IBrowserFile making it available for binding to Stream properties (attached).
2. a HxInputFile wrapper component that adds standard databinding functionality for the Stream (also attached).

Not sure how much spread the scenario like this is, yet if you think it is of general value, you could add it to your framework.
[StreamBinding.zip](https://github.com/havit/Havit.Blazor/files/8662739/StreamBinding.zip)

**Comment by hakenr** [comment]
I was looking at the provided source code. I think it can be useful for a lot of users. However, I still think it's not a good fit to become part of our libraries. It's not specific to our components or code organization and can very well work as a separate NuGet package usable with many file-components. So, I rather recommend going that way.

Thank you for the offer, we appreciate your willingness to contribute.
