### ISSUE TITLE
[HxSearchBox] To add SubItemCssClass

### ISSUE THREAD

**Issue by crdo** [havit/Havit.Blazor#147]
We need SubItemCssClass for some additional styling at G3. 
Please add it to the component API.

**Comment by hakenr** [comment]
@crdo What is the scenario?
@Harvey1214 If really necessary, it should be rather `ChildItemCssClass`.

**Comment by crdo** [comment]
@hakenr I need to fine tune the appearance of the second line of the suggested item 
<img width="491" alt="image" src="https://user-images.githubusercontent.com/1410922/168226396-91f7ab9f-97d8-49e3-81a1-665bdc19a55c.png">

**Comment by hakenr** [comment]
@crdo Oops, I mistook it for `HxTreeView`, so the name should be `SubtitleCssClass`.

...I think we should clean-up the default implementation, which is now (lines 12-13 hardcoded etc.)
https://github.com/havit/Havit.Blazor/blob/6a78a91c2a27219525d73a38530fb77ddeb99d62/Havit.Blazor.Components.Web.Bootstrap/Forms/SearchBox/Internal/HxSearchBoxItem.razor#L3-L20

**Comment by hakenr** [comment]
@crdo BTW the screenshot shows current weirdness - if you set Subtitle, the Title becomes `strong`. If the Subtitle is not set, it stays regular. 🤷‍♂️

**Comment by Harvey1214** [comment]
[https://github.com/havit/Havit.Blazor/commit/b80189cf91517720b920010a9e2a356250bfdad9](url)
