### ISSUE TITLE
Why is there a hidden text shown for a HxSpinner or a spinner button?

### ISSUE THREAD

**Issue by TheAnachronism** [havit/Havit.Blazor#152]
I've played around with the CSS styling of my project a bit and found out that the spinner component shows some hidden text if you activate it.
https://github.com/havit/Havit.Blazor/blob/d4c89c6e1a8b0b54205d3d00ce05591642117406/Havit.Blazor.Components.Web.Bootstrap/Progress/HxSpinner.razor

I'm just wondering why is this necessary as if you have some weird screen resolution, a scroll bar sometimes appears because this text is spinning around…

**Comment by hakenr** [comment]
Hi @TheAnachronism,
this was taken over from Bootstrap: https://getbootstrap.com/docs/5.1/components/spinners/:

>For accessibility purposes, each loader here includes `role="status"` and a nested `<span class="visually-hidden">Loading...</span>`.

**Comment by TheAnachronism** [comment]
Ah, OK, fair enough.
Thanks for the answer^^
