### ISSUE TITLE
[HxSidebarItem] Weird `no-icon` class when Icon is not null

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#156]
@crdo When implementing #78 I found this weird line of code:
https://github.com/havit/Havit.Blazor/blob/0af8b66406b2bdaf12311649d8cd3d3fea9a04eb/Havit.Blazor.Components.Web.Bootstrap/Navigation/HxSidebarItem.razor#L45
It renders `no-icon` class when there actually is the Icon set.
It was introduced when @Harvey1214 was extracting all hardcoded utility classes to CSS isolation.
![image](https://user-images.githubusercontent.com/12828888/169239492-933a4f27-5dc9-440b-89a3-3f8ecae2c647.png)

The name should probably be `hx-sidebar-item-text-with-icon` or something like that. :-D
BTW: The `text` class should have been renamed to something like `hx-sidebar-item-text`?
..and `.navbar-desktop-toggler` is also our own class which should get the `hx` convention?

BTW: The line 18 remained unextracted:
https://github.com/havit/Havit.Blazor/blob/0af8b66406b2bdaf12311649d8cd3d3fea9a04eb/Havit.Blazor.Components.Web.Bootstrap/Navigation/HxSidebarItem.razor#L18

**Comment by hakenr** [comment]
Is `bi-chevron-right` custom as well?

**Comment by crdo** [comment]
Yes, this clearly needs some review and polishing. I'll do that.

**Comment by crdo** [comment]
Done.

**Comment by crdo** [comment]
Note to my future myself: I have changed the layout of `HxSidebarItem` to horizontal stack so we can get rid of separate spacing for version with and without an icon.
