### ISSUE TITLE
[HxGridColumnBase] Asynchronnous method called from synchronnous Dispose?

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#158]
`Task ColumnsRegistration.Unregister(this);` is asynchronnous.
It is currently called from synchronnous `Dispose()` method in `HxGridColumnsBase`

@jirikanda , should we rather go for `IAsyncDisposable`?

**Comment by jirikanda** [comment]
Ups. It brings back the issue #107. Trying fix with try/catch & NOOP in the CollectionRegistration class.
