### ISSUE TITLE
[HxMessenger] Notice appears under top nav bar with top positions

### ISSUE THREAD

**Issue by rmmcgr** [havit/Havit.Blazor#175]
I have found when using ``ToastContainerPosition.TopCenter`` (or top start or top end), that the notice is appearing under the top nav bar (setup with HxNavbar).

I have applied a class that set's the z-index to 10000 to work around the problem for now.

**Comment by crdo** [comment]
Can not reproduce. The hx-toast-container has its `z-index` set to `1080` - that is highest value of all Bootstrap components. It should be alright.

What is your version of HAVIT Blazor?

**Comment by rmmcgr** [comment]
I am on the latest (2.6.3).

I can see that the navbar has a z-index of 1080, but when I inspect the messenger placeholder element I can't see a z-index applied.

I am including the components CSS reference in the "_Hosts" file:

`<link href="_content/Havit.Blazor.Components.Web.Bootstrap/defaults.css" rel="stylesheet" />`

This is what I can see in the browser coming through from this file (assuming I am inspecting this correctly):

<img width="387" alt="image" src="https://user-images.githubusercontent.com/6520697/170971924-1f48da57-46c1-4a4a-8351-dc041d2c0572.png">

When I specifically inspect the element `<div class="hx-toast-container position-fixed start-50 translate-middle-x" b-s6wlosgh2n=""></div>`, the "Computed" inspector does not show any z-index applied.

I have realised I am using it with the 5.2 beta of Bootstrap - not sure if that would be the problem or not?

Thank you for any help.

**Comment by hakenr** [comment]
The rule
```css
.hx-toast-container {
	z-index: 1080;
	margin: var(--hx-toast-container-margin);
}
```
is carried in CSS-isolation. Do you reference the Blazor CSS isolation styles from you _Hosts file?
```html
<link href="Your.Blazor.Project.Assembly.Name.styles.css" rel="stylesheet" />
```

**Comment by rmmcgr** [comment]
Ok, thank you. That was it - I did not have that reference in my _Hosts file. 

I thought that was only needed if I was doing CSS isolation for my own components, not ones coming from other frameworks.

Thank you!

**Comment by hakenr** [comment]
Unfortunately, Blazor mixes all the CSS isolations together (using @import directives) and the reference has to be there.
