### ISSUE TITLE
[HxAccordionItems] are not collapsed correctly (not tracking DOM state?)

### ISSUE THREAD

**Issue by pepe-marba** [havit/Havit.Blazor#182]
I found a problem when using the HxAccordion component, This Accordion displays a collection of items that need to be sorted as per user request.

These items have sub items that are displayed when the HxAccordionItem component is expanded.

The problem comes after sorting the items, some times there are more than one item expanded when it's supposed that only one should be displayed as expanded.

I have created a small project to test this, and the steps to reproduce the error are these:
1.- Expand any item, but the first one, in the Teams to Sort section.
2.- Click the Sort DESC button.
3.- Expand the first Item in the list
4.- Click the Sort ASC button.
5.- You should see two expanded items displayed.

These is another way to reproduce the issue:
1.- Expand the first item
2.- Click the Sort Desc button
3.- Expand the element in the first position after sorting the items.
4.- Two items should be displayed as expanded.

I found other different ways to reproduce the issue but I wasn't able to reproduce them in order to explain the steps to follow.

In this [link ](https://github.com/pepe-marba/havit-demo) you could find the small project I created for this.

This is how the 2 items look as expanded
![image](https://user-images.githubusercontent.com/8064119/170776031-e35be9d5-e175-41fa-ad78-184f8a700525.png)

Thanks

**Comment by hakenr** [comment]
The current HxAccordion implementation does not track DOM state. When user expands/collapses any item, the Blazor-HxAccordionItem is not aware of it. When re-rendering, Blazor identifies and applies only some DOM differences and the reported behavior occurs.

The solution is to track DOM state in HxAccordion, or better to track DOM state in HxCollapse na and refactor HxAccordion to use HxCollapse internally (#79).

The only thing we are afraid od is the cost of DOM state tracking (listening to hidden/shown events). This might bring some performance costs. We will consider adding TrackState parameter to such components (HxDropdown is another example).

**Comment by hakenr** [comment]
@pepe-marba We are still refactoring the HxAccordion and trying to make it better, but for now, you can resolve your issue by setting `@key="@team.Id"` for `HxAccordionItem`.

**Comment by hakenr** [comment]
In the end, after refactoring HxAccordionItem to HxCollapse, we decided to go for `@key` requirement in dynamic scenarios. We might change this in future (won't be breaking change).

https://github.com/havit/Havit.Blazor/blob/8b716945bbf9a6e83319cc87545b87a6c786c671/Havit.Blazor.Components.Web.Bootstrap/Accordions/HxAccordionItem.razor.cs#L76-L86

**Comment by pepe-marba** [comment]
this approach worked for me, thanks for your help
