### ISSUE TITLE
[HxGrid] ContextMenuCssClass parameter

### ISSUE THREAD

**Issue by alexax578** [havit/Havit.Blazor#187]
We would like to be able to set css classes on ContextMenu created using ContextMenu RenderFragment parameter the same way we are able to set css classes on HxGridColumn using ItemCssClass parameter.

Right now for our ContextMenu we have to use a workaround where we define ContextMenu as HxGridColumn
with parameter Order = int.MaxValue - 1.

**Comment by hakenr** [comment]
Will probably go with `HxGrid.ContextMenuSettings` to be able to pass additional settings to the `HxContextMenu` encapsulated inside `HxGrid`.

**Comment by hakenr** [comment]
released
