### ISSUE TITLE
[HxDropdown] Missing menu alignment properties

### ISSUE THREAD

**Issue by robertmclaws** [havit/Havit.Blazor#189]
I have a situation where I need to be able to specify that the dropdown opens pinned to the right side element triggering it.

The Bootstrap equivalent class is `dropdown-menu-end`: https://getbootstrap.com/docs/5.0/components/dropdowns/#menu-alignment

Maybe a `DropdownAlignment` enum with `Auto, Right, Left` options would suffice.

**Comment by robertmclaws** [comment]
Up and Down don't seem to be useful in this case, so there might need to be something different. The Auto behavior would make it as wide as possible if the opened menu is huge, or if the target element is big, making it the same width as the target.

**Comment by hakenr** [comment]
Ahh, I see, it is not the _direction_, it is the _alignment_. Got it.

**Comment by hakenr** [comment]
@robertmclaws What is the behavior of `Auto`? For now, we decided to start with `null` as default (not set).
+ we won't support strong-type API for responsive variants, you can still set the `HxDropdownMenu.CssClass` directly.

**Comment by robertmclaws** [comment]
I wouldn't consider "Auto" a "responsive" variant, it would allow for this:

**Comment by hakenr** [comment]
released
