### ISSUE TITLE
[HxCalendar] DisplayMonthChanged event fires twice when display month is changed

### ISSUE THREAD

**Issue by vesnicancz** [havit/Havit.Blazor#195]
If I have a selected date in calendar and I react to a change in selected date using events, the month cannot be changed (by arrows or by picking form year and month popups).
The DisplayMonthChanged event is fired twice.
For the first time with a new date. For the second time with the original one.
Simple repro page is atteched.
[HxCalendarBugRepro.zip](https://github.com/havit/Havit.Blazor/files/8821747/HxCalendarBugRepro.zip)

**Comment by jirikanda** [comment]
Will be fixed in the upcoming release.
