### ISSUE TITLE
[HxGrid] [HxTabPanel] UpdatedContentRenderer is useless

### ISSUE THREAD

**Issue by jirikanda** [havit/Havit.Blazor#199]
We found no scenario where it helps.

**Comment by hakenr** [comment]
@jirikanda MensaGymnazium.IntranetGen3 feels quicker now.

**Comment by hakenr** [comment]
@jirikanda It seems that the change exposed another bug
![image](https://user-images.githubusercontent.com/12828888/172340757-345b0416-a7ab-421a-8247-b608072dd63b.png)

The `DisposeAsyncCore()` is quick-fixed now (release 2.6.6-pre2), but I didn't have a chance to investigate the reason for this "exposure" and whether there are another more severe consequences.

**Comment by jirikanda** [comment]
Yeah, I have seen this (including your fix).
It is probably connected to #201, not to this issue.
