### ISSUE TITLE
[HxGrid] Grid rows have role="button" even when `[Multi]SelectionEnabled` is not set

### ISSUE THREAD

**Issue by crdo** [havit/Havit.Blazor#205]
Grid rows have role="button" even when SelectedDataItem is not set.
It causes wrong cursor on hover when row is not clickable.

**Comment by hakenr** [comment]
I think it should depend on `[Multi]SelectionEnabled`.

**Comment by hakenr** [comment]
It seems to be handled appropriately in the code.
