### ISSUE TITLE
[HxSidebar] Custom collapsible item?

### ISSUE THREAD

**Issue by czmirek** [havit/Havit.Blazor#222]
Hello,

I'm trying to figure out how in your [documentation](https://havit.blazor.eu/) the theme dropdown disappears and only the github icon shows.

Before sidebar collapse
![image](https://user-images.githubusercontent.com/18615545/175786842-aa9b3d2f-2c42-4974-94fe-1983f214b95a.png)

After sidebar collapse
![image](https://user-images.githubusercontent.com/18615545/175786864-ad33a149-ca47-4a23-8a37-eae24c072bbf.png)

I think I'm going to figure it out from CSS profiling...but it would be very cool if the documentation directly mentioned how to do it.

It would also be cool if there was a support for razor syntax distinguishing uncollapsed and collapsed sidebar item:

```razor
<HxSidebarItem>
   <Uncollapsed>
      some html
   <Uncollapsed>
   <Collapsed>
      some html
   </Collapsed>
</HxSidebarItem>
```

**Comment by crdo** [comment]
Hi @czmirek the `HxSidebar` has a `collapsed` class so hiding the theme input depends on it in custom styles of the docs page (`display: none`).
We know that there is some debt in the `Collapsed/Uncollapsed` API of `HxSidebar`, specifically in its footer and it will be subject of a further development.
There are multiple open issues related to `HxSidebar` so we will give it some upgrade soon.

**Comment by hakenr** [comment]
There is new `<ContentTemplate>` parameter added to `HxSidebarItem` component in last release (2.7.3).
The desired effect can be achieved through the `.collapsed` class as mentioned above.
Closing this for now.
If you feel there is still something what should be fixed/added to the library, feel free to reopen the issue / add comments.
