### ISSUE TITLE
[HxSidebar] Enable/disable responsive behavior

### ISSUE THREAD

**Issue by alexax578** [havit/Havit.Blazor#228]
I would like to be able to disable HxSidebar responsive behavior which stems from Bootstrap Navbar -> burger menu.

**Comment by hakenr** [comment]
😮 ...not sure if this still the `HxSidebar`.

**Comment by hakenr** [comment]
Seems to be doable, probably something like `<HxSidebar ResponsiveBreakpoint="Md | ... | null" />` (ability to set the responsive breakpoint incl. `null` as disabled).
