### ISSUE TITLE
[HxSidebar] Whitespace between item icon and text not aligned (items w/ vs. wo/ children)

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#231]
![image](https://user-images.githubusercontent.com/12828888/176559568-7a547ea2-3bbc-4b0b-885a-7096955451ee.png)

See https://havit.blazor.eu/components/HxSidebar

**Comment by crdo** [comment]
IMHO it doesn't make sense to fix this as the `login` part is just some custom `RenderFragment` and we should rather focus on #222.

**Comment by hakenr** [comment]
It is not just the `login` part, but see the difference in between _Subitems with icons_ (item with children) and _First-level item 1_ (item without children).

**Comment by hakenr** [comment]
fixed
