### ISSUE TITLE
[HxSidebar] --hx-sidebar-brand-logo-background-color CSS variable unset?

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#232]
When using `HxSidebarBrand` (without logo), without setting any CSS variable, the brand is "invisible":
![image](https://user-images.githubusercontent.com/12828888/176623145-3f6e8327-0ca3-4ef2-8c00-71e8b5ee3cd7.png)

I have to set the `--hx-sidebar-brand-logo-background-color` to get it visible:
```css
:root {
	--hx-sidebar-brand-logo-background-color: var(--bs-primary);
}
```

The default value for `--hx-sidebar-brand-logo-background-color` is `unset` (in contrary to the doc):
![image](https://user-images.githubusercontent.com/12828888/176623609-ebfb1cab-fcb7-4589-a6ac-a71a0b401be2.png)

I think this was introduced due to the `Logo` version of the `HxSidebarBrand`:
```razor
        <HxSidebarBrand BrandName="HAVIT Blazor">
            <Logo>
                <img src="/logo.png" width="35" height="35" />
            </Logo>
        </HxSidebarBrand>
```
where there is no background expected.

@crdo Can we somehow adjust the structure to have different background setting for the text-version if the brand (`var(--bs-primary)`) and the logo-version (no background color)?

**Comment by hakenr** [comment]
+ [ ] If implemented, remove the CSS rule for `--hx-sidebar-brand-logo-background-color` from NewProjectTemplate site.css

**Comment by crdo** [comment]
@Harvey1214 please review my commit. Thx.

**Comment by Harvey1214** [comment]
@crdo lgtm, css vars for setting background color and border radius for logo version would be nice though.

**Comment by crdo** [comment]
@Harvey1214 I think that if you use image as logo, It should be created in a way you want to use it and you should not be correcting its appearance by applying CSS.

**Comment by hakenr** [comment]
closing as resolved
