### ISSUE TITLE
[HxGrid] Invalid order of optional columns

### ISSUE THREAD

**Issue by vesnicancz** [havit/Havit.Blazor#233]
If I have a grid with several columns, some of which are optional, then optional columns are rendered in invalid order.
[Grid.zip](https://github.com/havit/Havit.Blazor/files/9019159/Grid.zip)
![Repro](https://user-images.githubusercontent.com/709508/176662046-418c23c7-a396-456b-bce5-e64aafc80e3c.png)
.

**Comment by jirikanda** [comment]
Hi @vesnicancz,
you reached a blazor design feature.

Use HxGridColumn.Visible property instead of @if (...) for showing/hiding columns.
Alternatively, use HxGridColumn.Order property.

See https://havit.blazor.eu/components/HxGrid
