### ISSUE TITLE
Havit.Blazor.Components.Web.Bootstrap - Project build failed

### ISSUE THREAD

**Issue by gnnsekhar** [havit/Havit.Blazor#248]
Havit.Blazor.Components.Web.Bootstrap - Project build failed

Build failed due to Havit.Blazor.Components.Web.Bootstrap.InternalSourceGenerators not generating the bootstrap icons.
~\Source\Repos\Havit.Blazor_Harvey\Havit.Blazor.Components.Web.Bootstrap.InternalSourceGenerators\bin\Debug\netstandard2.0\Havit.Blazor.Components.Web.Bootstrap.InternalSourceGenerators.dll

'BootstrapIcon' does not contain a definition for 'Filter'
3>C:\Users\Gnanasekhar K\Source\Repos\Havit.Blazor_Harvey\Havit.Blazor.Components.Web.Bootstrap\Navigation\HxSidebar.razor.cs(21,72,21,87): error CS0117: 'BootstrapIcon' does not contain a definition for 'ChevronBarRight'
3>C:\Users\Gnanasekhar K\Source\Repos\Havit.Blazor_Harvey\Havit.Blazor.Components.Web.Bootstrap\Navigation\HxSidebar.razor.cs(26,74,26,88): error CS0117: 'BootstrapIcon' does not contain a definition for 'ChevronBarLeft'
3>C:\Users\Gnanasekhar K\Source\Repos\Havit.Blazor_Harvey\Havit.Blazor.Components.Web.Bootstrap\Grids\HxGrid.nongeneric.cs(22,39,22,52): error CS0117: 'BootstrapIcon' does not contain a definition for 'SortAlphaDown'
3>C:\Users\Gnanasekhar K\Source\Repos\Havit.Blazor_Harvey\Havit.Blazor.Components.Web.Bootstrap\Grids\HxGrid.nongeneric.cs(23,40,23,56): error CS0117: 'BootstrapIcon' does not contain a definition for 'SortAlphaDownAlt'
3>C:\Users\Gnanasekhar K\Source\Repos\Havit.Blazor_Harvey\Havit.Blazor.Components.Web.Bootstrap\Forms\Autosuggests\HxAutosuggest.nongeneric.cs(18,32,18,38): error CS0117: 'BootstrapIcon' does not contain a definition for 'Search'
3>C:\Users\Gnanasekhar K\Source\Repos\Havit.Blazor_Harvey\Havit.Blazor.Components.Web.Bootstrap\Forms\Autosuggests\HxAutosuggest.nongeneric.cs(19,31,19,34): error CS0117: 'BootstrapIcon' does not contain a definition for 'XLg'
3>C:\Users\Gnanasekhar K\Source\Repos\Havit.Blazor_Harvey\Havit.Blazor.Components.Web.Bootstrap\Forms\SearchBox\HxSearchBox.nongeneric.cs(18,31,18,37): error CS0117: 'BootstrapIcon' does not contain a definition for 'Search'
3>C:\Users\Gnanasekhar K\Source\Repos\Havit.Blazor_Harvey\Havit.Blazor.Components.Web.Bootstrap\Forms\SearchBox\HxSearchBox.nongeneric.cs(19,30,19,33): error CS0117: 'BootstrapIcon' does not contain a definition for 'XLg'

**Comment by hakenr** [comment]
@gnnsekhar I have seen this on some machines, not sure what was the reason. Please try _Clean Solution_ and _Rebuild All_.
(See [CI build](https://github.com/havit/Havit.Blazor/actions) where it builds successfully, it has to be something local.)

**Comment by jirikanda** [comment]
@gnnsekhar And I have seen issues with not-up-to-date Visual Studio. Try to update Vistual Studio (if used) to the latest version.

**Comment by hakenr** [comment]
I'm closing this issue now. If you feel there is something to fix in the project, feel free to reopen it (add comment).
