### ISSUE TITLE
[HxSearchBox] cannot confirm selected item with keyboard `Enter` key

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#254]
https://havit.blazor.eu/components/HxSearchBox - basic Demo
1. Type `Doo`, _Door_ item is suggested.
2. Navigate to the first item with _ArrowDown_ key on keyboard (gets focus).
3. Hit `Enter`.

Nothing happens.
The item should be confirmed, the dropdown should close, etc. (as if it was clicked with mouse).

![image](https://user-images.githubusercontent.com/12828888/178936873-25301ee5-bd2f-40a0-8143-02981f5183e7.png)

**Comment by crdo** [comment]
@hakenr @Harvey1214 alright we can roll-back the solutions with buttons and document that the ItemTemplate content has to be inline elements only so the HTML is valid.

**Comment by hakenr** [comment]
@crdo Mrkni na ten můj commit prosím, snažil jsem se tam vrátit `button` a dostat to do validního stavu. Ale měl bys to radši vidět. :-D

**Comment by crdo** [comment]
Až na tohle je to OK. 
<img width="800" alt="image" src="https://user-images.githubusercontent.com/1410922/184652460-d6642ff7-4157-4b4c-8149-9a25eb180ced.png">

**Comment by hakenr** [comment]
@crdo OK, fixnu. By mě jeblo, s těma ul/li, to je podle mě přežitek, ale ok.
