### ISSUE TITLE
[HxSidebar] Enable defaults and settings for HeaderTemplate and TogglerTemplate

### ISSUE THREAD

**Issue by alexax578** [havit/Havit.Blazor#261]
I would like to be able to set default values for TogglerTemplate and HeaderTemplate.

My current solution is that I have a component derived from HxSidebar which has the following implementation in OnParametersSet.
```csharp
class MySidebar : HxSidebar
{
    protected override void OnParametersSet()
    {
        HeaderTemplate ??= builder =>
        {
            builder.openElement(100, "a");
            ...
        };
        ...
    }
}
```
If defaults and settings would be implemented the same way they are on HxButton I could override GetDefaults in my derived MySidebar component.
![image](https://user-images.githubusercontent.com/37944469/179705351-167d051a-1c06-48ec-98e0-acfadd8ae742.png)

**Comment by hakenr** [comment]
Such setting in `Defaults` does not add much value. You can easily "set" the default value in you derived component by overriding get `SetParametersAsync()` method and use the `this.MyParameter = parameters.GetValueOrDefault(nameof(MyParameter), myNewDefaultValue);`
