### ISSUE TITLE
[HxCard] Add virtual GetCssClass method

### ISSUE THREAD

**Issue by alexax578** [havit/Havit.Blazor#262]
I need to add a CssClass to my derived Card component permanently. I think the same pattern as the GetTableElementCssClass method on HxGrid is suitable.

**Comment by alexax578** [comment]
I personally would prefer if each component had virtual methods that I could override in a derived component but the same point as with [#261](https://github.com/havit/Havit.Blazor/issues/261) can be applied here. I used SetParametersAsync where I get the value of CssClass parameter and attach my CSS class to it if it isn't there already.

```
var cssClassValue = parameters.GetValueOrDefault(nameof(CssClass), string.Empty);
CssClass = cssClassValue.Contains("bt-card")
    ? cssClassValue
    : CssClassHelper.Combine(cssClassValue, "bt-card");
```

**Comment by hakenr** [comment]
I think this is the issue we are already discussing in #204, will be resolved there (set/override `CoreCssClass` property).
