### ISSUE TITLE
[HxInputFileCore] Trigger file selection dialog by clicking on an external button

### ISSUE THREAD

**Issue by alexax578** [havit/Havit.Blazor#263]
I would like to be able to select a file for the input by clicking on an external button.  Maybe **HxInputFileCore** component could expose Click method where I would be able to use it in my scenario like this?

```csharp
<HxButton OnClick="HandleSelectFileClick />
<HxInputFileDropZone @ref="inputFileComponent" />

public void HandleSelectFileClick()
{
    // Simulates click on the input file component -> opens dialog with file selection
    inputFileComponent.Click();
}
```

**Comment by alexax578** [comment]
@hakenr For now I implemented this functionality in BT2 project using JS Interop:
```javascript
document.querySelector(".hx-input-file-drop-zone input[type='file']").click();
```

**Comment by hakenr** [comment]
Just for the record. We decided not to implement any direct `OpenAsync()` method on `HxInputFileCore` nor `HxInputFileDropZone` as the `.click()` approach (on `input file`) appears to be kind of offensive (and might be blocked by browsers  some time). As there is a working workaround for now, we decided to stay on the safe side.
