### ISSUE TITLE
[HxInputTags] AddButton doesn't re-appear when using StaticSuggestions after onBlur

### ISSUE THREAD

**Issue by crdo** [havit/Havit.Blazor#277]
1. Use naked version with static suggestions
2. Click in to get a focus
3. Click out
4. Add button doesn't appear

**Comment by bholbrook** [comment]
The add button doesn't appear after many interactions with the input.
Perhaps we could have it so that the add button is permanently visible?

**Comment by hakenr** [comment]
Fixed for the repro-steps provided. If there are any additional scenarios where the AddButton does not reappear, please let me know.

cc @bholbrook
