### ISSUE TITLE
[HxInputFileDropZone] Template parameter when files are selected

### ISSUE THREAD

**Issue by alexax578** [havit/Havit.Blazor#280]
I would like to be able to customize the visuals of the `HxInputFileDropZone` component when files are selected. Maybe the same way we have NoFilesTemplate, we could have FilesSelectedTemplate or something like that.

**Comment by hakenr** [comment]
Currently the `HxInputFileDropZone` is very simple wrapper of `HxInputFileCore` and the intention was: Whenever there is need for custom UI, replicate the drop-zone implementation on your own and customize as needed.

(For the template you want, it is not clear whether to provide Context with IEnumerable of files, or string with list of files, or ...)
