### ISSUE TITLE
HxGrid.Defaults Page Navigation Settings

### ISSUE THREAD

**Issue by blimkemann** [havit/Havit.Blazor#283]
I use Font Awesome on my websites (leaving out the Bootstrap icons) and therefore need to set custom page icons for every HxGrid I use. I would like to see HxGrid.Defaults contain settings for these (like it does for the sort icons). May I recommend: FirstPageIcon, LastPageIcon, NextPageIcon, PreviousPageIcon?

**Comment by hakenr** [comment]
These has to be `GridSettings.PagerSettings` as they have to be passed to underlying `HxPager`.
We need to add customizability to the `HxPager` it is currently hardcoded:
* `FirstPageIcon` parameter
* `LastPageIcon` parameter
*  `NextPageIcon` parameter
*  `PreviousPageIcon` parameter
* `PagerSettings` class
* `HxPager.Settings` parameter
  * add also `CssClass`
  * add also `NumericButtonsCount` (rename original `DisplayNumberCount` parameter ⚠️)
* `HxPager.Defaults` static property

**Comment by jirikanda** [comment]
I also marked TotalPages and CurrentPageIndex using [EditorRequired].
I doubt about HxGrid.PagerCssClass, should or should not it be removed? (Currently it is replaced by HxGrid.PagerSettings.CssClass.)

**Comment by jirikanda** [comment]
PR #310.

**Comment by hakenr** [comment]
Thank you @blimkemann for your sponsorship!
