### ISSUE TITLE
Question: how to set HxGridColumn width manually?

### ISSUE THREAD

**Issue by rqx110** [havit/Havit.Blazor#285]
how to set HxGridColumn width manually?
I haven't find any property can do this.

**Comment by Harvey1214** [comment]
Hello @rqx110,

you can set the width of a column manually by applying a CSS class to it using the `ItemCssClass` parameter on the `HxGridColumn`, which applies the chosen CSS classes to every cell in the column.

![image](https://user-images.githubusercontent.com/62853076/183593768-0c5308db-19d8-47de-89c1-9194d5a8f9c2.png)

For example, this result where one column takes half of the available space was achieved simply by passing the Bootstrap utility class `w-50` to the `ItemCssClass` parameter as shown below.

![image](https://user-images.githubusercontent.com/62853076/183594281-eae2134f-d887-4fab-8984-f8dfef7c02b7.png)

Thanks for using our component library, if you have any other questions, feel free to ask.
