### ISSUE TITLE
OnToastHidden

### ISSUE THREAD

**Issue by pallu** [havit/Havit.Blazor#288]
Would it be possible to call the OnToastHidden of HxToast from MessengerMessage or AddMessage?

**Comment by hakenr** [comment]
@pallu Not sure what you are trying to achieve. Can you please give me more context?

**Comment by pallu** [comment]
When a toast closes - either by clicking the x or on auto-hide, the OnToastHidden gets fired on HxToast. However, it's internal to the library. If you can expose it to the HxMessenger, then for an AddMessage, a callback can be passed to be fired when the toast is hidden.

**Comment by Harvey1214** [comment]
Hello @pallu,

thank you for the context, now we understand what functionality you are requesting. We will consider implementing this feature.

Thank you for using our component library and have a nice day 😀

**Comment by pallu** [comment]
Thank you!

**Comment by pallu** [comment]
My specific application is that I keep a track of toast messages for history. However, if a toast is closed manually, I remove it from the list - I know that the callback really does not track if a toast is closed manually or auto-closes. Anyway, for now I use the MutationObserver in JS for added and removed toasts and I have been able to successfully use that for my application

**Comment by hakenr** [comment]
@pallu I see. For such an application I would recommend to use `HxToast` instances directly (in `foreach` or `HxRepeater`) and bind them to a list of messages you will maintain in your state and manipulate as needed.

We were discussing the possibility to add `OnMessageClosed` to `HxMessenger`, but it opens much more questions than it resolves. For now, we decided not to add such feature to the library, unless there will be more scenarios/users demanding it.

If you get stuck in implementing your scenario with `HxToast`, place you question to the _Discussions_ here and we will try to help you.

Thanks for using our library and providing feedback...
