### ISSUE TITLE
[HxScrollspy] when user doesn't scroll between link clicks, sometimes scroll to the anchor doesn't happen

### ISSUE THREAD

**Issue by Harvey1214** [havit/Havit.Blazor#296]
1. go to [this demo](https://havit.blazor.eu/components/HxScrollspy#StaticContentListGroupNavigation)
2. click "Par 3" - the view is scrolled to the anchor
3. click "Par 4" - the view is not scrolled to the anchor

If you scroll even a little bit between steps 2 and 3, the issue doesn't occur.

cc @hakenr

**Comment by crdo** [comment]
@Harvey1214 It could be very easily bug in Bootstrap. The Scrollspy has been refactored in 5.2. Please try to reproduce in 5.2 branch so we make sure it is on our side.

**Comment by Harvey1214** [comment]
@crdo yes, it's happening even with Bootstrap upgraded.

**Comment by Harvey1214** [comment]
I created a standalone page with the demo that wasn't working and it worked flawlessly. I think the multiple demos - multiple `HxAnchorFragmentNavigation` components on the same page were causing the issue.

cc @crdo
