### ISSUE TITLE
Password complexity component

### ISSUE THREAD

**Issue by MichaelMelena** [havit/Havit.Blazor#300]
Component that clearly show to the user password complexity and what changes are required to pass the complexity check.

Validations:
* don't use common passwords (1234 etc.)
* don't use repeating patterns (password111 etc.)
* Uppercase letters required
* Special characters required

Parameters:
* Common password
* Allowed character
* Uppercase required 
* Number of uppercase letters required
* Special characters
* Special characters required
* Number of special characters required

Nice to have:
* localizable messages

**Comment by crdo** [comment]
We have a password complexity checker example implementation in Blocks, as part of the Premium content https://blocks.havit.blazor.eu/forms/input-password
@hakenr shall we keep this open?
