### ISSUE TITLE
[HxTooltip] Text not updating

### ISSUE THREAD

**Issue by Harvey1214** [havit/Havit.Blazor#301]
### Repro steps
When a tooltip's `Text` parameter is adjusted dynamically (changed from the initial `Text` value), a tooltip with the old text stays rendered and cannot be closed. When the tooltip is activated (`onhover` for instance), then a tooltip with the new text is rendered above the old one.

cc @hakenr, @crdo

### Update
This issue occurs only in a structure where the element with the event leading to changing the tooltip text resides in the tooltip's `ChildContent` - might correlate with the tooltip being shown while the text is changing.

![image](https://user-images.githubusercontent.com/62853076/185151551-edc1ef48-6384-4d66-b702-03686e2e0ba0.png)

**Comment by hakenr** [comment]
Duplicates #439
