### ISSUE TITLE
[HxGrid] InfiniteScroll + synchronous DataProvider returning empty data => DOMException: Failed to execute 'setStartAfter' on 'Range': the given Node has no parent.

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#303]
If there is HxGrid with ContentNavigationMode="GridContentNavigationMode.InfiniteScroll" (Virtualize) and the DataProvider delagate returns empty data synchronously, the underlying Virtualize emits JavaScript error to the console:
![image](https://user-images.githubusercontent.com/12828888/184900047-668bbf3e-f6f0-4c8d-9732-ead26ea4d435.png)
```
blazor.webassembly.j…1pV1-b5sQ3Rj11QGI:1 
 Uncaught DOMException: Failed to execute 'setStartAfter' on 'Range': the given Node has no parent.
    at https://localhost:44376/_framework/blazor.webassembly.js?v=wC-zAyYHVTNzevCw3SFvHI4jG51pV1-b5sQ3Rj11QGI:1:28726
    at Array.forEach (<anonymous>)
    at IntersectionObserver.<anonymous> (https://localhost:44376/_framework/blazor.webassembly.js?v=wC-zAyYHVTNzevCw3SFvHI4jG51pV1-b5sQ3Rj11QGI:1:28677)
(anonymous)	@	blazor.webassembly.j…1pV1-b5sQ3Rj11QGI:1
(anonymous)	@	blazor.webassembly.j…1pV1-b5sQ3Rj11QGI:1
```

In InfiniteScroll mode, we set `shouldRenderData` to true when `totalCount == null` to render the `Virtualize` which initiates the `DataProvider` request. As the DataProvider returns empty data, we re-render with `shouldRenderData = false` and remove the `Virtualize` from DOM. It seems it disappears from the DOM too quickly and the supporting JavaScript (MSFT) logs the error to console (not causing the Blazor app to fail!).

Related [AB#63587](https://dev.azure.com/havit/fd51f9bd-46eb-4a1b-98c8-b26cba5651c4/_workitems/edit/63587).

Workaround (for the scenarios where the Data is available in advance):
```razor
<HxGrid ContentNavigationMode="Data.Any() ? GridContentNavigationMode.InfiniteScroll : GridContentNavigationMode.Pagination" .../>
```

cc @alexax578 @jirikanda

**Comment by jirikanda** [comment]
@hakenr Don't ask me why it helps ;-).

**Comment by jirikanda** [comment]
I tried alternative approach and it also works. So no need to use Task.Yield.
BUT there is some issue with CSS, in this case, then I hover the empty template, it showes gray background (while in other scenarios it does not).

**Comment by hakenr** [comment]
@crdo Can you please check the mentioned visual issue in PR? Maybe @Harvey1214?

**Comment by crdo** [comment]
@hakenr @jirikanda It is set as hover-able table. So I guess it is expected behaviour...

**Comment by jirikanda** [comment]
Agree, I missed thad.
Thx.
