### ISSUE TITLE
[HxCheckbox] [HxSwitch] Inline mode does not work in EditForm

### ISSUE THREAD

**Issue by jirikanda** [havit/Havit.Blazor#312]
The [demo](https://havit.blazor.eu/components/HxInputCheckbox#Inline) works well.
But when I place the inputs to the EditForm, the inline mode does not work (each checkbox is on a separate line).

@crdo, how should the html look to make it working?

**Comment by jirikanda** [comment]
But we are going to replace the component, see #191.

**Comment by jirikanda** [comment]
Also happed for the new HxCheckbox, we need deep-dive. @crdo could you help please.

On the first look it looks like there is difference in display (block vs. inline-block) and width attributes on the wrapping div.

**Comment by crdo** [comment]
@jirikanda it has to be wrapped in extra div.

**Comment by hakenr** [comment]
Discussed the details with @crdo, my rewording:

As our CSS defaults bring flex-column to `<form>` element (`EditForm` component), every single direct child component of `<form>` is stacked in vertical column. (We can discuss this separately, we decided to go for this setup for better developer experience and ease of building the forms.)

This setup implies, whenever you want to go for horizontal stacking, you have to wrap your items in some element (usually `<div>`), and this is exactly what happens with inline checkboxes and what is needed to arrange them horizontally.

Closing this issue as _as designed_ for now. (+ Will add some explanation and/or guidance to documentation.)

**Comment by hakenr** [comment]
> Is there a demo to show how to use the HxCheckbox inside and outside of the EditForm?

https://havit.blazor.eu/components/Inputs#form-layout - demo
https://havit.blazor.eu/components/HxCheckbox#Inline - alert
