### ISSUE TITLE
[BlazorAppTest] run BlazorAppTest error

### ISSUE THREAD

**Issue by rqx110** [havit/Havit.Blazor#318]
File was loaded in a wrong encoding 'utf-8':

https://github.com/havit/Havit.Blazor/blob/8ad58fc913ce1e7cf5124fa81f749085a5810df1/BlazorAppTest/Pages/HxInputTagsTest.razor#L52

**Comment by hakenr** [comment]
Removed the testing characters from the file and resaved it in correct encoding.
Hope this resolves you issue. (I'm not aware of anyone else who is suffering with the scenario you mentioned (error when trying to run the BlazorAppTest)).

**Comment by rqx110** [comment]
> Removed the testing characters from the file and resaved it in correct encoding. 

Yes, this resolves my issue.
I saw your commit, so I closed this issue.
Thanks.
