### ISSUE TITLE
[HxInputRange?] - <input type="range">

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#32]
Do we want https://getbootstrap.com/docs/5.1/forms/range/?

**Comment by hakenr** [comment]
Doubts regarding naming
* colision with `HxInputDateRange` where it is "from" and "to"
* should this be `HxInputSlider`?
* do we prefer to stick with underlying HTML input naming?

**Comment by crdo** [comment]
@hakenr @Harvey1214 I don't think the name HxInputSlider is a good idea and IMHO we should respect the original HTML naming. 
It does not mean that you are selecting a range but from range and that make sense to me.
So let's go ahead with HxInputRange.
