### ISSUE TITLE
HxModal, HxCanvax Shuts down Main Page Scrolling after use

### ISSUE THREAD

**Issue by stayboy** [havit/Havit.Blazor#320]
![image](https://user-images.githubusercontent.com/10756019/186588557-c386444f-e428-4dcb-9fd4-3f73f4575591.png)
![image](https://user-images.githubusercontent.com/10756019/186588926-ac2d5ea0-c668-4c34-aec0-3b0ac2e65432.png)

After dismissing HxModal, Page Scrolling is disabled unless refreshed. Kindly find the Console bug if it helps

**Comment by hakenr** [comment]
Duplicates #148.

**Comment by stayboy** [comment]
> Duplicates #148.
Do I have to wait for bug fix from bootstrap?

Reproducing Bug:
1. Go to Sample Site https://havit.blazor.eu/components/HxOffcanvas
2. Under Backdrop Example, Click Open with Disabled Backdrop
3. With Canvax still opened, Click the Source Tab Under Backdrop Example
4. Close the HxOffCanvas dialog
5. Scroll the main page not working

![image](https://user-images.githubusercontent.com/10756019/186610918-289b9ef6-9490-4d0a-b199-462b7e91a84d.png)

**Comment by hakenr** [comment]
Unfortunately yes, this is something what has to be resolved in Bootstrap.
We are currently applying update to BS 5.2 (release expected next week) and hope some of these will be resolved.

(Also duplicates #110.)
