### ISSUE TITLE
[HxInputNumber] Question: Why is HxInputNumber not actually a number field?

### ISSUE THREAD

**Issue by Eonasdan** [havit/Havit.Blazor#324]
As the title states, I was expecting that `HxInputNumber` would have `type=number` instead of `text`. Is there a reason behind this?

**Comment by hakenr** [comment]
As far as I remember, the `type=number` does not respect page language on some devices and does not allow to enter decimal point in some locales (i.e. comma for decimal point, etc.)

Maybe @jirikanda can clarify more.

**Comment by hakenr** [comment]
Confirmed by @jirikanda, the `type="number"` does not reflect application local and prefers browser/OS locale for displaying and editing numbers. We want our apps to provide consistent formatting for displaying and editing numbers, therefor we decided to go for `type="text"` and custom implementation on top of that (most component libraries go this way as far as I know).

Fun fact: Our first implementation of `HxInputNumber` was `type="number"`, but we decided to change this.

**Comment by hakenr** [comment]
(We might make this configurable if someone will justify the reason. ;-))

**Comment by Eonasdan** [comment]
Interesting. It just feels bad to allow none-numeric characters and then validate it from a UX point of view. Silly browsers eh? :)

Thanks

**Comment by hakenr** [comment]
We are considering adding a new parameter that will allow you to force-set the input type to `number`.
cc @franc-havit

**Comment by hakenr** [comment]
In the end, we decided to add opt-in support for `<HxInputNumber Type="InputType.Number" />`, while `InputType.Text` remains the default.

Release `4.6.18-pre1`.
