### ISSUE TITLE
[HxInputDate], [HxInputDateRange] clear button not working after invalid entry to empty input

### ISSUE THREAD

**Issue by Harvey1214** [havit/Havit.Blazor#325]
When an invalid date is manually entered into an empty `HxInputDate(Range)` and the input has been marked invalid or no date has been entered before, the clear button doesn't work - the text stays intact when it's clicked.

cc @hakenr @crdo

**Comment by hakenr** [comment]
(I think we decide to take this as known issue not worth to fix, but please confirm.)

**Comment by hakenr** [comment]
Same applies (for the same reason, I think) when you start with specific date, then change it to invalid input and then click the original date in dropdown calendar.

**Comment by jirikanda** [comment]
#382

**Comment by jirikanda** [comment]
Is it connected to the issue 40097 in the aspnetcore? I guess so...
(InputText and other input components do not use SetUpdatesAttributeName() for two-way binding)

**Comment by jirikanda** [comment]
As an experiement, I tried to add Value/ValueChanged and mainly call the SetUpdatesAttributeName method to the HxDropdownToggleElement which renders the input for HxInputDate, HxInputDateRange. With the current implementation it works even worse (the invalid value is immediately overwritten with the previous value).

**Comment by Harvey1214** [comment]
Has been fixed. Most likely in [this commit](https://github.com/havit/Havit.Blazor/commit/934bee20ba2bf83ce2a00841aeaf40b214fd3e80) but `HxInputDateRange` still incurs this issue.
