### ISSUE TITLE
Doc - Navbar toggle button not visible in mobile view

### ISSUE THREAD

**Issue by Harvey1214** [havit/Havit.Blazor#333]
Although not visible, it is interactive.

![image](https://user-images.githubusercontent.com/62853076/187636802-743ce411-3f4a-4805-9783-fc3ffc9bef8c.png)

should be

![image](https://user-images.githubusercontent.com/62853076/187636946-8991c17d-8a6c-40e2-8ff8-3bfae740f288.png)

cc @hakenr @crdo

**Comment by hakenr** [comment]
There were some dances around CSS variables, maybe check there. (Found 1 mistake yesterday.)
