### ISSUE TITLE
[HxAutosuggest] [HxSearchBox] [HxInputTags] Keyboard navigation (up/down) stopped working

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#348]
1. Type something.
2. Use `ArrowDown` to navigate to specific item.
...not working

cc @crdo @Harvey1214

**Comment by hakenr** [comment]
Same with `HxSearchBox`.

(When I reverted back from li/a to buttons, I think it was working. It has to be some change in between that and Bootstrap 5.2)

**Comment by Harvey1214** [comment]
@hakenr, I agree with @crdo, this issue arose with the Bootstrap upgrade. Also, there haven't been any changes to the `HxSearchBox` since the structure change.

**Comment by hakenr** [comment]
This is our current issue:
https://github.com/twbs/bootstrap/blob/337068f8b1044004f4b9abfffbb433694ae87993/js/src/dropdown.js#L391-L405

**Comment by crdo** [comment]
So it has been already [discussed and closed](https://github.com/twbs/bootstrap/issues/36598) as won't fix.
