### ISSUE TITLE
[HxInputDate] - crashes when disposing and hxDropdownToggleElement is not available (edge case)

### ISSUE THREAD

**Issue by pavmal12** [havit/Havit.Blazor#353]
When I open offcanvas which has datepickers, it returned unhandled error. 

<img width="1552" alt="Screenshot 2022-09-05 at 10 18 42" src="https://user-images.githubusercontent.com/110027149/188403426-480524a1-bf4f-411f-b377-9a591bb93eb5.png">

![image](https://user-images.githubusercontent.com/110027149/188403506-d81b2cf0-3969-4466-a7a2-9ff537954ddd.png)

**Comment by hakenr** [comment]
fixed in v3.0.0-pre3, applied to BTF-AUT project
