### ISSUE TITLE
[HxInputDate] [HxInputDateRange] Show calendar icon as default

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#358]
We are removing the "three dots input-group" (#355).
I suggest to make the `HxInputDate` and `HxInputDateRange` display the calendar icon as default.

This would probably need some API redesign as there is currently only `CalendarIcon` parameter and leaving it `null` means "no icon".
If we set a default icon, we should probably add a new `ShowCalendarIcon`  parameter (`bool`, default `true`).

cc @crdo, @jirikanda

**Comment by crdo** [comment]
@hakenr I believe that this is obsolete as you can achieve this by using app-wide defaults.

**Comment by crdo** [comment]
@hakenr shall we close this?
