### ISSUE TITLE
[HxGrid] A way to persist grid state (sorting, current page) ?

### ISSUE THREAD

**Issue by Apskaita5** [havit/Havit.Blazor#360]
Is there a way to persist (e.g. in a cookie) the current state of the grid?
It would be nice if the grid is initialized/restored to its last state after a user navigates back. I understand that the grid state is not enough by itself, but it's current page and sorting are important elements for that purpose.

**Comment by hakenr** [comment]
You can use the `CurrentUserState` parameter and bind it to persisted field/property of your choice. E.g. serialize it to localStorage, cookie or just to any application-scoped storage (static field, singleton, ...).

**Comment by Apskaita5** [comment]
Got a warning Component parameter 'CurrentUserState' should not be set outside of its component.
Is it (CurrentUserState) json serializable?

**Comment by hakenr** [comment]
You have to use the `@bind-CurrentUserState="myField"` to bind to the parameter safely.
It should be serializable (let me know if you find the opposite).

**Comment by hakenr** [comment]
Thanks for opening this issue and testing the serializability.
We will prepare some guidance and/or adjustments to enable this use-case (preserving the grid state).

Just to be sure. Do you need to preserve the state over application restart (i.e. next user visit) or just within single application run (i.e. user travels across the app and returns to the screen with grid)? For the second, you can just save the state in app/circuit/scoped service.

cc @jirikanda

**Comment by Apskaita5** [comment]
I thought about standard user options persistence over application restart but the idea with a scoped service will do for starters.

**Comment by Apskaita5** [comment]
Not a priority for me as well ;)
It turned out that my users themselves are not sure if they want to save these specific GUI settings between sessions at all. They are quite happy about single session solution.

I think the feature could be implemented by extension methods without touching HxGrid code. The SortItemDto <-> Dto conversions could be done externally if Expression SortKeySelector could be semantically simplified to a property name (string). Does it always point to a property?

**Comment by Apskaita5** [comment]
Took a quick look at your code. I think if you implement HxGrid method

```
public IEnumerable<Expression<Func<TItem, IComparable>>> GetAvailableSortings()
=> columnsList.Where(c => null != c.SortKeySelector).Select(c => c.SortKeySelector);
```

the serialization could be simplified by trivial ToString. I.e. you persist SortKeySelector.ToString() and after deserialization just pick one of the existing ones.

**Comment by hakenr** [comment]
>the serialization could be simplified by trivial ToString. I.e. you persist SortKeySelector.ToString() and after deserialization just pick one of the existing ones

👍 Also one of the options to be able to rebuild the original state or pick the right expression for the sorting.

**Comment by hakenr** [comment]
...but still we have to take in account the scenarios where the `CurrentUserState` of the grid is not only saved and restored, but also can be manipulated (e.g. external controls for setting the sorting, etc.). It has to be intuitive for the developers, what the `GridUserState` holds and how to manipulate it (I admit, that the current implementation is not that friendly for such scenarios in combination with `Expression SortKeySelector`).

**Comment by jim-craane** [comment]
> ...but still we have to take in account the scenarios where the `CurrentUserState` of the grid is not only saved and restored, but also can be manipulated (e.g. external controls for setting the sorting, etc.). It has to be intuitive for the developers, what the `GridUserState` holds and how to manipulate it (I admit, that the current implementation is not that friendly for such scenarios in combination with `Expression SortKeySelector`, we use it with `SortString`).

Yes, I am looking for functionality to manipulate sorting from the c# code. Tried it with the bind suggestions on CurrentUserState in this post, but it didn't help. I will wait until this feature is implemented.

**Comment by hakenr** [comment]
@jim-craane The functionality was already published in one of earlier releases and is part of the documentation (just forgot to close this issue). See
https://havit.blazor.eu/components/HxGrid#persisting-state

On one of our projects, we do manipulate the CurrentUserState from outside. Fragments you might be interested in (this time we didn't use the column `Id`, but a enum-based `SortString` for every single column, which is then `switch`-ed on server side when preparing data for the grid):
```csharp
private void HandleSortingChanged()
{
	var sorting = clientCardListFilterSortModel.ToSortingItems();
	currentUserState = currentUserState with { Sorting = sorting };
}
```
```razor
<HxGridColumn ... SortString="@nameof(ClientCardSort.LegalType)" />
```
```csharp
public IReadOnlyList<SortingItem<ClientCardListItem>> ToSortingItems()
{
	var result = new List<SortingItem<ClientCardListItem>>();

	if (Sort.Value is not null)
	{
		result.Add(new SortingItem<ClientCardListItem>(
			Enum.GetName(Sort.Value.SortExpression),
			null, Sort.Value.SortDirection, null));
	}

	return result;
}
```
```csharp
public enum ClientCardSort
{
	[Description("Podle příjmení")] LastName,
	[Description("Podle města")] City,
	[Description("Podle typu subjektu")] LegalType,
	[Description("Podle rodného čísla")] BirthNumber,
	[Description("Podle hodnocení")] Rating,
	[Description("Podle platnosti klientské karty")] CardValidity,
	[Description("Podle poslední aktivity")] LastActivity,
	[Description("Podle datumu vytvoření")] BtCreated,
	[Description("Podle splnění GDPR")] HasConsent
}
```
