### ISSUE TITLE
FluentValidation Mismatch Version

### ISSUE THREAD

**Issue by yeganehaym** [havit/Havit.Blazor#362]
fluent validation in Havit components is lower than fluent validation in my project and gives me version mismatch error
what should I do?

**Comment by hakenr** [comment]
Hi,
we do not introduce dependency on FluentValidation package, we are not using it in our library et al (except testing application, which is not part of the release). You should not be restricted by our library in any way.

--- 
Our [NewProjectTemplate-Blazor](https://github.com/havit/NewProjectTemplate-Blazor) (optional, not sure you are referring to it?) uses Blazored.FluentValidation (currently v2.0.3), which currently restricts the FluentValidation dependency to v10.
There is a pre-release of the Blazored.FluentValidation NuGet package which allows you to use v11+ if you don't want to wait. We have submitted an issue (https://github.com/Blazored/FluentValidation/issues/153) where we ask to finish this version to production but without any progress as of today.

**Comment by yeganehaym** [comment]
![image](https://user-images.githubusercontent.com/5742917/188834550-bb03333f-e4c7-4a87-8f15-a4c158badf8c.png)

**Comment by hakenr** [comment]
I don't see anything which supports your statement that `Havit.Blazor` has a FluentValidation dependency which breaks your project.

I think you are trying to update all your dependencies. But the `Blazored.FluentValidation v2.0.3` (latest release) requires `FluentValidation v10` which you are trying to update to `v11`.

It seems you are referencing `Blazored.FluentValidation` from your project. You have to either update it to `2.1.x-pre` or stick with `FluentValidation v10`.
