### ISSUE TITLE
[HxAutosuggest] Missing scrolling in dropdown?

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#363]
Was there a limit for number of visible items?
The new implementation doesn't seem to have one:
![image](https://user-images.githubusercontent.com/12828888/188986206-b0965c4d-ecb4-44fb-b65a-866f3d8528f1.png)

**Comment by crdo** [comment]
Unlike `HxMultiSelect`, this component does not have `max-height` set and you are expected to limit the suggestions when returning data from server.

**Comment by hakenr** [comment]
Got it, adjusted the demo with 3f1f8ae1634ef3ff55eadbffd3c20eba93e942de.
