### ISSUE TITLE
[doc] Update installation instructions to work for new Blazor empty app templates in VS

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#372]
https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-6/#empty-blazor-project-templates

**Comment by jjindrich** [comment]
HxGrid doesn't work without builder.Services.AddLocalization();
Please add this comment into Getting started page

**Comment by hakenr** [comment]
`.AddLocalization()` is covered in `.AddHxServices()` which is required by installation instructions:
https://havit.blazor.eu/#register-services

Did you encounter the issue where you have `.AddHxServices()` included in your project and the `HxGrid` does not work?
