### ISSUE TITLE
[HxGrid] Check/Improve implementation based on QuickGrid reference architecture and performance baseline 

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#373]
https://aspnet.github.io/quickgridsamples/
https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-6/#experimental-quickgrid-component-for-blazor
https://www.nuget.org/packages/Microsoft.AspNetCore.Components.QuickGrid/0.1.0-alpha.22351.1
https://github.com/aspnet/AspLabs/tree/main/src/QuickGrid

**Comment by jirikanda** [comment]
I can try to rework the column registration by the provided example.
@hakenr , please merge the #385 first to smooth the following PR merges.

**Comment by jirikanda** [comment]
@hakenr, AFAIK it is completed, isn't it?

**Comment by hakenr** [comment]
@jirikanda There are still a few minor tweaks to apply, but this issue no longer holds any value, so I'm closing it.
