### ISSUE TITLE
Darkmode issues

### ISSUE THREAD

**Issue by W0lfgang** [havit/Havit.Blazor#375]
I love the new version! Finally I can use dark mode in my application without big css modifications, since the new Havit elements make extensive use of the bootstrap 5.2 css variables. Awesome!

Just two small things: 
The search result `<li>` elements of `<HxSearchBox>` and the text of the `<HxSidebarItem>`  don't use the variables for text color and element background.

I patched the navbar items with 
```
.hx-sidebar-brand-name,
.hx-sidebar-item-navlink-content-inner,
.stretched-link {
    color: var(--bs-body-color) !important;
}
```
But I don't know how to fix the search result list.

Everything else works fine :-)

**Comment by crdo** [comment]
There is our own set of CSS variables for components that are built on top of Bootstrap.
In case of `HxSidebar`, you are looking for `--hx-sidebar-item-color`, `--hx-sidebar-brand-name-color`.

`HxSearchbox` result list is built with Bootstrap dropdown and its text color can be set via `--bs-dropdown-link-color`.

Each component has a list of its CSS variables at the end of each documentation page.

**Comment by crdo** [comment]
... also I highly discourage you to override `stretched-link` CSS class as it is one of the Bootstrap utility classes, that can be used on other parts in your app not related to `HxSidebar`.

**Comment by W0lfgang** [comment]
Thank you for your reply! :-) I have changed my css snippet from above to

```
:root {
    --hx-sidebar-item-color: var(--bs-body-color) !important;
    --hx-sidebar-brand-name-color: var(--bs-body-color) !important;
}
```

But I am unable to find the variables (or documentation) for the font color of the selected item in the result list opened by `<HxSearchBox>`. Any idea?

**Comment by crdo** [comment]
If you mean this by "selected item"
![image](https://user-images.githubusercontent.com/1410922/190096483-7af23ff2-67e1-4ba6-8d1b-584721c367de.png)
then you are looking for `--bs-dropdown-link-active-color` and `--bs-dropdown-link-active-bg`.

At this point `HxSearchbox` does not have its own CSS vars for this and its all inherited from Bootstrap dropdown.

We might consider to change this in future minor release and use the Bootstrap values as defaults.
