### ISSUE TITLE
[HxInputDate(Range), HxSearch, HxAutosuggest] To visually unify the clear button

### ISSUE THREAD

**Issue by crdo** [havit/Havit.Blazor#383]
I suggest to visually unify the clear button.

HxSearch
<img width="273" alt="Screenshot 2022-09-16 at 9 09 18" src="https://user-images.githubusercontent.com/1410922/190578327-b4fa7473-ccb7-485c-b2ed-0eb40de96552.png">

HxAutosuggest
<img width="244" alt="Screenshot 2022-09-16 at 9 09 30" src="https://user-images.githubusercontent.com/1410922/190578361-92a34199-d039-4fa5-87b8-8287fba5e7fe.png">

HxInputDate(Range)
<img width="272" alt="Screenshot 2022-09-16 at 9 09 51" src="https://user-images.githubusercontent.com/1410922/190578413-5e5c7127-3326-422f-bb57-bf494a4ad1ca.png">

**Comment by hakenr** [comment]
My preference is the `HxSearch` look.
