### ISSUE TITLE
Data Table and search

### ISSUE THREAD

**Issue by Gena-developer** [havit/Havit.Blazor#397]
Hi, does it have a search of table together?

**Comment by hakenr** [comment]
There is currently no built-in filtering feature in `HxGrid` component, the intention is to let the developers implement it as needed (e.g. using `HxListLayout` in `HxOffcanvas` filter, or using `HeaderTemplate` for each grid column).

Sample implementation (with help of HxListLayout):
* https://github.com/mensagymnazium/IntranetGen3/blob/master/Web.Client/Pages/Electives/SubjectList.razor
* https://github.com/mensagymnazium/IntranetGen3/blob/master/Web.Client/Pages/Electives/SubjectList.razor.cs
