### ISSUE TITLE
[HxTooltip] - Tooltip is sometimes shown at wrong position on the page

### ISSUE THREAD

**Issue by pavmal12** [havit/Havit.Blazor#404]
In some scenarios when I move mouse over element with tooltip, then move over and again move back to element, the tooltip is shown at the bottom of the page. 

![image](https://user-images.githubusercontent.com/110027149/195544891-14cb1fa9-a8e4-4573-828f-03c68033b1d4.png)

**Comment by alexax578** [comment]
The mentioned behavior probably occurs when I quickly move move away from the element with tooltip and then back over before the tooltip has finished disappearing.

**Comment by hakenr** [comment]
I'm unable to reproduce.
Can you please tak a look, @crdo?

**Comment by crdo** [comment]
It is a Bootstrap issue. If you hover the tooltip while it is being hidden and the hide animation is still in progress, it breaks.
https://github.com/twbs/bootstrap/issues/36875

**Comment by hakenr** [comment]
The issue seems to be fixed in Bootstrap 5.2.3.
