### ISSUE TITLE
[HxGrid] - grid with multiselect can select checkbox when no data are on grid

### ISSUE THREAD

**Issue by pavmal12** [havit/Havit.Blazor#407]
When I do not have any data on grid, I'm still able to select checkbox. I would suggest to have option disable this checkbox. 

![image](https://user-images.githubusercontent.com/110027149/196177013-46dcf194-dcd1-4c17-8a7e-31f4fbd06acf.png)

**Comment by hakenr** [comment]
(Just verified the issue is still there.)

**Comment by hakenr** [comment]
The checkbox is now disabled whenever there are no items available (`TotalCount` is either `null` or `0`).
(Hiding the checkbox results in UI jumping during rendering.)
