### ISSUE TITLE
[HxTabPanel] Set order in which tabs will be displayed

### ISSUE THREAD

**Issue by alexax578** [havit/Havit.Blazor#409]
I want to set a specific order in which the tabs would show up in the tab panel. In my scenario one tabs rendering is delayed because it is wrapped in AuthorizeView component therefore it will render last in the tab panel.

```
<HxTabPanel>
    <HxTab Title="First tab" Order="1">
        <Content>This is the first tab.</Content>
    </HxTab>

    <HxTab Title="Second tab" Order="2">
        <TitleTemplate>Second tab</TitleTemplate>
        <Content>This is the second tab. This tab is initially active.</Content>
    </HxTab>

    <HxTab Title="Third tab" Order="3">
        <TitleTemplate>Disabled tab</TitleTemplate>
    </HxTab>
</HxTabPanel>
```

**Comment by hakenr** [comment]
This is already implemented for HxGridColumns and we should "just" replicate the same ordering logic here.
cc @jirikanda
