### ISSUE TITLE
Export HxGrid Data

### ISSUE THREAD

**Issue by spiderock98** [havit/Havit.Blazor#41]
I need to export data table to pdf and xlsx format , is there any script or extension to support that. Thank you so much for your supports

**Comment by hakenr** [comment]
Hi, there is currently no export built in our HxGrid component. The intended way is to use dedicated library (iTextSharp, Apose.Pdf, Aspose.Tables, ...) and use the same data to build an export using such library (usually, but not exclusively, on server side).
