### ISSUE TITLE
[HxGrid] Page sequentially decreased until data found after data filter applied (should we return to first page?)

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#412]
## THE ISSUE
Let's have grid with 40000 items.
Paging mode (50 items per page).
User clicks "go to last page" in pager.
Page 800 is displayed.

User applies filtering criteria where the new data set consists of 200 records.

Our current implementation recognizes there are no data on page 800 and rerenders to page 799.
As there are no data on page 799, the grid rerenders to page 798.
As there are no data on page 798, the grid rerenders to page 797.
...
As there are no data on page 5, the grid rerenders to page 4.

This creates almost 800 DataProvider requests and takes ages.

https://github.com/havit/Havit.Blazor/blob/0e3b01c2986e831883d54508c74d491feb03116e/Havit.Blazor.Components.Web.Bootstrap/Grids/HxGrid.razor#L51-L54

https://github.com/havit/Havit.Blazor/blob/0e3b01c2986e831883d54508c74d491feb03116e/Havit.Blazor.Components.Web.Bootstrap/Grids/HxGrid.razor.cs#L316-L322

## IDEAS
1. The DataProvider returns total number of items. We should not return to previous page, but calculate the index of last available page.
2. We should give the developers an easy way to navigate the beginning of the grid after new filtering criteria are applied (no matter whether it is in paging, inifinite-scroll or any other future mode). Maybe something like (new optional parameter)
```csharp
await gridComponent.RefreshDataAsync(resetUserState: true);
```
...which will be used when the _Apply_ button in filter is clicked?
Do we also want to reset sorting or just the position?

@jirikanda (cc @crdo)

**Comment by jirikanda** [comment]
@hakenr (cc @crdo)
The idea was to navigate one page back when the last item on the last page is deleted. I understand the naive implamentation leads to this hell and needs to be fixed. The fix calculates the last page now and do not navigate back page by page anymore.
Commited to master.

The further questions (should we return to first page?, We should give the developers an easy way to navigate the beginning of the grid after new filtering criteria are applied, Do we also want to reset sorting or just the position?) can be answer on the next TDM.

**Comment by hakenr** [comment]
Extracting the "reset state when filter applied" to separate issue and closing this one.
