### ISSUE TITLE
[doc] Remove `int` from types + invalid links

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#417]
https://havit.blazor.eu/components/HxGrid#HxGrid-parameters

`int?` parameters link to https://havit.blazor.eu/types/int (remove)
the https://havit.blazor.eu/types/int shows `SidebarResponsiveBreakpoint`

**Comment by vaclavek** [comment]
Also on page https://havit.blazor.eu/components/HxPager is link to https://havit.blazor.eu/types/PagerDefaults and shows nothing...

On page https://havit.blazor.eu/components/HxGrid there is are some invalid links:
- [EventCallback<HashSet<TItem>>](https://havit.blazor.eu/types/EventCallback%3cHashSet%3cTItem%3e%3e)
- [HxGrid.Defaults](https://havit.blazor.eu/types/GridDefaults) 
- [HxGrid.DataProvider](https://havit.blazor.eu/types/HxGrid#DataProvider)
- [SortDirection.Ascending](https://havit.blazor.eu/types/SortDirection)

And there is more on other pages :)
