### ISSUE TITLE
[HxDropdownContent] is missing Alignment property

### ISSUE THREAD

**Issue by crdo** [havit/Havit.Blazor#423]
`HxDropdownMenu` has the Alignment property while `HxDropdownContent` does not.
The only difference is what does each component render but the API should be alike.

**Comment by hakenr** [comment]
(Implementation note: If it makes sense to make those two aligned, we should enforce that by using a `IHxDropdownContent` interface, although there is not expected the interface will be consumed by anyone in production code. Already used for other similar component pairs.)
