### ISSUE TITLE
[HxTagInput] input area out of + button

### ISSUE THREAD

**Issue by Mpowerman** [havit/Havit.Blazor#424]
<img width="908" alt="image" src="https://user-images.githubusercontent.com/45297752/199696988-11c262a9-0967-4dff-8e6e-3422140a2d01.png">

ADOS reference:
[https://dev.azure.com/havit/DEV/_workitems/edit/65374](url)

**Comment by pavmal12** [comment]
@crdo only button with plus should be clickable

**Comment by hakenr** [comment]
For now, I consider it to be intentional. In the future, we can reassess if this is the desired behavior, should it bother anyone.
