### ISSUE TITLE
[HxGrid] Asynchronous reading data into grid via EF Core

### ISSUE THREAD

**Issue by HonzaZajic298** [havit/Havit.Blazor#442]
Hello,

our team is trying to use your Havit Blazor components in our new Web app.
We are trying (for educative reasons) to read data from EF Core layer into your HxGrid, but we have noticed that your extension method `public GridDataProviderResult<TItem> ApplyTo(IEnumerable<TItem> data)` is synchronous.

Is there any way how to get data into grid asynchronously?

**Comment by hakenr** [comment]
Hi,
there is a draft pull request with `ApplyTo`-like implementation for IQueryable including a demo.
I guess it is what you need. You can use the proposed `ApplySortingPagingTo()` method instead of the current `ApplyTo()` method and pickup the data in asynchronous way.

**Comment by hakenr** [comment]
Duplicates #66.
