### ISSUE TITLE
[HxInputDate] Dropdown not working after once disabling the component

### ISSUE THREAD

**Issue by Unwieldy** [havit/Havit.Blazor#446]
If you toggle the HxInputDate component off and on using the "Enable" parameter the datepicker does not show on click.
`<HxInputDate Label="Date" @bind-Value="@Value" Enabled="@Enable" />`

**Comment by hakenr** [comment]
Duplicates #458, fixed, waiting for release.

**Comment by crdo** [comment]
Fixed and released.
