### ISSUE TITLE
[HxMultiSelect] Using HxMultiSelect in HxGrid causes extra scrollbar to apear

### ISSUE THREAD

**Issue by TPIvan** [havit/Havit.Blazor#449]
**Observed behavior:**

![image](https://user-images.githubusercontent.com/39948593/211492911-aecafe52-7a4c-449e-b894-d3db6a984c88.png)

**Expected behavior**: the same as  `HxSelect`

![image](https://user-images.githubusercontent.com/39948593/211493219-2c589626-349e-4bd7-bea8-ad7fd4381a6f.png)

The _vertical_ scrollbar can be removed by unsetting _horizontal_ scroll on grid container (class `table-responsive`) 

    <style type="text/css">.table-responsive {overflow-x:initial;} </style>
It can be tested even in browser developer tools.
![image](https://user-images.githubusercontent.com/39948593/211498686-75e9e791-8258-44bb-a772-e57ade45126e.png)
![image](https://user-images.githubusercontent.com/39948593/211498908-5731983b-81d9-4d48-a898-2dcc0f450465.png)

**Full sample:**

      <div style="border:1px solid blue">
         <HxGrid TItem="string" Responsive="true" DataProvider="GetGridData" PageSize="10">
             <Columns>
                 <HxGridColumn HeaderText="HxMultiSelect">
                     <ItemTemplate>
                         <HxMultiSelect TItem="Person"
                                        TValue="string"
                                        Data="@people"
                                        @bind-Value="@selectedPersonsInitials"
                                        TextSelector="@(p => p.Name)"
                                        ValueSelector="@(p => p.Initials)" />
     
                     </ItemTemplate>
                 </HxGridColumn>
                 <HxGridColumn HeaderText="HxSelect">
                     <ItemTemplate>
                         <HxSelect TItem="Person"
                                   TValue="string"
                                   Data="@people"
                                   @bind-Value="selectedInitials"
                                   TextSelector="@(p => p.Name)"
                                   ValueSelector="@(p => p.Initials)"
                                   Nullable="true" />
                     </ItemTemplate>
                 </HxGridColumn>
             </Columns>
         </HxGrid>
     </div>
     @code {
         private string selectedInitials;
         private List<Person> people;
         private List<string> selectedPersonsInitials { get; set; } = new();     
         protected override async Task OnInitializedAsync()
         {
             await Task.Delay(1000); // simulates slow server API call
     
             people = new List<Person>
             {
                 new Person("Starr Ringo", "RS"),
                 new Person("Lennon John", "JL"),
                 new Person("McCartney Paul", "PMC"),
                 new Person("Harrison George", "GH")
             };
         }
     
         private record Person(string Name, string Initials);     
         private Task<GridDataProviderResult<string>> GetGridData(GridDataProviderRequest<string> request)
         {     
             return Task.FromResult(new GridDataProviderResult<string>
                 {
                     Data = new[] { "JL" },
                     TotalCount = 1
                 });
         }
     }
**Notes:**
The same behavior was observed also for `HxInputTags`.
Observation was done in MS Edge 108.0.1462.76. Other browsers were not tested.

**Comment by TPIvan** [comment]
Currently I confirm that this issue is connected with #450. My mistake was that I have omitted adding `!important` flag to the position rule. So with help of crdo: https://github.com/havit/Havit.Blazor/issues/450#issuecomment-1457792243 I have found the following workaround:

        .table-responsive .dropdown-menu 
        {
            position: fixed !important;
            width:auto !important;
        }
The resetting the width is necessary because  `HxMultiSelect` have `width:100%`. So I think, that some tuning will be necessary, when the problem is corrected in Bootstrap.

In future I have to confirm whether the selector is specific enough.

**Comment by hakenr** [comment]
Issue tracked in #450.

**Comment by TPIvan** [comment]
The resolution of issue #450 highlighted the need to add the `data-bs-popper-config` attribute to the toggle element. However, upon reviewing the [HxMultiSelectInternal component](https://github.com/havit/Havit.Blazor/blob/6db8a5ded4d3639ebc846266c5985e8031fbeb53/Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxMultiSelectInternal.razor#L20), it appears that there is currently no built-in mechanism to support this attribute directly. While issue #450 has been addressed, the limitation within HxMultiSelect remains unresolved. It may be necessary to consider extending the component's functionality or exploring alternative solutions to incorporate the `data-bs-popper-config` attribute effectively.

**Comment by hakenr** [comment]
Oh, I see.
Attribute splatting correctly places the `data-bs-popper-config` on the underlying `input` in `HxMultiSelectInternal`, while the `data-bs-toggle` is associated with the wrapping `div`.

https://github.com/havit/Havit.Blazor/blob/6db8a5ded4d3639ebc846266c5985e8031fbeb53/Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxMultiSelectInternal.razor#L19-L33

@crdo, is there a possibility to consolidate the `div>input` structure into just an `input` with the `data-bs-toggle`? It seems that `HxInputDateInternal` is implemented in this manner:

https://github.com/havit/Havit.Blazor/blob/6db8a5ded4d3639ebc846266c5985e8031fbeb53/Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxInputDateInternal.razor#L22-L47

**Comment by crdo** [comment]
@hakenr I have removed the extra div and tested the component in docs and BlazorAppTest successfully.
