### ISSUE TITLE
[HxInputBase] Text inputs should specify Value update frequency

### ISSUE THREAD

**Issue by robertmclaws** [havit/Havit.Blazor#45]
Text input controls in Blazor are able to specify if they update bindings on input change or on blur. That ability should be surfaced up through your controls so that the developer can specify when they went their ViewModels updated.

Thanks!

**Comment by hakenr** [comment]
Hi @robertmclaws,
the `HxInputText` component currently has `BindEvent="BindEvent.OnChange|OnInput` parameter. Can you please explain what scenarios you need to cover so we can think of the best design...?

cc @jirikanda

**Comment by hakenr** [comment]
Hi @robertmclaws,
the `HxInputText` component currently has `BindEvent="BindEvent.OnChange|OnInput` parameter. Can you please explain what scenarios you need to cover so we can think of the best design...?

cc @jirikanda

**Comment by robertmclaws** [comment]
OH! Sorry I missed that, it's not in the API docs. 

If that is the case, then I'm seeing a couple issues with the Inputs docs (and probably the docs in general):
1) The API surface area is not alphabetized.
2) Inherited objects (like `HxInputNumber`) do not always show base class members (or if they do, like `InputGroupStart` & `InputGroupEnd`) they don't let you know specifically that they are inherited and what class they come from).

It looks like ComponentApiDoc.razor needs a couple simple updates to pull up the inheritance chain and then sort the output by member name.

**Comment by hakenr** [comment]
Oops, you are right, we didn't even notice that the inherited members are missing. Will fix.

The order of members in API documentation currently corresponds to the order of members in the class, which we hope prioritizes the most relevant members and puts some members together according to the feature affected. I'm not sure if the alphabetical order will be better (any arguments? switchable?), but we might review the order of members in classes to polish the results of this approach.

Thanks for your suggestions!

**Comment by hakenr** [comment]
@robertmclaws In the end I decided to go with the alphabetical order of members. We will see if that proves to be right...
