### ISSUE TITLE
[HxDropdown] - Content overflowing container is not visible

### ISSUE THREAD

**Issue by TPIvan** [havit/Havit.Blazor#450]
When `HxDropdown` is in a container with `overflow` auto (hidden) then the the part exceeding the container is scrollable (hidden).
![image](https://user-images.githubusercontent.com/39948593/211505150-b7e1f4b1-6b01-465b-a652-400b694627be.png)

I would expect an option to control whether the DropDown pops out of container or is included in it.

It seems that there used to be an option in Bootstrap but it seems that it no longer works.
[SO: Bootstrap 5.1.3 Dropdown data-bs-boundary No Longer Works](https://stackoverflow.com/questions/70098157/bootstrap-5-1-3-dropdown-data-bs-boundary-no-longer-works).

**Code sample**
    
    <div style="overflow-y: auto; height: 175px;">      
      <HxDropdown>                                        
        <HxDropdownToggleElement ElementName="div" CssClass="bg-success p-3 text-white" role="button">        Custom dropdown toggle element     
        </HxDropdownToggleElement>                          
        <HxDropdownMenu>		
          <HxDropdownItemNavLink>Link with Href</HxDropdownItemNavLink>		
          <HxDropdownDivider />        
          <HxDropdownItemText>Some text only 1</HxDropdownItemText>        
          <HxDropdownItemText>Some text only 2</HxDropdownItemText>        
          <HxDropdownItemText>Some text only 3</HxDropdownItemText>        
          <HxDropdownItemText>Some text only 4</HxDropdownItemText>        
          <HxDropdownItemText>Some text only 5</HxDropdownItemText>        
          <HxDropdownItemText>Some text only 6</HxDropdownItemText>        
          <HxDropdownItemText>Some text only 7</HxDropdownItemText>	
        </HxDropdownMenu>
      </HxDropdown>
    </div> 

By the mentioned article the problem can be solved by setting `position: static` on `HxDropdown` component. It can be tested in browser develper tools (has to be set before clicking to drop).
![image](https://user-images.githubusercontent.com/39948593/211506881-7d6a6b47-c0e7-47d3-b2d0-3b7f4d359713.png)
![image](https://user-images.githubusercontent.com/39948593/211507173-cfd0bead-6af7-47ec-844c-c6082b60a031.png)

**Notes:**
The problem was discovered when analyzing #449 but it seems that it is different problem, because setting the position doesn't help in `HxGrid`.
Observation was done in MS Edge 108.0.1462.76. Other browsers were not tested.

**Comment by crdo** [comment]
Hi @TPIvan thanks for reporting this. 
We know about this issue and I believe it is related to the Popper config that is taken over from Bootstrap.
I was not able to find what needs to be changed in order to work-around this so far.
We also came across this on our applications and we have to find some solution soon.

**Comment by crdo** [comment]
@TPIvan try to add `position-fixed` to the dropdown-menu as pre https://github.com/twbs/bootstrap/issues/35774. As this is reported as Bootstrap issue we have to rely on fixing on their side.
Please not that I am not sure about side-effects that this work-around may cause.

**Comment by GreathostRo** [comment]
After more than a few hours and various attempts I found the working version:

```
const dropdowns = document.querySelectorAll('.dropdown-toggle')
const dropdown = [...dropdowns].map((dropdownToggleEl) => new bootstrap.Dropdown(dropdownToggleEl, {
    popperConfig(defaultBsPopperConfig) {
        return { ...defaultBsPopperConfig, strategy: 'fixed' };
    }
}));
```

**Comment by crdo** [comment]
Thanks for a tip @GreathostRo, we will give it a try.

**Comment by TPIvan** [comment]
@crdo thanks for comment (https://github.com/havit/Havit.Blazor/issues/450#issuecomment-1457792243). I helped me to find a workaround for #449.

**Comment by crdo** [comment]
@TPIvan an ultimate solution for this is to use what @GreathostRo suggested in his comment but via data attribute.

`data-bs-popper-config='{"strategy":"fixed"}'`

It needs to be placed on the toggle element - usually `HxDropdownToggleElement`, `HxDropdownToggleButton` or in case of `HxInputDate` on the input itself.
