### ISSUE TITLE
[HxAutosuggest] Free text input

### ISSUE THREAD

**Issue by jakakordez** [havit/Havit.Blazor#454]
I would like an input text field that would allow me to enter any text but offer suggestion like HxAutosuggest does. With the current implementation, the field can only contain values returned by the data provider, any other value gets deleted. The data provider in my case suggests regular strings, no complicated objects.
Can this functionality be added? Can I achieve this with some other component?

**Comment by crdo** [comment]
Hi @jakakordez, have a look at [HxSearchbox](https://havit.blazor.eu/components/HxSearchBox#HxSearchBox).

**Comment by jakakordez** [comment]
I checked the HxSearchBox component but that one doesn't allow me to bind or pre-populate the box with already existing value. I would like to use it in an edit form.

**Comment by jakakordez** [comment]
Nevermind, I see I can achieve desired functionality with the TextQuery property. Thanks for your help.

**Comment by hakenr** [comment]
You should be able to pre-populate the dropdown by using the very same approach as `HxAutosuggest` and `HxInputTags` do. Set minimum length to 0 and delay to 0 + return the desired items from the DataProvider.

Let me know if you find any troubles using this approach.
