### ISSUE TITLE
[HxPager] PagerSettings.CssClass is not working when set.

### ISSUE THREAD

**Issue by jim-craane** [havit/Havit.Blazor#459]
When I was migrating from v2 to v3, I had to migrate the HxPager as well according to the documentation: https://havit.blazor.eu/migrating-to-v3#HxGrid-pager

First of all, the code example provided in the documentation is invalid razor. It should be:
`
<HxGrid PagerSettings="@(new() { CssClass = "your-class" })" .../>
`

But when settings the CssClass, nothing happend. I dived in to the code and found this:

In HxPager.razor.cs there is this code:
![image](https://user-images.githubusercontent.com/64642269/215733690-40bcea00-1c9e-4640-8c98-985b2ab7a4f6.png)

But in HxPager.razor the effective is not used:
![image](https://user-images.githubusercontent.com/64642269/215733531-960be7fc-0cb4-4446-ae37-85a3f96776b6.png)

For the other PagerSettings properties, the effective is used:
![image](https://user-images.githubusercontent.com/64642269/215733783-0b1eb2b4-1fc7-46f8-831c-f2c0292e21bc.png)

Can this be solved?

**Comment by crdo** [comment]
Will be part of next minor release probably this or next week.

**Comment by jim-craane** [comment]
> Will be part of next minor release probably this or next week.

2 weeks are passed. When is the new release coming?

**Comment by crdo** [comment]
Hi, it will be released tonight.

**Comment by hakenr** [comment]
released in v3.2.7
