### ISSUE TITLE
[HxPager] Overflowing on mobile devices

### ISSUE THREAD

**Issue by crdo** [havit/Havit.Blazor#46]
<img width="529" alt="image" src="https://user-images.githubusercontent.com/1410922/143444662-d5c2ec4c-ae01-4591-a5c7-86f1b8c52de0.png">
As the TableContainerCssClass only wraps the table itself, there is potential issue with HxPager overflowing on mobile devices if the number of pages is high even though the table-responsive class is used.

**Comment by hakenr** [comment]
Decision: to display arrows + three page-numbers + arrows on XS devices.

**Comment by crdo** [comment]
@jirikanda please apply following changes:
Page 1-3 no change
Page 4-5 add classes "d-none d-md-block"
Page 6-10 add classes "d-none d-lg-block"

**Comment by hakenr** [comment]
Future plans: The breakpoint should be configurable as we do not know the layout of the page.
We might support several breakpoints where the number of displayed pages will be decreasing.
