### ISSUE TITLE
[Navbar] Remove depreciated navbar-light variant and adjust by the new color scheme settings

### ISSUE THREAD

**Issue by crdo** [havit/Havit.Blazor#461]
The `Navbar` light variant has been depreciated as of 5.2.0.
Navbar color variants are set by the applying bg utility classes.
Dark variant is set by adding `data-bs-theme="dark"` attribute.

https://getbootstrap.com/docs/5.3/components/navbar/#how-it-works

I guess we are about to abbandon the `ColorScheme` settings.

**Comment by hakenr** [comment]
@crdo Do we want this to be in v4.0.0 or earlier minor release? (I just created a separate milestote `v4.0.0`, so use it if appropriate.)

**Comment by hakenr** [comment]
* Removed the `ColorScheme` parameter
* Added the `Theme` parameter with `BootstrapTheme` enum (`Light` and `Dark` currently supported)
* Adjusted the documentation
* We do not have strong-type support for `.bg-*-subtle` and `.bg-body-*` classes
