### ISSUE TITLE
[HxPager] role="button" on whole pager

### ISSUE THREAD

**Issue by crdo** [havit/Havit.Blazor#464]
The wrapping `ul` of `HxPager` has `role="button"` attribute.

`<ul role="button" class="@CssClassHelper.Combine("hx-pager pagination", this.CssClassEffective)">`

It is wrong from accessibility POV, as it is not one but many buttons and some of them could be disabled.
The attribute should be present on each not disabled button separately.

**Comment by hakenr** [comment]
Is there any reason for v4.0.0 milestone? It is just a regular bug which might be fixed anytime?

**Comment by hakenr** [comment]
@crdo, please see the associated commit if `a` element is the right target for `role="button"` (or should it be the parent `li`?)?
reopen if needed

**Comment by crdo** [comment]
I did some related CSS cleanup in v4 milestone, but it is not necessary to release it together. Placement on `a` is OK

**Comment by crdo** [comment]
Also, my previous assumption that it should not be on disabled items was wrong. It is OK.

**Comment by hakenr** [comment]
Not sure what you are talking about? There are no disabled items, just items without `a` element which are not actionable?
