### ISSUE TITLE
[HxGrid] Filtering from header

### ISSUE THREAD

**Issue by Arnnes** [havit/Havit.Blazor#470]
Is it possible to add support for individual column searching on HxGrid? Just to add some possibility to display an input under the column name with callback to handle the searching itself.
![image](https://user-images.githubusercontent.com/121752292/219372262-7edd5607-8498-43f9-941e-fa14ca1a5639.png)

**Comment by Harvey1214** [comment]
This is already possible with the `HeaderTemplate` as shown in the referenced demo. Not sure we want to add built-in support for this exact scenario as there seem to be a lot of options for data filtering UI.

cc @hakenr

**Comment by hakenr** [comment]
@Harvey1214 Can you please make it a regular demo in HxGrid documentation, similar to inline-editing we added earlier? Thank you

**Comment by Harvey1214** [comment]
Sure thing - #473

**Comment by Arnnes** [comment]
HeaderTemplate was the first thing that came to my mind. But there are cases when it is quite difficult to make it pretty:

1. When the searching should not be enabled for all columns we need to put the column name to separate div instead of HeaderText to be able to align the column names.
2. By default, the sort icon is aligned with both column name and searchig box. Instead, we need to align it with the column name. Again, it is not impossible to achieve this with HeaderTemplate but I'm afraid the implementation won't be elegant enough.

So if you reconsider implementing support for a separate row for the search field, I'd appreciate it. Thanks

FYI @hakenr @jirikanda

**Comment by jirikanda** [comment]
Another approach, using FilterTemplate, not messing things in header.
Take it (& merge it) or leave it...

From my perspective there is one missing piece. I think the grid should navigate to the first page when changing the filter.
I suggest to add method RefreshDataAsync(RefreshMode mode) and the RefreshMode sould be enum with "No" and "ResetNavigation". Or something like that.

@Arnnes, @hakenr

**Comment by Harvey1214** [comment]
Another path that we could take would be to remove the `div` that is wrapping the `HeaderTemplate`, then it would be on the same level as the sort icon, therefore the user would be able to move the sort icon in between elements in the `HeaderTemplate` allowing for the desired layout - text and sort icon on the first line and an input field on the second line. I think also the second arrangement (dropdown filtering) could be easily implemented while preserving sorting.

![image](https://user-images.githubusercontent.com/62853076/221596439-9e5dae5c-0112-4a64-bfe6-430028233326.png)

We could add features such as the possibility of setting the CSS class of the container to make this simpler.

![image](https://user-images.githubusercontent.com/62853076/221598096-b73650ff-ff0c-4420-8f6f-56155cb2fc51.png)

cc @hakenr @crdo

**Comment by Harvey1214** [comment]
Another path that we could take would be to remove the `div` that is wrapping the `HeaderTemplate`, then it would be on the same level as the sort icon, therefore the user would be able to move the sort icon in between elements in the HeaderTemplate allowing for the desired layout - text and sort icon on the first line and an input field on the second line. I think also the second arrangement (dropdown filtering) could be easily implemented while preserving sorting.

![image](https://user-images.githubusercontent.com/62853076/221599216-a3b67008-89f0-4966-807d-af30bf2caf77.png)

We could add features such as the possibility of setting the CSS class of the container to make this simpler.

![image](https://user-images.githubusercontent.com/62853076/221599296-0c620c7d-122a-4009-a768-990b700673d4.png)

cc @hakenr @crdo

**Comment by Harvey1214** [comment]
@crdo @hakenr, I used the approach from the previous comment and got to the desired solution - the icon is located next to the `HeaderText`.

![image](https://user-images.githubusercontent.com/62853076/222186798-967ee806-ca23-4c67-b727-35fbf0a6b295.png)

Modifications made to `HxGrid` - removal of the element wrapping the `HeaderTemplate` and `HeaderText`.

On the usage side:

1. Add `w-100` and `order-1` classes to the filtering input. `order-1` causes it to render as the last child in the wrapping element with `display: flex;`. When we add also `w-100`, then it will take up an entire row.
2. Set the header cell container to `flex-wrap: wrap;` to allow the input to move to its own line. This could be simplified by adding the possibility of the addition of CSS classes to the header cell container.

I think this structure change is reasonable even if we add full built-in support for some filtering scenarios later.

The code is located in commit https://github.com/havit/Havit.Blazor/commit/96a89f847479eb6c78ff9facb272d5f0fc10f51a.
