### ISSUE TITLE
[HxGrid] Add support for load more pagination 

### ISSUE THREAD

**Issue by Arnnes** [havit/Havit.Blazor#471]
HxGrid supports only classic pagination and infinite scrolling. Is it possible to add support for "load more" pagination?

**Comment by jirikanda** [comment]
Note:
* it works well together - Pagionation and LoadMore (like Alza.cz, czc.cz, etc.)
* I do not expect Pager and LoadMore to be used at one in production (line 250 in HxGrid.razor.cs could be reverted)
* LoadMoreTemplate uses context to provide access to method to load more data (despite our discussion, @hakenr)
* LoadMoreContext solves well current requirement: to be able to render grids in "repeater" way - to use context is much easier over @ ref + this does not block using LoadMoreAsync on HxGrid (which is also there as internal), thanks @alexax578.
* think: If we never use pager with load more, we can load any number of aditional items, they do not need to be aligned with page size (not implemented but slightly required by JN)

**Comment by jirikanda** [comment]
FYI, @Allegon

**Comment by hakenr** [comment]
TODOs before release:
* [ ] LoadMore button configurability (`LoadMoreButtonSettings`? `LoadMoreButtonText`?) @hakenr after discussion with @crdo 
* [ ] visual tuning of the default UX (button text (dot? no dots?), button justification?, button size?, button color?, ...) @crdo 
* [ ] add to documentation - basic demo + short description
* [ ] naming of the `GridLoadMoreTemplateContext.LoadMoreAsync()` method. Should it be `HandleLoadMoreClick`?
* [ ] co-existence with pager (do we want separate modes? do we want a parameter to be able to enable/disable pager for LoadMore mode?)
* [ ] configurable number of items to load (I'm OK not to support custom number of items, but if there is a chance we will have to add this later, we should adjust the API accordingly. E.g. `GridUserState.LoadMorePagesCount` vs. `LoadMoreItemsCount`, etc.)

TODOs any later:
* [ ] add documentation (demo) for customizability (`LoadMoreTemplate`, button settings, ...)

(I will probably create a pre-release now, just to be able to play it with in our projects. cc @alexax578 @Allegon @Arnnes)

**Comment by jirikanda** [comment]
> naming of the GridLoadMoreTemplateContext.LoadMoreAsync() method. Should it be HandleLoadMoreClick?

From my perspective: No.

> co-existence with pager (do we want separate modes? do we want a parameter to be able to enable/disable pager for LoadMore mode?)

I don't think so. Even the Load More can co-existence with pager now (due to the inspiration), I am not keen on seeing it.

> configurable number of items to load (I'm OK not to support custom number of items, but if there is a chance we will have to add this later, we should adjust the API accordingly. E.g. GridUserState.LoadMorePagesCount vs. LoadMoreItemsCount, etc.)

Good point, lets do it this way.

**Comment by jirikanda** [comment]
This commit has a minor change, when no paging is used, the `GridDataProviderRequest.Count` property is `null` now, previously it was zero (by mistake).
`GridDataProviderRequest.Count` property type was NOT changed, it was and still is Nullable&lt;int&gt;.

**Comment by hakenr** [comment]
@crdo The demo is ready in `HxGrid_Demo_LoadMore.razor` (BTW: On my way to consolidate the demos with help of IDemoDataService.)

Can you please try to align the button to the center in the demo (just by using the `.razor` file, no external CSS). I just want to see how complicated it is to do so to help me decide whether it is easy and we can leave it as is or if it implies some complicated CSS/HTML (in such case I would suggest to go for some additional API support for such customization).

Thank you!

**Comment by crdo** [comment]
@hakenr If you think there would be a need for one of styling in a specific .razor file instead of a global rule we would have to create LoadMoreCssClass.
