### ISSUE TITLE
[HxGrid] Input-groups on inputs in HeaderTemplate not rendering correctly

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#476]
I tried to make the header filtering UI fancy, but the input-groups do not render correctly:
![image](https://user-images.githubusercontent.com/12828888/221160639-fa54e858-4176-4f72-9b3a-d8f0b05b49fa.png)

Sample code:
```razor
<HxGridColumn HeaderText="LCID" ItemTextSelector="item => item.LCID.ToString()" SortKeySelector="item => item.LCID" IsDefaultSortColumn="true">
	<HeaderTemplate>
		<HxInputText @bind-Value="lcidSearchString" BindEvent="BindEvent.OnInput" @bind-Value:after="grid.RefreshDataAsync" Placeholder="Type to search LCID" InputSize="InputSize.Small">
			<InputGroupEndTemplate>
				<HxIcon Icon="BootstrapIcon.Filter" />
			</InputGroupEndTemplate>
		</HxInputText>
	</HeaderTemplate>
</HxGridColumn>
```

cc @crdo

**Comment by crdo** [comment]
@hakenr not sure what UI are you trying to create, but you either have to use `InputGroupStart/EndText` or there has to be a `HxButton` or `HxDropdown` inside the `InputGroupEndTemplate`. https://havit.blazor.eu/components/Inputs#input-groups

**Comment by hakenr** [comment]
Maybe not the UX state of art but my intention was to put Funnel/Filter icon in InputGroupEnd[Text].
As the InputGroupEndText is string-only, my "code" was:
```razor
<HxInputText ...>
  <InputGroupEnd><HxIcon ... /></InputGroupEnd>
</HxInputText>
```

Should I put the `CssClass="input-group-text"` to `HxIcon` or wrap it with `<span class="input-group-text">`?

**Comment by crdo** [comment]
@hakenr If you add `CssClass="input-group-text"` to `HxIcon` used inside of `InputGroupStartTemplate` it works as expected.
And from the nature of any `Template` fragment, it feels right to me.
<img width="373" alt="image" src="https://user-images.githubusercontent.com/1410922/233973782-96a43041-bb9e-477b-93cb-efdc15e29618.png">
