### ISSUE TITLE
HxDropdownToggleElement is missing [Parameter] on the EventCallbacks

### ISSUE THREAD

**Issue by bbchriscooper** [havit/Havit.Blazor#48]
HxDropdownToggleButton has [Parameter] on the OnShown and OnHidden EventCallbacks, but the attribute is missing from them on HxDropdownToggleElement. I'm guessing this is just an oversight not on purpose? It makes it impossible to assign the event handlers in the markup. (I'm assigning them in code at the moment as a workaround, but thats rather messy)

**Comment by bbchriscooper** [comment]
That's great, thanks!

**Comment by hakenr** [comment]
fixed in release https://github.com/havit/Havit.Blazor/releases/tag/v1.6.5
