### ISSUE TITLE
[HxButton] Horizontal space (whitespace) between icon and text do not match for ButtonIconPlacement.Start|End

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#482]
![image](https://user-images.githubusercontent.com/12828888/221697046-e82c678b-05c3-4bce-ab0d-d20e0b1cd4cb.png)

**Comment by crdo** [comment]
@hakenr instead of rendering a spacer before or after the icon, I have switched the button to flexbox and handle the gap with new CSS var `--hx-button-gap` that is used for spacing icons, dropdown caret and spinner. The `--hx-button-icon-text-spacer-width` is now obsolete.
