### ISSUE TITLE
[HxSearchBox] Search icon missaligned when used with label

### ISSUE THREAD

**Issue by alexax578** [havit/Havit.Blazor#487]
Problem is that the search icon is absolutely positioned relative to the input container and that container contains both the input and the label.
![Bez názvu](https://user-images.githubusercontent.com/37944469/222766096-a9632d34-1496-4d1b-bd9a-e469eca289ea.png)

**Comment by crdo** [comment]
@hakenr @Harvey1214 @alexax578 I believe this has been resolved and released. Has it?
