### ISSUE TITLE
[HxCheckboxList] Inline checkboxes

### ISSUE THREAD

**Issue by vinod-vetrivel** [havit/Havit.Blazor#49]
Currently the HxCheckboxList doesn't support inline checkboxes as given in the bootstrap documentation [here](https://getbootstrap.com/docs/5.0/forms/checks-radios/#inline), and there is no option to set the CssClass of the individual HxInputCheckbox items.
Please add a property to select the layout, or the ability to set the CssClass of the individual checkboxes.
The same might exist on HxRadioButtonList too.

**Comment by hakenr** [comment]
@vinod-vetrivel You wanted that and it is there, enjoy.
Published in release 1.6.6 ;-)
