### ISSUE TITLE
[HxMessenger] messages from multiple positions.

### ISSUE THREAD

**Issue by TheAnachronism** [havit/Havit.Blazor#498]
Is it possible to create messages from different positions?
Right now, it seems like it's only possible from one global position set by the `<HxMessenger>` element, that's added on `MainLayout.razor`.

As an example, errors, or warnings might be shown more top middle or just more in front of the user and information messages might be shown in the bottom right.

**Comment by hakenr** [comment]
`HxMessenger` is just a higher-level dance with underlying `HxToastContainer` and `HxToast` components (corresponding to original Bootstrap components). With a few lines of code, you can create your own setup, where you might create several `HxToastContainers` at different positions and render `HxToast` components into them.

Take the current `HxMessenger` implementation as an inspiration:
https://github.com/havit/Havit.Blazor/tree/master/Havit.Blazor.Components.Web.Bootstrap/Toasts

(The value added by `HxMessenger` is the `IHxMessengerService` and its dispatching od the messages from code to the single `HxMessenger` component somewhere in App.razor / MainLayout.razor / ...)

...we currently do not plan to support per-message positioning with `HxMessenger`, it does not seem to be mainstream usage scenario. If we get more feedback on this feature request in future, we might reconsider this decision.
