### ISSUE TITLE
[HxTreeView] ItemInitialExpandedSelector seems not to work

### ISSUE THREAD

**Issue by jim-craane** [havit/Havit.Blazor#499]
I have a simple organization tree. If all items are opened, it looks like this:
![image](https://user-images.githubusercontent.com/64642269/224290767-9d8eca37-b163-4fa2-b802-705d905eda62.png)

By default, I want to open the parent tree items of the selected organization when the page is loaded.
So I added this logic to the ItemInitialExpandedSelector. But then I noticed it not always seems to work.

Then I tested it with all items always open:
ItemInitialExpandedSelector="@(p => true)"

This results in this:
![image](https://user-images.githubusercontent.com/64642269/224291549-84ef14a4-de26-4cc7-acbe-4412607cb0d7.png)

Even if the selected item is null, it has the same behavior. I expect that all tree items are open.
Is this a bug?

**Comment by hakenr** [comment]
Reproduced with `ItemInitialExpandedSelector="@(p => true)"`, only first level of the tree gets expanded.
