### ISSUE TITLE
[Debouncer] to help you debounce asynchronnous actions

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#501]
We often have to debounce some UI action, e.g. `HxInputText` with `BindEvent="BindEvent.OnInput"`.
We do not want to add debouncing API to every single component where there is a chance it will be needed.
We want to provide a simple "tool" and pattern for implementation of such debouncing.

**Comment by hakenr** [comment]
@jirikanda, @crdo, @alexax578 Please review the associated commit and the documentation provided:
https://havit.blazor.eu/concepts/Debouncer
(Released in 3.2.0-pre2 if you want to play with it.)

The documentation has not been added to Sidebar/Search yet as I want to be sure this ways it the one we want to have it implemented.
- [ ] review the API (naming, consistency, understandability, discoverability ... :-D)
- [ ] review the documentation (Is it clear enough? Should it be simplified? Should we provide more examples?)
- [ ] review the implementation

Then...
- [ ] add the documentation to Sidebar/Search
- [ ] add XML documentation of the class

**Comment by jirikanda** [comment]
@hakenr So useful, but I have some ideas:
## API
- I prefer to use the delay interval as the first argument (supports code readibility) (and yes, I always can using named parameters)

## Example
- What is the difference between queryDebouncedStarted and queryDebouncedCompleted in the UI? (I observe) they show always the same value.
- Using Task.Delay in PerformSomeWork can confuse developer use to always use Task.Delay in the workload to debounce it himself.
- it would be nice to show more instances (two instances) of debouncer to show they cannot be reused in multiple debouncing scenarios

## Implementation
- I think this is useless: `debounceCancellationTokenSource.Token.ThrowIfCancellationRequested();` while it is done by Task.Delay.
- should `catch (TaskCanceledException)` catch only the exceptions with the tokey the method creates?
