### ISSUE TITLE
[HxInputDate] Input text is overlapping validation icon

### ISSUE THREAD

**Issue by crdo** [havit/Havit.Blazor#503]
In a real world scenario, this is going to happened if the input is enclosed in narrow container and is validated.
<img width="993" alt="image" src="https://user-images.githubusercontent.com/1410922/225058074-f772cf7e-92af-4964-bfea-50ee5640f450.png">

**Comment by hakenr** [comment]
The issue still reproduces.

**Comment by crdo** [comment]
Also fixed already.
<img width="1005" alt="image" src="https://github.com/user-attachments/assets/fe355084-41ff-495c-b847-279df69b7402">
