### ISSUE TITLE
[HxAutosuggest] Input text is overlapping Clear/Search icon

### ISSUE THREAD

**Issue by crdo** [havit/Havit.Blazor#504]
It will also overlap the validation icon, if displayed.
<img width="561" alt="image" src="https://user-images.githubusercontent.com/1410922/225060015-b312681e-48c3-4f60-960f-6c1d64f25b5a.png">

**Comment by hakenr** [comment]
The issue still reproduces.
Probably to be addressed together with #503.

**Comment by crdo** [comment]
Fixed a while ago.
