### ISSUE TITLE
Change in HxGrid PageSize Default resolution logic/behaviour, between 3.2.7 and 3.2.8

### ISSUE THREAD

**Issue by pollardpj** [havit/Havit.Blazor#507]
I am not sure if this is an issue or not, or by design: With 3.2.7, you can set a default for page size on HxGrid:

`HxGrid.Defaults.PageSize = 10;`

And using the standard DataProvider interface, it respects this. 

In 3.2.8, the page size is not picked up, and you have to set the page size on the HxGrid instance for it to take effect.

I can do a repro, and look to fix this, unless a) it's by design or b) someone knows about this just by reading this and gets there quicker than me :) Loving this library, would love to contribute where I can.

I just tried this in the latest commit:

```
@page "/HxGrid_Issuexxx_Test"
@using System.Globalization
@inject ILogger<HxGrid_Issuexxx_Test> logger

<HxGrid Responsive="true" TItem="CultureInfo" DataProvider="ClientSideProcessingDataProvider" @ref="grid">
    <Columns>
        <HxGridColumn TItem="CultureInfo" HeaderText="LCID" ItemTextSelector="@(item => item.LCID.ToString())" SortKeySelector="@(item => item.LCID)" IsDefaultSortColumn="true" />
        <HxGridColumn TItem="CultureInfo" HeaderText="DisplayName" ItemTextSelector="@(item => item.DisplayName)" SortKeySelector="@(item => item.DisplayName)" />
    </Columns>
</HxGrid>
@code {
    private HxGrid<CultureInfo> grid;
    private int maxItems = 1000;
    private List<CultureInfo> localCultureInfos = CultureInfo.GetCultures(CultureTypes.AllCultures).ToList();

    public HxGrid_Issuexxx_Test()
    {
        HxGrid.Defaults.PageSize = 10;
    }

    private Task<GridDataProviderResult<CultureInfo>> ClientSideProcessingDataProvider(GridDataProviderRequest<CultureInfo> request)
    {
        logger.LogInformation(request.StartIndex.ToString());
        return Task.FromResult(request.ApplyTo(localCultureInfos.Take(maxItems)));
    }
}
```
And all rows are returned, but paging controls suggest otherwise. This happens with defaults set in Program.cs also.

**Comment by pollardpj** [comment]
Thank you! So quick!

**Comment by hakenr** [comment]
We don't like regressions. :-D
