### ISSUE TITLE
[HxButton] Automatic Spinner only works with Task methods

### ISSUE THREAD

**Issue by diejozef** [havit/Havit.Blazor#51]
Hi,

The automated spinner currently only works if the invoked eventhandler is wrapped into a Task.Run call.
e.g.
`<HxButton Text="Test" OnClick="@(async () => await Task.Run(() => DbContext.Database.EnsureCreated()))"/>`
works, however
`<HxButton Text="Test" OnClick="@(async () => await DbContext.Database.EnsureCreatedAsync())"/>`
does not.

Is this a limitation?

Thanks

**Comment by hakenr** [comment]
Hi @diejozef,
thanks for reporting the issue, we will look into this deeper.

From the very first point of view, there has to be `Task` returned to be able to run the spinner as without the `Task` there is nothing to await for.

In the meantime, you should be able to workaround this by wrapping any code in awaitable method returning `Task`, such as
```csharp
private async Task HandleClick()
{
   await ...
}
```

BTW: Your second example does not have to be wrapped at all
```razor
<HxButton Text="Test" OnClick="DbContext.Database.EnsureCreatedAsync"/>
```
should work.

BTW: Are you sure the the second version of your code does not show the spinner? Is there any chance the second version is so quick that you do not notice the spinner? Maybe the DB is already created?

**Comment by hakenr** [comment]
Confirming...

The button spins if there is a `Task` to await:
```razor
<HxButton Text="Task" OnClick="HandleClick" />
@code {
private async Task HandleClick()
{
  await Task.Delay(2000);
}
```

This does not spin as there is no `Task` to await, no chance to interrupt the call an render the spinner.
```razor
<HxButton Text="Task" OnClick="HandleClick" />
@code {
private async void HandleClick()
{
  Task.Delay(2000);
}
```

This is by design and you should always prefer awaitable Tasks in Blazor UI code.

We will stress this behavior in `HxButton` documentation to help the users understand it.

**Comment by diejozef** [comment]
The following handler won't show the spinner either:
```razor
<HxButton Text="Test" OnClick="IncrementCount" Color="ThemeColor.Primary"/>
@code {
    private async Task IncrementCount()
    {
        await Db.Database.EnsureCreatedAsync();
    }
}
```

So this means that I'll have to return with a Task at the end of the function no matter what?

**Comment by hakenr** [comment]
Your code returns Task and should work. You can easily test it by replacing the `await Db.Database.EnsureCreatedAsync()` with `await Task.Delay(2000)`.

Please check your implementation of `EnsureCreatedAsync()`. It should await the asynchronnous I/O operation with database. Also check whether it does take enough time for the user to actually see the spinner?

**Comment by diejozef** [comment]
Tried it with `Task.Delay(2000)` and got the expected result (spinner shown), however that EF Call (`EnsureCreatedAsync`) just freezes the UI for a few seconds without showing a spinner. Wrapping `EnsureCreated` in a `Task.Run` results in correct behavior as well which is weird.

**Comment by hakenr** [comment]
Well, the `Task.Run()` enques the action to the `ThreadPool` and returns a `Task` which completes after the action is completed. This usually means the action gets executed on separate parallel thread.

On the other hand, the behavior you see with `EnsureCreatedAsync()` usually means there is a significant amount of synchronous work (CPU bound) being executed before the inner asynchronnous I/O operation gets executed (the call to DB itself). My guess is that EF builds the model metadata or something like that (I guess you are running your app in Blazor Server model?).

**Comment by diejozef** [comment]
I'm actually running EF Core (Sqlite) in Blazor WebAssembly. Thank you for clarifying the underlying issue.
