### ISSUE TITLE
[HxInputDate and HxSearchBox]JS object instance with ID XX does not exist (has it been disposed?)

### ISSUE THREAD

**Issue by TorikatoTrong** [havit/Havit.Blazor#517]
HxInputDate and HxSearchBox When page reload (f5) have error: JS object instance with ID XX does not exist (has it been disposed?).
Please see attached video for details.
![image](https://user-images.githubusercontent.com/101616337/229027304-706c29d2-0d8e-45ba-8d0a-c32d1ffdfc60.png)

https://user-images.githubusercontent.com/101616337/229027086-d8a61629-5a1f-49ad-b65a-95cdd09f12b3.mp4

**Comment by hakenr** [comment]
@TorikatoTrong Are you still able to reproduce the issue with latest version of our library?
There were some updates in Bootstrap and MAUI which might resolve such issue.

**Comment by hakenr** [comment]
Due to lack of response, we are closing this issue as _unable to reproduce_.
