### ISSUE TITLE
[HxInputDate] [HxInputDateRange] Keyboard entry - navigating with TAB should go to next input, not the calendar

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#519]
User scenario:
1. Focus the input (click).
2. Type "0101" (as pattern for 01.01.2023)
3. Hit TAB key

Current behavior:
The focus is moved to the drop down calendar.

Expected behavior (what I want as a user):
The focus to be moved to next input.

My toughts:
* If we remove the dropdown from `tabindex`, how does the user navigate to the calendar with keyboard?
   * If the user uses keyboard, he does not need the dropdown calendar et al.
* ...therefor we do not need to distinguish different scenarios and vary the TAB behavior.

cc @crdo @jirikanda

**Comment by hakenr** [comment]
Tried a few exiting date pickers in the wild and none of them moves the focus from the input to the calendar-dropdown on TAB. Most of them move the focus to a next input, some of them (mainly those where the calendar is not shown on focus) move the focus to the calendar icon.

**Comment by jirikanda** [comment]
It has been implemented with #266 in commit  https://github.com/havit/Havit.Blazor/commit/c55b71c61d1795db137291ded4818f0369cd7407#diff-ff7383fa634ced7144f58649bec2aaff8b33c71e91550972c4994bb621ce1f42 (search for KeyboardNavigation="false") after deep dive discution with @hakenr.

However it has been removed a few days later in commit by @hakenr, probably poor merge (it was not easy, I remember the situation), commit https://github.com/havit/Havit.Blazor/commit/034f2de684fd355efa54adb25e505698149a60aa#diff-ff7383fa634ced7144f58649bec2aaff8b33c71e91550972c4994bb621ce1f42.

AFAIR, the only thing we need to do is to add KeyboardNavigation="false" on HxCalendar in HxInputDateInternal.razor and HxInputDateRangeInternal.razor.

**Comment by jirikanda** [comment]
@hakenr Check it, please. I hope it works like a charm ;-)
