### ISSUE TITLE
Valid control is improperly marked as invalid after change in source collection

### ISSUE THREAD

**Issue by HonzaZajic298** [havit/Havit.Blazor#524]
Hello,

I have found an issue regarding validation and presentation of invalid controls in **HxGrid**.
You can see the problem here - only 2nd row is actually invalid.
![Wrong behaviour](https://user-images.githubusercontent.com/120579709/232459814-ade4d453-e0a6-44a9-81b7-9411a4ec7fb6.png)

To demostrate the issue I have prepared a razor component which shows this invalid behaviour in more detail, you can find it here: [BlazorTest.zip](https://github.com/havit/Havit.Blazor/files/11248998/BlazorTest.zip) 

As a base I used your demonstrative code taken from https://havit.blazor.eu/components/HxGrid#inline-editing
and I wrapped it by EditForm with DataAnnotationsValidator.
The main difference between your original code and my version is usage of **HxInputText** control always for bound DisplayName and not using simple text when not editable.

Steps how to reproduce the wrong behaviour:
1. When you navigate this component you will see a grid with one invalid row.
2. When new row is added by clicking Add Row button this original row moves into second position but valid control on newly created line is marked as invalid.

Thanks,
Honza

**Comment by hakenr** [comment]
Duplicates #494.
Now you can use `ItemKeySelector` to provide `@key`s for the `HxGrid` items.
