### ISSUE TITLE
Different color between `form-label` and `form-check-lable` in same Form

### ISSUE THREAD

**Issue by rqx110** [havit/Havit.Blazor#527]
the `form-check-label` is darker than `form-label`

https://github.com/havit/Havit.Blazor/blob/f7a6e108bffd83afc05016854ad9d7ae68cc0498/Havit.Bootstrap/scss/_variables.scss#L28

![image](https://user-images.githubusercontent.com/1829209/233944622-43014287-a863-47eb-bce5-4ab6be899878.png)

**Comment by hakenr** [comment]
@crdo I guess this is intentional in our Havit.Blazor theme?

**Comment by crdo** [comment]
It is, but the checkboxes should have the same label color. So it is a bug.

**Comment by rqx110** [comment]
@crdo it looks like this issue is back on new v4.0

**Comment by crdo** [comment]
We will do a minor release with some hotfixes soon, I will have a look on this. It might not been properly merged to v4.
