### ISSUE TITLE
[HxTooltip] Custom content

### ISSUE THREAD

**Issue by TeaTime762** [havit/Havit.Blazor#531]
Hello,

in my experience was not able to hand in a custom component as tooltip content, only a string or html.
But I want to render a button in the tooltip, handle the click etc.

Am I right or do I miss something.
IF so do you plan to add custom content in tooltip component?

**Comment by crdo** [comment]
Hello @TeaTime762, your observation is right. It is not possible to render Blazor component inside HxTooltip nor HxPopover.

**Comment by hakenr** [comment]
Allow me to provide a more detailed explanation as to why the `HxTooltip`/`HxPopover` content cannot be a `RenderFragment`. The reason for this is that the underlying Bootstrap Tooltip and Popover components require the content to be passed through an HTML attribute, specifically through the `data-bs-content="..."` attribute. Unfortunately, there is currently no simple way to use a `RenderFragment` directly within an HTML attribute.

**Comment by hakenr** [comment]
@Xymanek You can use `HtmlRenderer` (.NET 9+) to convert any Razor component into its string representation (HTML).
See https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-components-outside-of-aspnetcore?view=aspnetcore-9.0

**Comment by Xymanek** [comment]
@hakenr Rip interactivity, but definitely an improvement for static content. Do you know of any razor-syntax-integrated approach to using HtmlRenderer?
