### ISSUE TITLE
[HxSidebar] Sidebar remains collapsed horizontally when the window is resized 

### ISSUE THREAD

**Issue by TPIvan** [havit/Havit.Blazor#532]
When a Sidebar is horizontally collapsed by toggler and then the window is made narrower which causes the Sidebar to collapse vertically to its header and then the Sidebar is expanded vertically by the hamburger expader it remain collapsed horizontally. There is no way how to expand the sidebar horizontally in this situation (the toggler is hidden).
![image](https://user-images.githubusercontent.com/39948593/236154710-8e8d8be0-2660-4421-8da4-4dc63a82888c.png)

### Steps to reproduce
1. Open the documentation site https://havit.blazor.eu/
2. Toggle the Sidebar 
3. Make the window narrower to make Sidebar to collapse to up
4. Expand the Sidebar

### Solution
A solution is probably quite simple the navbar toggler (hx-sidebar-navbar-toggler) should expand the sidebar also horizontally.
The onclick is added:

              <HxButton OnClick=@(async () => await SetCollapsed(false))
                    CssClass="@CssClassHelper.Combine("hx-sidebar-navbar-toggler ms-auto", GetResponsiveCssClass("d-??-none"))"

and the function:
       
       private async Task SetCollapsed(bool state)
	    {
		Collapsed =state;
		await InvokeCollapsedChangedAsync(Collapsed);
	    }

**Comment by hakenr** [comment]
@crdo Can you please check the proposed solution?

**Comment by crdo** [comment]
That is unfortunately not enough. 
We need to get rid of the `collapsed` class on `HxSidebar` and if this is suppose to be a real solution, it has to happen on the window resize event and also take in an account the responsive settings of the Sidebar.
That being said makes it a way more complicated than the proposed solution

**Comment by TPIvan** [comment]
The presence of `collapsed ` css class is controlled by `Collapsed` property.

        private string GetCollapsedCssClass() => Collapsed ? "collapsed" : null;
and onclik handler sets the property whenever the hamburger button is pressed. 
Afte the window resize sidebar is **horizontally** collapsed  (disapears) and shows only after clicking the hamburger button which expands it **horizontally** too and there is no need for reaction to window resize.   

I apologize - it is difficult to explain it clearly.

**Comment by crdo** [comment]
I think there is a better solution. Working on it...

**Comment by crdo** [comment]
@hakenr i decided to link WIP PR as I am not making any progress.

1) cleaned some CSS and moved utility classes to CSS isolation
2) implemented what @TPIvan is suggesting, but I consider it to be more a work-around than a real fix as is has some known issues (`SidbarBrand` text shows after clicking on hamburger menu, not after resizing window, collapse animation of mobile menu is not happening on the first click)
3) moved some logic of showing/hiding of elements when collapsed/expanded from CSS to Blazor using `CascadeParamterer`

From my POV, points 1 and 3 are merging worthy. Not sure about the 2. Real solution as I see it after messing around with the implementation for couple of hours is to separate rendering of `SidebarItems` in desktop and mobile view. Yes, it would duplicate presence of the items in the DOM, but it would solve this issue and simplify the implementaiton.

**Comment by crdo** [comment]
... is was hoping for a CSS only solution, but the with the possibility to set Responsivity of rendering the desktop/mobile version in Blazor and with missing SASS maps in the CSS isolation, it is simply not possible.

**Comment by TPIvan** [comment]
I think that a CSS only solution will be difficult (if possible), because after the sidebar is horizontally collapsed its state is changed and this state has to be responsively ignored.
I agree that proposed solution is more a workaround than a solution, but it respects the changed state and reverts it after pressing the vertical expand button.

**Comment by StefanOverHaevgRZ** [comment]
@crdo Do you have any idea for a permanent solution?
We're currently thinking about overriding all the sidebar css classes with media queries in our SCSS.
So basically inverting the root classes to have no width limitation on the collapsed state, and for the media query classes to have a set width instead.

**Comment by crdo** [comment]
That is only a half of the problem. 
Even if you remove the fixed width of the collapsed `Sidebar`, fixing the layout problem, you end up with correct layout but still missing the content of the `SidebarItems`, which is not rendered at all if `ParentSidebar.Collapsed == true`.

<img width="574" alt="image" src="https://github.com/user-attachments/assets/3f494092-5ca6-44bc-8507-a9a37af45953">

I have an idea of permanent solution which is to separate rendering of the `nav` content for mobile/desktop. 

The mobile item is a simple `NavItem` with no logic whatsoever contrary to desktop item that has `tooltips`, `dropdowns`, `expanded/collapsed` variant etc.

I am giving you guys a hads-up that we are currently focused on activities related to Havit.Blazor.Premium as part of our monetisation efforts tracked in #798 so if anyone giving it a shot I can support you with my ideas.

**Comment by TPIvan** [comment]
@crdo:
I believe that categorizing navigation strictly into mobile and desktop views might be a bit limiting. For instance, a desktop window can be resized to a narrow width, and mobile devices can switch orientations, altering their display between mobile and desktop views.

**Comment by crdo** [comment]
@TPIvan what I propose is that both of the views will be always rendered in the DOM and its visibility will be managed by responsive utility classes set on the `Sidebar`. 
The key take-away is that the mobile nav would not be anyhow affected by the collapse state of the desktop nav.

**Comment by StefanOverHaevgRZ** [comment]
@crdo Sounds like the best approach to be honest. I had a look at the Bootstrap 5.3 docs page, and they handle this issue similiar,  but a bit different (the menu becomes an offcanvas there).

Some design questions regarding the proposed solution:

1. How should the files/classes/components be organized? Separate components for the "sidebar" and "topbar" states, or everything in `HxSidebar`?
1. For the small screen size: should it always be a "topbar", or optional the "offcanvas" approach?

There are probably multiple ways to approach this, either with breaking changes or without.

**Comment by crdo** [comment]
@StefanOverHaevgRZ @TPIvan good news, finally found some time to fix this. We will cleanup the solution with @hakenr next week and release it.

**Comment by crdo** [comment]
@StefanOverHaevgRZ @TPIvan you can validate the fix in 4.7.2-pre01.

**Comment by StefanOverHaevgRZ** [comment]
@crdo `AddHxMessageBoxHost` is gone?

**Comment by StefanOverHaevgRZ** [comment]
@crdo Mostly working fine 👍 Some minor "issue", maybe with the same root issue:

- Setting the `Collapsed` property to `true` does not affect the small screen navigation.
![image](https://github.com/user-attachments/assets/cdfaff8a-0b79-41a0-99ea-9a7f15f255cd)
  1. Have navigation expanded in large and small screen state.
  2. In large screen state, set `Collapsed` to true.
     - Large screen nav is collapsed
  4. Reduce window size to small screen.
     - Small screen nav is still expanded, even though `Collapsed` is `true`
- Having the small screen nav will stay open when switching between large and small screen state.
  1. In small screen state, open the top navigation.
  2. Switch between small and large screen size.
     - Whenever switching to small screen size, the navigation is still open.
     - From a UX, I kinda expect the navigation to be closed.

Maybe both things are by design and not real issues. 😄

**Comment by crdo** [comment]
@StefanOverHaevgRZ thanks for the feedback. I think what you describe is related to https://github.com/havit/Havit.Blazor/issues/529 and that have not been addressed yet.

**Comment by TPIvan** [comment]
@crdo I have tested HxSidebar on the documentation website, and it works mostly well. However, I have noticed two minor issues:

1. When the issue was initially reported, the main documentation sidebar was collapsible. Currently, I cannot find a toggle button, so I had to add a custom toggler.
2. When the window is resized, the collapsed sidebar becomes wider just before it disappears.


![image](https://github.com/user-attachments/assets/49461a46-93d5-45ce-a8e5-c3c6035d9d4b)

**Comment by StefanOverHaevgRZ** [comment]
@TPIvan Probably the new default width of 300px instead of 250px playing a part here? I could not observe this issue however.

**Comment by crdo** [comment]
@TPIvan 
The collapse toggle is there, but in a slightly more minimalistic fashion.
<img width="820" alt="image" src="https://github.com/user-attachments/assets/dd922930-0ec1-4591-8f58-4aec2ad5604a">
I am aware of the second point, but that is bug in the docs, not in the Sidebar component itself.

**Comment by TPIvan** [comment]
@crdo I apologize for the confusion earlier.

1. I now see the toggle button. Thanks for pointing that out!
2. I deleted my clone and downloaded it again. The issue no longer appears, so it seems the code was not properly synchronized before.

**Comment by crdo** [comment]
I fixed the docs in the meantime. It will be part of the next release.
