### ISSUE TITLE
[HxContextMenuItem] Add Href property to support navigation.

### ISSUE THREAD

**Issue by TPIvan** [havit/Havit.Blazor#559]
### Current state
[HxContextMenuItem.razor](https://github.com/havit/Havit.Blazor/blob/master/Havit.Blazor.Components.Web.Bootstrap/ContextMenus/HxContextMenuItem.razor) renders as 
      
       <li> 
          <a onclick="...">icon + text + (content) <a>
       <li>
It has `OnClick` property which to the `onclick` event, but there is no Blazor equivalent for the `href ` attribute.
### Background
If I want to navigate to a detail page from the context menu, I have two options:

- Use `NavigationManager.NavigateTo` in the `OnClick` handler:

          <HxContextMenuItem Text='Detail' OnClick='()=> NavigationManager.NavigateTo($"detail-page")'>
      
 -  Use `HxNavLink` as a child component (I have to set its `Text` property instead of the HxContextMenuItem's `Text` property to make the link clickable):                      

            <HxContextMenuItem>
                     <HxNavLink Text="Detail" Href="detail-page" />
            </HxContextMenuItem>

However, both options are not very convenient. 
### Proposal
I think a better solution would be  **to add ability to set `href` attribute of already present <a> tag**  which would map to the `href` attribute of the existing `<a>` tag:

         <HxContextMenuItem Text='Detail'  Href="detail-page">
This way, I can easily navigate to different pages from the context menu without using extra components or code.

**Comment by hakenr** [comment]
I'm not entirely sure, but I have a feeling we tried this and there was some problem with the `Href` parameter. @crdo?
Some weird behavior or JavaScript error when closing the context menu on such navigation? External navigation?

**Comment by crdo** [comment]
I do not recall that. Changing the URL with Blazor while the dropdown menu is open could cause a JS error. 
@TPIvan give it a try and submit a PR.

**Comment by TPIvan** [comment]
I have created a pull request https://github.com/havit/Havit.Blazor/pull/560.
An internal and external navigation was tested and seems to work. 
@hakenr: I think that something was changed in the context menu or in the grid because in past (6 month ago) there was a problem with grid trying to refresh itself whenever the context menu was clicked.
