### ISSUE TITLE
Question:HxCarousel - do not stop

### ISSUE THREAD

**Issue by walterX12** [havit/Havit.Blazor#56]
Is it possible to cycle througt slides in HxCarousel without stopping, when user points mouse on slide ?

I am trying to achieve, that Carrousel would be sliding all the time. User cannot stop it anyhow.
Is it possible ?

**Comment by hakenr** [comment]
Hi @walterX12,
as far as I understand, according to [Bootstrap Doc](https://getbootstrap.com/docs/5.1/components/carousel/#options), if you want to let the carousel sliding all the time without interference with the mouse, it is needed to set the `pause` option to `false`.

Such option is currently not implemented in `HxCarousel` and you would need to adjust the underlying bootstrap-carousel options on your own with addition JavaScript code (with the `bootstrap.Carousel.getOrCreateInstance(element)`).

If you wait several days we can add the new parameters needed to our `HxCarousel` or you can create a PR. ;-)

**Comment by walterX12** [comment]
Thank you for quick reply. I am happy to wait several days. Thank you in advance

**Comment by walterX12** [comment]
Thank you. It helps

**Comment by hakenr** [comment]
Will be part of next release, probably tonight or on Friday.

**Comment by hakenr** [comment]
Release just now. https://github.com/havit/Havit.Blazor/releases/tag/v2.0.1
