### ISSUE TITLE
[HxDropdownDivider] Divider line not connected to the dropdown border

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#562]
![image](https://github.com/havit/Havit.Blazor/assets/12828888/3d9d0544-f5ea-40c0-b3d5-9cbefa5a1293)

@crdo, probably a v5.3 regression in our library?

https://getbootstrap.com/docs/5.3/components/dropdowns/#dividers
![image](https://github.com/havit/Havit.Blazor/assets/12828888/ffeee036-d6c2-4b6c-9867-71c8b543f741)

**Comment by crdo** [comment]
That is on purpose/as designed as we override the look of dropdowns in our build. There is a padding added to the dropdown menu and the DropdownItems are rounded instead of full-width in default.

**Comment by hakenr** [comment]
ok
