### ISSUE TITLE
[HxTooltip] Immediately disappears when text is changed

### ISSUE THREAD

**Issue by alexax578** [havit/Havit.Blazor#563]
I found a weird behavior of the HxTooltip component. When I change the text of the tooltip component and then immediately after that call ShowAsync the tooltip component is shown and then immediately hides.

**Comment by hakenr** [comment]
@alexax578 Is it only `String.IsNullOrWhitespace()` to non-`String.IsNullOrWhitespace()` or any change to tooltip text?

**Comment by alexax578** [comment]
@hakenr You can refer to the example issue page I created in this branch: https://github.com/havit/Havit.Blazor/tree/issue/HxTooltip_563

I think I observed the same behavior occur for NULL value in the beginning and any non-empty string value at the beginning. I did not test anything else.

**Comment by hakenr** [comment]
https://github.com/havit/Havit.Blazor/commit/db34bd5cf32f8d1457f9484cb7ab326286682595

**Comment by hakenr** [comment]
Merged repro test in PR #574
