### ISSUE TITLE
[HxAutosuggest] differentiate between search icon and clear icon using CSS classes

### ISSUE THREAD

**Issue by alexax578** [havit/Havit.Blazor#565]
I would like to be able to write CSS selectors that change colors of the icons based on whether the search icon is shown or the clear icon is shown. I don't want to target CSS classes of the icons themselves because they can be changed using the SearchIcon and ClearIcon parameters.

**Comment by crdo** [comment]
This is more a work-around than a solution, but you can use the :placeholder-shown pseudo selector https://developer.mozilla.org/en-US/docs/Web/CSS/:placeholder-shown

So it would be:

.hx-autosuggest-input-icon {
 // styles for clear icon
}

.hx-autosuggest-input:placehoder-shown + .hx-autosuggest-input-icon {
 // styles for search icon
}
