### ISSUE TITLE
Sorting by non-string columns fails with ApplyGridDataProviderRequest

### ISSUE THREAD

**Issue by TPIvan** [havit/Havit.Blazor#569]
### Issue
`ApplyGridDataProviderRequest` is a useful feature that allows applying grid parameters to a _queryable_ source. However, it does not work when sorting by columns that are not of type string.

### Example
When I try to sort by an int column, I get the following exception (shortened):

    System.InvalidOperationException: 'The LINQ expression
    ...
    .OrderBy(i => (IComparable)i.Age)' could not be translated.

The reason is that the sorting expression is stored as `Func<T, IComparable>`. When the property is `string`, the expression is simple, like `p=>p.Name`. But when the property is a value type like `int`, the expression is complex, like `p=>Convert(p.Age, IComparable)`. EF cannot translate such an expression to a query.

### Possible solution
I have a modified method that parses the expression and extracts the inner property expression. However, it uses reflection. The key part is

    if (expression.Body is UnaryExpression unaryExpression)
    {
      var propertyExpression = (MemberExpression)unaryExpression.Operand;
      var parameters = expression.Parameters;
      //Here we RELY that there is only ONE method with two parameters.

      MethodInfo? method = typeof(Queryable)
        .GetMethods()
        .Where(m => m.Name == methodName && m.GetParameters().Length == 2)
        .SingleOrDefault();
      MethodInfo? generic = (method ?? throw new AmbiguousMatchException($"More then one method {methodName} with two parameters exists in {nameof(Queryable)} class"))
                  .MakeGenericMethod(typeof(T), propertyExpression.Type);
      Type delegateType = typeof(Func<,>).MakeGenericType(typeof(T), propertyExpression.Type);
      var lambda = Expression.Lambda(delegateType, propertyExpression, false, parameters);
      return (IOrderedQueryable<T>?)generic?.Invoke(null, new object[] { entities, lambda });
    }
This is not very elegant but it works. I can create a pull request if you are interested.

**Comment by hakenr** [comment]
@jirikanda Can you please take a look? Thanx

**Comment by jirikanda** [comment]
Maybe I missed something but If you want to pass information about sorting between layers, there is a SortString property for this use.
If you want to sort data in memory & automatically, you should use SortKeySelector.

[See docs](https://havit.blazor.eu/components/HxGrid)

* SortKeySelector
Returns column sorting expression for automatic grid sorting. To be used for "strongly typed" setting of sorting, required for client-side sorting. Must be [IComparable](https://docs.microsoft.com/en-us/dotnet/api/System.IComparable). Sorting of the column does not support multiple expressions. Create an artificial property and implement [IComparable](https://docs.microsoft.com/en-us/dotnet/api/System.IComparable).

* SortString
Returns column sorting as string. Use to set sorting as a string, ie. to get value to pass to backend. Ignored for client-side sorting.

Using filters & SortString in our backend code can look this way (SortString is Sorting in the code below):

```
return someQueryableDataSource
	.WhereIf(filter.CompanyId != null, o => o.CompanyId == filter.Compan.Id)
	...
	.OrderByMultiple(Sorting, sortingExpression => sortingExpression switch
	{
		nameof(OrderDto.CustomerReferenceNumber) => new() { o => o.CustomerReferenceNumber },
		nameof(OrderDto.DeliveryPlace) => new() { o => o.CompanyBranch.Street, o => o.CompanyBranch.Zip, o => o.CompanyBranch.City },
		nameof(OrderDto.Id) => new() { o => o.Id },
		nameof(OrderDto.OrderedBy) => new() { o => o.Contact.Surname, o => o.Contact.FirstName },
		nameof(OrderDto.OrderedDate) => new() { o => o.OrderDate },
		...
		_ => throw new InvalidOperationException($"Unknown SortingItem.Expression {sortingExpression}.")
	})
	.Select(o => new OrderDto
	{
		Id = o.Id,
		...
	});
```

**Comment by TPIvan** [comment]
I wanted to keep the issue report short, so I might have left out some key information. Here is a more detailed explanation:

I have a grid with several columns, including these two:

    <HxGridColumn ItemTextSelector="@(item => item.ProfileName)" SortKeySelector="@(item => item.ProfileName)" />
    <HxGridColumn ItemTextSelector="@(item => item.Modified.ToString())" SortKeySelector="@(item => item.Modified)" />

The type of `ProfileName` is `string` and the type of `Modified` is `DateTime`.

The data for the grid are created using the queryable approach described in  [docs](https://havit.blazor.eu/components/HxGrid#Queryable). The difference is that the `query` is not a list converted to `IQueryable`, but an _Entity Framework_ expression. This expression has to be translated to _SQL_, and that's where the problem occurs.

In my ApplyToAsync<TItem> method (created by #66), I get the sort key selector from `request.Sorting[0].SortKeySelector`. For `ProfileName`, it is `item=>item.ProfileName`, as shown in this image:

![image](https://github.com/havit/Havit.Blazor/assets/39948593/fc9d0821-a483-4fde-a763-249a46e5873c)

For Modified, it is `item=>Convert(item.Modified, IComparable)`, as shown in this image:

![image](https://github.com/havit/Havit.Blazor/assets/39948593/31f1693e-8b18-487a-969b-22d48dd0b567).

The second expression is not valid for _EF_ and causes a _LINQ_ exception.

I hope this makes the issue clearer. Please let me know if you need more clarification.

**Comment by jirikanda** [comment]
@TPIvan, I will look at your report later.
However, first impression: If there is a problem with Convert expression and no problem without Covnvert expression, why not try to remove the Convert expression? [how?](https://github.com/havit/HavitFramework/blob/695c28aba5ceccbea0f98dbcb3aceb86e3d969a5/Havit.Core/Linq/Expressions/ExpressionExt.cs#L31)

**Comment by TPIvan** [comment]
@jirikanda You might be right and I would be glad if I could avoid the ugly reflection based code. The challenge is that it still has to be done inside `ApplyGridDataProviderRequest`.

**Comment by introw** [comment]
Hi, I am experiencing exactly same issue. 
Can you please provide example how to use `RemoveConvert` to get sorting by DateTime work?
Thank you!

**Comment by introw** [comment]
Any update please?

**Comment by jirikanda** [comment]
I hope it is the same as #883 which was fixed.
(Feel free to disaggree!)

**Comment by TPIvan** [comment]
After a quick test with the prerelease version, it appears to work. However, a final, fully tested confirmation will take some more time.

**Comment by hakenr** [comment]
@TPIvan Great, thanks for this preliminary confirmation.

**Comment by TPIvan** [comment]
I have tested the solution more thoroughly and confirm that it resolves the reported problem. I have removed my workaround and replaced it by calling the ApplyGridDataProviderRequest method.
