### ISSUE TITLE
[HxModal] [HxDialogBase] Examples of form integration

### ISSUE THREAD

**Issue by DeanBrighton** [havit/Havit.Blazor#570]
Is there any examples of using HxModal or HxDialogBase with forms for CRUD operation? I cannot see how to pass modals between components and I get a null reference when trying to use HcModal in an "edit" operation. Thanks.

**Comment by hakenr** [comment]
Unfortunately not. If you provide us with a simple repro of your issue, we can try to help you resolve it.
