### ISSUE TITLE
Please implement ComboBox with multi-select

### ISSUE THREAD

**Issue by resignationinfinite** [havit/Havit.Blazor#579]
It would be great to have a ComboBox available along with the option for multi-select. Currently the MultiSelect component is the only choice but when the data source has hundreds of entries it can get cumbersome. Thank you for your consideration! These components are awesome.

**Comment by hakenr** [comment]
Consider using [`HxInputTags`](https://havit.blazor.eu/components/HxInputTags). It is string-only (no `ItemValueSelector`), but might be a good fit for some scenarios (if needed, you can return any items you want from the `DataProvider` no matter the keyboard input is).
![image](https://github.com/havit/Havit.Blazor/assets/12828888/955ea15d-9bdf-4e61-8027-c3302d0c720e)

**Comment by hakenr** [comment]
Duplicates #616.
