### ISSUE TITLE
[HxGrid] Data never gets loaded when using PlaceholdersRowCount together with InfiniteScroll mode

### ISSUE THREAD

**Issue by Arnnes** [havit/Havit.Blazor#588]
When the `PlaceholdersRowCount` is set to a higher number of rows, causing the content not to fit on the page, the grid continues to display placeholder rows forever. Data is only loaded when I scroll to the end of the placeholder rows within the grid.

The bug can be reproduced even when the value of `PlaceholdersRowCount` is not set high, as it occurs when the browser window is small.

The behaviour can only be reproduced in `InfiniteScroll` mode, other modes seems to be working correctly.

**Comment by hakenr** [comment]
@jirikanda It seems, the `Virtualize` component does not initiate loading data (`DataProvider` not called), unless it is visible (in viewport). We might try to resolve this by changing the order of rendering and expect the upper part of the grid to be "most likely visible")...

Currently it renders:
1. Header row
2. Placeholders / Loading template
3. EmptyData template (mutually exclusive to 2.)
4. Data rows (Virtualized or not)
5. Footer row
6. Pager
7. LoadMore button/template

We might change the order to render data (4.) before Placeholder/Loading (2.).
Do you see any risks in such change?

cc @crdo

**Comment by jirikanda** [comment]
😮

I would try the same.
Risks? Have no idea. Hopefully none.
