### ISSUE TITLE
HxGrid cell link does not work

### ISSUE THREAD

**Issue by franky1017** [havit/Havit.Blazor#589]
I am using HxGrid and one of the columns is a link to another page, this is what I did:
```
	    <HxGridColumn Context="item">
			<ItemTemplate>
				<a hreaf="/_admin/courses/course/@item.CourseId.ToString()">Edit</a>
			</ItemTemplate>
		</HxGridColumn>
```
It generates the Edit link successfully, however, nothing happens when clicking on it.

I then changed it to a button:
```
	    <HxGridColumn Context="item">
			<ItemTemplate>
				<HxButton Text="Edit" Color="ThemeColor.Primary" Size="ButtonSize.Small" OnClick="@(() => _nav.NavigateTo("/_admin/courses/course/" + item.CourseId.ToString()))"></HxButton>
			</ItemTemplate>
		</HxGridColumn>
```

This works well. Please advise, thanks!

**Comment by hakenr** [comment]
It seems you have a typo in your code. The attribute shoud be `href` not `hreaf` for the `<a>` HTML element.

**Comment by hakenr** [comment]
@franky1017 And BTW, thanks for sponsoring us! Really appreciate it.

**Comment by franky1017** [comment]
> @franky1017 And BTW, thanks for sponsoring us! Really appreciate it.

I've been using Blazor since beta and I have to tell you, your components are by far the single most useful one. I constantly struggle with any other bootstrap templates due to the extensive use of js and get those templates working with blazor is such a painful process. But with your components, I threw away all other templates and only need yours. Please keep up the good work, I really appreciate your effort on this project!

**Comment by franky1017** [comment]
> It seems you have a typo in your code. The attribute shoud be `href` not `hreaf` for the `<a>` HTML element.

Oh dah, my bad lol
