### ISSUE TITLE
[HxSelect] cannot handle invalid value (value not present in Data)

### ISSUE THREAD

**Issue by franky1017** [havit/Havit.Blazor#590]
I have a HxSelect component that binds to a nullable int say int? CategoryId. Later on, the category id value saved in the db is no longer present in the dropdown. However, when populating the edit form, I received an error:

`Error: System.InvalidOperationException: Data does not contain item for current value '3'.
   at Havit.Blazor.Components.Web.Bootstrap.HxSelectBase`2.RefreshState()`

It's because 3 is not a value in the drop-down but it's still the binding value, therefore it can't find it. Is there an elegant way to resolve this? If not found, can it just default to the NULL value as I've specified the HxSelect as Nullable.

Thanks!

**Comment by hakenr** [comment]
This is intended behavior, as `HxSelect` is simply a raw UI component. For the time being, we've chosen not to embed any business logic within it. Binding to a non-existent value generally indicates that you should determine what the new values should be (application business logic), and we didn't want to obscure these scenarios by merely falling back to `default(TItem)` (`null`).

In our applications, a missing value often represents a "soft-deleted" codebook item. In such cases, you'll want to preserve the original value for existing entities without making the codebook item available to new ones. In other instances, you may wish to replace non-existent values with new, corresponding ones (mapping), etc.

We designed it this way to compel the developer to make these decisions explicitly. These choices should be made either in the business layer or in a scenario-specific component like `CategoryPicker` (which might be derived from `HxSelect` or, more appropriately, `HxSelectBase`). Here, you can opt to fall back non-existent categories to `null`.

(But this is not the first time we hear the request to handle the non-existent values in the component. If you provide us reasonable arguments and find some other users to vote for such feature, we might reconsider... ;-))

**Comment by franky1017** [comment]
My argument is that is the default inputselect behavior -- if you pass a value and it's not in the drop-down list values, .NET will default to the first value where you typically have something like - Select Value -- with empty value in the option field. if you don't have this, .NET will display nothing, forcing you to make a selection. Not saying this is better, but the key difference is it doesn't throw an error. For your component, it actually throw an error which is unexpected behavior.
