### ISSUE TITLE
[HxDropdownToggleButton] Add AutoClose Parameter to control the closing behavior

### ISSUE THREAD

**Issue by TPIvan** [havit/Havit.Blazor#600]
### Current state
`HxDropdownToggleButton` is rendered as a HTML button with `data-bs-toggle` and `data-bs-auto-close` attributes. The value of `data-bs-auto-close` is controlled by `AutoClose` property of the parent `HxDropdownButtonGroup` component.

### Problem 
I need a dropdown triggered by a button, which is inside an input group. The dropdown has to be closed by an inner button. As stated in Havit documentation ([Input groups](https://havit.blazor.eu/components/Inputs#input-groups)) `Bootstrap does not expect any <HxDropdown /> wrapper` there. Therefore, there is no way to specify the `AutoClose` behavior for the dropdown button.

### Proposal 
I propose to add a property `AutoClose` to the `HxDropdownToggleButton` component, which would allow the user to set the closing behavior of the dropdown button independently of the parent `HxDropdownButtonGroup` component.
This would require modifying this [line](https://github.com/havit/Havit.Blazor/blob/a61beb74190946bcac6b89ba13a570bd5ee54469/Havit.Blazor.Components.Web.Bootstrap/Dropdowns/HxDropdownToggleButton.cs#L94) of code

    AdditionalAttributes["data-bs-auto-close"] = (DropdownContainer?.AutoClose ??  DropdownAutoClose.True) switch

to 

     AdditionalAttributes["data-bs-auto-close"] = (DropdownContainer?.AutoClose ?? AutoClose) switch

This would solve the problem and make the HxDropdownToggleButton component more flexible and customizable.

**Comment by hakenr** [comment]
Note to implementer:
* The local parameter should have a higher priority than the container-one.
* Take Settings/Defaults into account.

**Comment by TPIvan** [comment]
It is present in 4.2.7 and works as I have expected.
