### ISSUE TITLE
Adding is-valid Bootstrap class when input is valid

### ISSUE THREAD

**Issue by pollardpj** [havit/Havit.Blazor#603]
I notice that the is-invalid class is used by the HxInput components. I don't see is-valid used, where a green tick is shown if the validation succeeds, e.g.: https://getbootstrap.com/docs/5.0/forms/validation/ :

![image](https://github.com/havit/Havit.Blazor/assets/3042366/4835e5e7-fede-43e4-9e88-4b674f1f3e01)

I have manually added it in some cases, but it's hard to get right - is this something that we couldshould do in the HxInput components too? Is there some reason why we can't? Would it be a tricky PR?

**Comment by hakenr** [comment]
Hello @pollardpj,

The challenge lies in the fact that Blazor's validation architecture lacks a built-in mechanism for indicating successful validation. We attempted to implement this feature for a client project, achieving visual cues like green checkmarks for valid inputs. However, the solution required numerous workarounds, compromising the overall design and implementation quality. As a result, we opted not to include this feature in our library.

If you are interested I can try to find and share the source code of our implementation for such feature.

**Comment by pollardpj** [comment]
Thanks @hakenr , that would be useful to see if it is not too much trouble :)

**Comment by hakenr** [comment]
I gave you read access to one of our repositories.
In the end, we agreed with the client we won't implement full indication of positive validity, but only a "soft validation message + indicator" which is currently controlled manually by setting the `SoftValidationWarning` parameter.

You will find the important source code here: https://github.com/havit/Bt.Blazor/tree/master/Havit.Bt.Blazor/Components/Forms/Internal

You will also find several examples of custom `HxInputBase`-component implementation there, e.g. the `BtSingleSelect`:
https://github.com/havit/Bt.Blazor/tree/master/Havit.Bt.Blazor/Components/Forms/Selects
