### ISSUE TITLE
Changing HxMessenger toast delay

### ISSUE THREAD

**Issue by Vallatu** [havit/Havit.Blazor#609]
As per [HxMessenger](https://havit.blazor.eu/components/HxMessenger) documentation, 

> Informational messages are automatically hidden after 5 seconds

I realize HxMessenger is a wrapper for [HxToast](https://havit.blazor.eu/components/HxToast) which does have parameter called `AutohideDelay` but it is unclear for me how to easily change that in my code. 

I know this is a rookie question and I do apologise for wasting everyone's time here, but I tried searching, without results unfortunately, so here I am.

**Comment by hakenr** [comment]
You can set the delay by setting:
```
HxMessengerServiceExtensions.Defaults.InformationAutohideDelay = 5000; // ms
```
