### ISSUE TITLE
[HxPopover] Dismiss on next click is not working on macOS

### ISSUE THREAD

**Issue by crdo** [havit/Havit.Blazor#611]
We do not have the required structure:

"Dismissing on next click requires specific HTML for proper cross-browser and cross-platform behavior. You can only use `<a>` elements, not `<button>`s, and you must include a [tabindex](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex)."

**Comment by oliverw** [comment]
Hmm, its working here: https://havit.blazor.eu/components/HxPopover
