### ISSUE TITLE
Top navigation menu not collapsing after click on mobile

### ISSUE THREAD

**Issue by franky1017** [havit/Havit.Blazor#612]
I am using the HxNavbar to construct the top navigation menus. However, on mobile phone, once you click on the menu, it does not collapse and remains open. I am using iPhone.

Please point your phone to [test site](https://future-envision.azurewebsites.net/)

Please let me know if I missed any settings.

Thanks!

**Comment by crdo** [comment]
Hi @franky1017 I have tested the link on my iPhone this morning and the navigation is working as expected. 
Could you please try the official Bootstrap site with your device to make sure it is not a Bootstrap issue related to your device? https://getbootstrap.com/docs/5.3/components/navbar/
