### ISSUE TITLE
HxIcon doc page points to bad location

### ISSUE THREAD

**Issue by pm100** [havit/Havit.Blazor#62]
![image](https://user-images.githubusercontent.com/489231/149236613-53f6144d-629f-43be-8db9-721dd3064b3b.png)

the second link points to an azure page that needs credentials. I suspect it should point to  github source file

**Comment by hakenr** [comment]
Correct.
@Harvey1214 please change the link to GitHub source code.
Or maybe better to https://havit.blazor.eu/types/BootstrapIcon? Or both...
