### ISSUE TITLE
[HxInputDate] Add DisplayMonth to HxInputDate

### ISSUE THREAD

**Issue by blanchardglen** [havit/Havit.Blazor#621]
Hello,

I have a requirement to add the `HxCalendar.DisplayMonth` parameter to the `HxInputDate`.

More than happy to implement and raise a PR.

That is quite a simple change.

Part 2 is for `HxInputDateRange`, it would be a bit more complex as the whole idea is to optionally change the `DisplayMonth` of the `EndDate` when the `StartDate` is changed while `EndDate` is still null.  Should it be a flag along the lines of end date is after start date?  Think holiday reservation or event booking.

Any thoughts before I start implementation?

Thanks.

**Comment by hakenr** [comment]
Do you want the displayed month in the dropdown to default to something other than the current month (`Today`) when no `Value` is set? If so, we should name the new parameter `CalendarDisplayMonth`.

For the `HxInputDateRange`, I expect the user experience to be such that when the `EndDate` isn't set, it displays the same month as the `StartDate`. To be honest, I thought our current implementation already did this. It would be a bug if it defaults to the current month (Today).

I'd appreciate a pull request on this (both ;-)).

cc @crdo @jirikanda

**Comment by blanchardglen** [comment]
The attached PR fixes the bug and also provides the enhancement.
