### ISSUE TITLE
ColorModeSwither fails on start in BlazorTestApp

### ISSUE THREAD

**Issue by crdo** [havit/Havit.Blazor#635]
Probably only happens on macOS/Safari on BlazorTestApp startup.
<img width="1204" alt="image" src="https://github.com/havit/Havit.Blazor/assets/1410922/9188e78d-1170-4b69-b756-0d83a4a2007c">

**Comment by hakenr** [comment]
Please send me the network log, i.e. what is the request path where the server returns 404 (first line of your screenshot).
