### ISSUE TITLE
[HxMultiSelect] synchronize "SelectAll" checkbox with selected items

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#638]
Feedback from the Field

1. **Visual Feedback for Manual Selection**: When all items in the list are manually selected one by one, the "SelectAll" checkbox should automatically become checked. This serves as an indicator that all items are currently selected.

2. **Pre-checked State Based on Value**: If the `Value` parameter includes all items, the "SelectAll" checkbox should be checked when the dropdown is first opened. This not only indicates that all items are selected but also allows for easier mass deselection.

@bholbrook, do you have any thoughts on these suggestions?

**Comment by hakenr** [comment]
Found an example with the behavior described above: https://mdbootstrap.com/docs/standard/extended/multiselect/

**Comment by hakenr** [comment]
cc @vaclavek

**Comment by bholbrook** [comment]
@hakenr I would be comfortable implementing these changes. Stay tuned for a PR shortly.
