### ISSUE TITLE
[Docs] Search suggestion is not working after selecting existing text with mouse and entering new query

### ISSUE THREAD

**Issue by crdo** [havit/Havit.Blazor#645]
1. Insert text query to search in docs
2. Select some of the suggestion with enter
3. Select existing text with mouse
4. Remove with backspace and write new query
5. No suggestion appears
<img width="1361" alt="image" src="https://github.com/havit/Havit.Blazor/assets/1410922/7826b308-9466-4eb3-a806-5baaddde322a">

**Comment by hakenr** [comment]
I believe you were hitting the #702.
