### ISSUE TITLE
Feature Request : Is posible to add the "AllowFiltering" parameter to HxSelect?

### ISSUE THREAD

**Issue by LiveIsLive** [havit/Havit.Blazor#650]
The behavior is the same as the "AllowFiltering" parameter in the HxMultiSelect .

**Comment by crdo** [comment]
HxSelect is a native browser input where such a modification is impossible.

**Comment by hakenr** [comment]
(However you can start typing on keyboard when you open the select and most browsers will jump to the corresponding item.)
