### ISSUE TITLE
Unable to use components that include JavaScript modules on an MVC site

### ISSUE THREAD

**Issue by flamewave** [havit/Havit.Blazor#665]
I'm in the process of slowly updating an old MVC site over to Blazor (server) and have been using the Havit.Blazor components in the conversion. However, I ran into a fairly major issue with this when attempting to use any of the Havit components that include a JavaScript module (i.e. modal, autosuggest, etc). As soon as the Blazor server attempts to dynamically load the component's JavaScript module file, I get the following error:

Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: https://<localhostPath>/<viewFolderName>_content/Havit.Blazor.Components.Web.Bootstrap/HxAutosuggest.js?v=2.0.0%2B38e62b7e03b8f1fb69f3fc3f937482d9e769dcd7

Note that <localhostPath> and <viewFolderName> would be replaced by their respective values.
When I browse to where the file is supposed to be (i.e. remove the <viewFolderName> part), I can see that the JS module file is there. But for some reason, the <viewFolderName> part is being added (without a trailing slash). So for example, if the component was being used on a view under the location (from root of site) Views/MyCustomView/Index.cshtml, then it would be attempting to load the module file using the following URL:
https://<localhostPath>/MyCustomView_content/Havit.Blazor.Components.Web.Bootstrap/HxAutosuggest.js?v=2.0.0%2B38e62b7e03b8f1fb69f3fc3f937482d9e769dcd7

I think this may be caused by the use of the "./" prefix you are using in the path to load the module in the JSRuntimeExtensions.ImportHavitBlazorBootstrapModuleAsync method.

I tried to reproduce this with a new MVC project, but was unable to, so this appears to be something specific to the project setup in the old MVC project I am converting. Note that if I add my own component with a JS module reference (either embedded into another project referenced or within the web project itself), that works just fine, so it appears to only be an issue with the embedded JS modules in your library.

**Comment by hakenr** [comment]
I think you are struggling with "Application base path", check the Blazor doc here:
https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-8.0&tabs=visual-studio#app-base-path

Also check the specifics for MVC integration here:
https://github.com/dotnet/aspnetcore/issues/43191#issuecomment-1212156106

**Comment by flamewave** [comment]
Adding the tag: `<base href="/" />` to the header was what was missing. Thanks for the help.
