### ISSUE TITLE
[HxInputTags] support for input-groups (incl. templates)

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#68]
...e.g. to be able to set filtering mode (ALL / ANY).
![image](https://user-images.githubusercontent.com/12828888/149966078-654b5b53-7817-40c5-a24f-6e99f43806ab.png)

**Comment by Harvey1214** [comment]
https://dev.azure.com/havit/DEV/_git/002.HFW-HavitBlazor/commit/e1b475fa60c16a3bf2e8c9eb09b90307d856ceea

**Comment by hakenr** [comment]
@Harvey1214 Implementation should be aligned with current input-groups implementation:
* missing `InputGroupCssClass` parameter
* the wrapping HTML element for `input-group` class should be `span` (or is there any reason for not being?)
