### ISSUE TITLE
[HxGrid] Supporting data loading from outside

### ISSUE THREAD

**Issue by Arnnes** [havit/Havit.Blazor#682]
I have a scenario where I need to prepare data outside of HxGrid before passing it to the Data Provider. This results in no progress indication being displayed, and I have to address it using the following hack:

```
@if (_dataLoaded)
{
	<HxProgressIndicator InProgress="@(!_dataLoaded)" />
}
else
{
	<HxGrid ...>
}
```

Is it possible to add support for displaying placeholder rows based on a condition passed from the parent component?

**Comment by hakenr** [comment]
BTW, I just found a forgotten `InProgress` parameter of the `HxGrid` which might help you to achieve what you wanted.
