### ISSUE TITLE
[HxAccordion] [Possible Bug] Accordion Collapses When It Should Stay Open

### ISSUE THREAD

**Issue by chobo2** [havit/Havit.Blazor#685]
Version: 4.3.4
Blazor 8 Interactive Server

Issue: When I have an autosuggest / search box in an accordion and a value is chosen, the accordion collapses for some reason . 

In this example when you chose "bob" either via "enter key" or with mouse it will collapse on the first time of choosing a value. If you choose "Jim" for the first time it won't, though in my real code it seems to be all choice so not sure why the difference here. 

Attached is a video.

What is interesting is you will see the container disappear but if you look at the carrot you will see it is in the "up/open" poistion and though I did not put it in the video when I did display "expandedItemId " on the page it never changes it always stays as "1".

```
@page "/"

<PageTitle>Home</PageTitle>

<h1>Hello, world!</h1>

Welcome to your new app.

<Component @rendermode="RenderMode.InteractiveServer" />
```

Component.razor
```
<HxAccordion @bind-ExpandedItemId="@expandedItemId" CssClass="mb-3">
	<HxAccordionItem Id="1">
		<HeaderTemplate>Accordition Item 1 (Id="1") with LazyLoaded content</HeaderTemplate>
		<BodyTemplate>
			<HxAutosuggest Label="Employee"
						   Placeholder="Start typing to search by name"
						   TItem="EmployeeDto"
						   TValue="int?"
						   @bind-Value="@selectedEmployeeId"
						   DataProvider="ProvideSuggestions"
						   ValueSelector="employee => employee.Id"
						   TextSelector="employee => employee.Name"
						   ItemFromValueResolver="ResolveAutosuggestItemFromValue">
				<EmptyTemplate>
					<span class="p-2">Couldn't find any matching employee</span>
				</EmptyTemplate>
			</HxAutosuggest>
		</BodyTemplate>
	</HxAccordionItem>
</HxAccordion>

@code
{
	private string expandedItemId = "1"; // you can se the initial value here, if binding to ExpandedItemId

	private int? selectedEmployeeId = 1;

	private async Task<AutosuggestDataProviderResult<EmployeeDto>> ProvideSuggestions(AutosuggestDataProviderRequest request)
	{
		var matchingEmployees = new List<EmployeeDto>()
		{
			 new EmployeeDto { Id =1 , Name = "Jim"},
			 new EmployeeDto { Id =2, Name = "Bob"}
		};

		return new AutosuggestDataProviderResult<EmployeeDto> { Data = matchingEmployees };
	}

	private async Task<EmployeeDto> ResolveAutosuggestItemFromValue(int? value)
	{
		if (value is null)
		{
			return null;
		}

		return new EmployeeDto();
	}

	public class EmployeeDto
	{
		public string? Name { get; set; }
		public int Id { get; set; }
	}
}
```

https://github.com/havit/Havit.Blazor/assets/321584/5d15228d-8863-41d5-a498-47bc29d0fd4c

**Comment by chobo2** [comment]
@hakenr 

Hey, could you please let me know if this is a bug or not? I understand if it is a bug and there is no time to fix it at this time. I just don't want to go ahead and rewrite this control myself and find out I was doing something wrong.

Thanks

**Comment by hakenr** [comment]
@chobo2 This seems to be a bug. We need some time to investigate deeper and confirm.

**Comment by chobo2** [comment]
blazor

> @chobo2 This seems to be a bug. We need some time to investigate deeper and confirm.

Okay great, thanks for getting back to me. I will hold off then trying roll mine own out.

**Comment by chobo2** [comment]
> @chobo2 This seems to be a bug. We need some time to investigate deeper and confirm.

Hey, let me know if you need more information or videos to reproduce the bug. 

I am sure you're busy so if this something that is not high priority for you just let me know, so I can plan accordingly as probably by Mid-January I will have to roll out my own if no solution is finished.

Thanks

**Comment by chobo2** [comment]
I tried the latest version and the fix seems to have solved the problems, thanks @alexax578 and @hakenr
