### ISSUE TITLE
[HxSidebar] Add support for tooltips on items & display dropdown on hover when collapsed

### ISSUE THREAD

**Issue by alexax578** [havit/Havit.Blazor#686]
I want to be able to set a tooltip text to individual sidebar items.

- The tooltip should be visible only when I hover on the item when the sidebar is collapsed.
- The tooltip can stay visible when I open the submenu with child navigation items but should appear only when I hover over the parent icon.

In my scenario, tooltips are only relevant on the first-level parent sidebar items.

**Comment by hakenr** [comment]
(During the implementation, the scope was widened to include "dropdown on hover".)
