### ISSUE TITLE
HXInput labeltemplate not hidden when input is marked as hidden

### ISSUE THREAD

**Issue by bluisanajmr** [havit/Havit.Blazor#696]
I have an HXinputNumber and custom label template setup like this.   When the projectmodel.IsBudgetEstimate is set to false the input is hidden but the label is still visible.  How can the label and input both be hidden conditionally? 

<HxInputNumber @bind-Value="@projectmodel.TimeEstimate" Placeholder="Project Time Estimate." hidden="@(!projectmodel.IsBudgetEstimate)">
    <LabelTemplate>
        Time Estimate
                <HxTooltip Placement="TooltipPlacement.Right" Text="The estimated total amount of hours estimated for this project. If left blank reports and dashboards won't dipslay %Time completed for this project.'">
                    <Havit.Blazor.Components.Web.HxIcon Icon="BootstrapIcon.QuestionCircle" />
                </HxTooltip>
    </LabelTemplate>
</HxInputNumber>

![image](https://github.com/havit/Havit.Blazor/assets/135136836/9c5d1a8f-e004-4589-81a6-d65f9fccc07c)

![image](https://github.com/havit/Havit.Blazor/assets/135136836/9649cddd-da66-4bf1-85cd-beb22e4c33ad)

**Comment by hakenr** [comment]
Not sure, what you want to achieve, but I would go for simple `if`:
```razor
@if (projectModel.IsBudgetEstimate)
{
   <HxInputNumber ... />
}
```
If you absolutely need to have the value in hidden form field (Static Server Rendering?), then try something like:
```razor
<HxInputNumber CssClass="@(projectmodel.IsBudgetEstimate : null ? "d-none")" hidden="@(!projectmodel.IsBudgetEstimate)" ... />
```

**Comment by bluisanajmr** [comment]
Thanks Hakenr, 

I can get away with a simple if to hide the input.  This just seems like a minor bug to me from the HxInput components.  If you build the component with the label specified in the input like below the label will be hidden along with the input. 

 <HxInputNumber Label="id" @bind-Value="@projectmodel.Id" hidden="true" />

but if you specify a labeltemplate instead of specifying the label in the input component the label will be displayed if the input is hidden. 

<HxInputNumber Label="id" @bind-Value="@projectmodel.Id" hidden="true" >
LabelTemplate>
                    Id
</LabelTemplate>
</HxInputNumber>

I can't think of a scenario when you would ever want to display a label for an input without actually displaying the input but maybe there is a use case. 

Thanks again for the quick responses and solutions.

**Comment by hakenr** [comment]
I just tried to add the `hidden="true"` to a basic `HxInputNumber` demo with plain `Label` and the `Label` still renders:
![image](https://github.com/havit/Havit.Blazor/assets/12828888/e55030f5-188c-463f-91f0-509d80b09fae)

The behavior is consistent in both cases, we just pass the `hidden` attribute to the underlying HTML element (attribute splatting).
