### ISSUE TITLE
[HxMultiSelect] InputGroupStartTemplate and InputGroupEndTemplate inner button clicks don't function

### ISSUE THREAD

**Issue by bholbrook** [havit/Havit.Blazor#699]
When you use either a ```InputGroupStartTemplate``` or ```InputGroupEndTemplate``` element within the ```HxMultiSelect``` and it contains functionality such as an ```HxButton``` (or similar I'd imagine) they don't get clicked, instead the main multi-select dropdown is toggled.
Instead, the dropdown click event should only be triggered if the main input is clicked, not either template.

**Comment by hakenr** [comment]
Have you tried setting OnClickStopPropagation="true" for those buttons? (Or @onclick:stopPropagation for HTML elements.) Your click event is propagating to the enclosing div that contains the data-bs-toggle attribute for the selection dropdown.

If that's the case, could you please provide us with a simplified code example that we can use to reproduce the issue?
