### ISSUE TITLE
Layout components? Container/Row/Col/...

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#7]
Do we want to cover components for layout?

something similar to https://blazorstrap.io/layout

cc @crdo

**Comment by robertmclaws** [comment]
I never really understood what the point was. Using a div is fewer characters, and also doesn't requiring spinning up and managing a class of object to maintain state on. Not assuming that my opinion matters here, but I personally think it's a waste of time.

**Comment by hakenr** [comment]
Putting this down, at least for now.
