### ISSUE TITLE
Add configuration to HxInputDate to support Jalali (Persian) calendar

### ISSUE THREAD

**Issue by zoha-shobbar** [havit/Havit.Blazor#701]
please add some configuration to use  Jalali (Persian) calendar to HxInputDate , this team did it before, https://components.bitplatform.dev/components/datepicker . it will be grate if you add this ability to HxCalendar.

**Comment by hakenr** [comment]
Duplicates #633.

(This is currently beyond our scope. We may prioritize this request if we secure sponsorship funding or if we can provide the feature as a commercial consulting service.)
