### ISSUE TITLE
[HxAuttoSuggest/Search] Sometimes does not open suggestion list

### ISSUE THREAD

**Issue by chobo2** [havit/Havit.Blazor#702]
Hi

I am struggling to recreate this problem on a controlled app, but in my real app I am getting in an issue where the dropdown-menu just does not open up.

For instance, I am seeing in the dom right now

```
<div class=hx-autosuggest-input-wrapper>
   <input..... />
  <div class="hx-autosuggest-input-incon > </div>
<div class="dropdown-menu **style**> 
    <button class="dropdown-item text-truncate hx-atuosuggest-item-focused type="button" tabindex"-1"< </button>
    ..... more of them
</div>

</div>
```
From what I have seen, it for some reason gets tripped out and generates the list of dropdown-menus but does not add the styling on that class to actually show the items.

I have to click in and out of the box then they will all appear.

To me it seems like it thinks you're clicking out of the box, and it is trying to hide the dropdown list when in reality I have not left the box yet.

Any ideas on how this could happen?

**Comment by chobo2** [comment]
@hakenr 

I was able to get it to happen once in a test project I made though in my appliation it happens more frequently but this best I can do for now.

I thought it could be because of switching between different controls and multiple same controls on the page and then going back, but it seems to just happen randomly.

In my real application I tried just 1 autocomplete on the page by itself I tried a combination of search boxes and auto complete on the same page.


```
@page "/"

<PageTitle>Home</PageTitle>

<h1>Hello, world!</h1>

Welcome to your new app.


<Component1 @rendermode="RenderMode.InteractiveServer" />




<HxAccordion @bind-ExpandedItemId="@expandedItemId" CssClass="mb-3">
	<HxAccordionItem Id="1">
		<HeaderTemplate>Accordition Item 1 (Id="1") with LazyLoaded content</HeaderTemplate>
		<BodyTemplate>
			<HxAutosuggest Label="Employee"
						   Placeholder="Start typing to search by name"
						   TItem="EmployeeDto"
						   TValue="int?"
						   @bind-Value="@selectedEmployeeId"
						   DataProvider="ProvideSuggestions"
						   ValueSelector="employee => employee.Id"
						   TextSelector="employee => employee.Name"
						   ItemFromValueResolver="ResolveAutosuggestItemFromValue">
				<EmptyTemplate>
					<span class="p-2">Couldn't find any matching employee</span>
				</EmptyTemplate>
			</HxAutosuggest>

			<HxAutosuggest Label="Employee"
						   Placeholder="Start typing to search by name"
						   TItem="EmployeeDto"
						   TValue="int?"
						   @bind-Value="@selectedEmployeeId"
						   DataProvider="ProvideSuggestions"
						   ValueSelector="employee => employee.Id"
						   TextSelector="employee => employee.Name"
						   ItemFromValueResolver="ResolveAutosuggestItemFromValue">
				<EmptyTemplate>
					<span class="p-2">Couldn't find any matching employee</span>
				</EmptyTemplate>
			</HxAutosuggest>


			<HxButton Color="ThemeColor.Primary" Text="Test" OnClick="TestClick" />
		</BodyTemplate>
	</HxAccordionItem>
</HxAccordion>

<HxCheckbox @bind-Value="isChecked" Text="A simple checkbox" Label="Label" />

@code
{
	private string expandedItemId = "1"; // you can se the initial value here, if binding to ExpandedItemId
	bool isChecked;
	private int? selectedEmployeeId = 1;

	private List<EmployeeDto> matchingEmployees = new List<EmployeeDto>()
		{
			 new EmployeeDto { Id =1 , Name = "Jim"},
			 new EmployeeDto { Id =2, Name = "Bob"},
			new EmployeeDto { Id = 1, Name = "John Smith" },
			new EmployeeDto { Id = 2, Name = "Jane Johnson" },
			new EmployeeDto { Id = 3, Name = "Michael Williams" },
			new EmployeeDto { Id = 4, Name = "Emily Jones" },
			new EmployeeDto { Id = 5, Name = "David Brown" },
			new EmployeeDto { Id = 6, Name = "Sophia Davis" },
			new EmployeeDto { Id = 7, Name = "Matthew Miller" },
			new EmployeeDto { Id = 8, Name = "Olivia Wilson" },
			new EmployeeDto { Id = 9, Name = "Christopher Moore" },
			new EmployeeDto { Id = 10, Name = "Emma Taylor" },
			new EmployeeDto { Id = 91, Name = "John Smithson" },
			new EmployeeDto { Id = 92, Name = "Jane Doe" },
			new EmployeeDto { Id = 93, Name = "Michael Brown" },
			new EmployeeDto { Id = 94, Name = "Emily Davis" },
			new EmployeeDto { Id = 95, Name = "David Johnson" },
			new EmployeeDto { Id = 96, Name = "Sophia Wilson" },
			new EmployeeDto { Id = 97, Name = "Matthew Taylor" },
			new EmployeeDto { Id = 98, Name = "Olivia Miller" },
			new EmployeeDto { Id = 99, Name = "Christopher Jones" },
			new EmployeeDto { Id = 100, Name = "Emma Taylorson" }
		};

	private void TestClick()
	{
		selectedEmployeeId = null;
	}

	private async Task<AutosuggestDataProviderResult<EmployeeDto>> ProvideSuggestions(AutosuggestDataProviderRequest request)
	{

		var matching = matchingEmployees.Where(x => x.Name.ToLower() == request.UserInput.ToLower());
		await Task.Delay(500);
		return new AutosuggestDataProviderResult<EmployeeDto> { Data = matching };
	}

	private async Task<EmployeeDto> ResolveAutosuggestItemFromValue(int? value)
	{
		if (value is null)
		{
			return null;
		}

		return new EmployeeDto();
	}

	public class EmployeeDto
	{
		public string? Name { get; set; }
		public int Id { get; set; }
	}
}
```


https://github.com/havit/Havit.Blazor/assets/321584/82587550-4536-4298-a65d-5ea76500c647

**Comment by hakenr** [comment]
Thanks for recording the video.
Using the information provided I'm now able to reproduce the issue even on our basic demo:
![2023-12-13_21-26-35](https://github.com/havit/Havit.Blazor/assets/12828888/2cb70b40-bdfe-4d65-b8f4-3fe4790125e3)
1. Click the input and type "jon" (dropdown opens).
2. Select the typed text with mouse (dropdown closes - probably should not close in this case).
3. Type new text, e.g. "bob" => suggestion should appear, but the dropdown remains closed.

**Comment by hakenr** [comment]
The cause:
- we track `clickIsComing` (#572) with `mousedown` and `mouseup` events of the `input`
- during the selection of the content, the `mouseup` is not received when the mouse button is release outside the input
- the `clickIsComing` remains `true` and prevents opening the dropdown

The fix (to test):
- in addition to `mouseup` we will also listen to `mouseleave` and set `clickIsComing` to `false`

**Comment by hakenr** [comment]
@chobo2 I will publish `v4.3.6-pre1` to NuGet in few minutes.
Give it a try if it fixes the issue and please let me know.

**Comment by chobo2** [comment]
> @chobo2 I will publish `v4.3.6-pre1` to NuGet in few minutes. Give it a try if it fixes the issue and please let me know.

Great, I will try it on my test application and once it passes that and a non "pre" is released will test in my main application.

**Comment by chobo2** [comment]
Just tried it in my sample application and in my main application, so far I am no longer seeing the issue.  I think it is fixed, if I find it happening again I will try to recreate it and let you know.

Thanks, @hakenr
