### ISSUE TITLE
Non-english descriptions for methods in Havit.Linq namespace

### ISSUE THREAD

**Issue by oscar230** [havit/Havit.Blazor#709]
# Non-english descriptions for methods in Havit.Linq namespace
Methods `Havit.Linq.WhereIf`, `Havit.Linq.FullOuterJoin`, `Havit.Linq.Chunkify` and `Havit.Linq.ContainsAll` have non-english descriptions.

## Version:
```csharp
#region Assembly Havit.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null
// C:\Users\REDACTED\.nuget\packages\havit.core\2.0.28\lib\net6.0\Havit.Core.dll
// Decompiled with ICSharpCode.Decompiler 7.1.0.6543
#endregion
```

## Example:
```csharp
        //
        // Summary:
        //     Indikuje, zda obsahuje kolekce všechny položky jiné kolekce.
        //
        // Parameters:
        //   source:
        //     Kolekce, v níž ověřujeme existenci hodnot.
        //
        //   lookupItems:
        //     Hodnoty, jejichž existenci ověřujeme v kolekci.
        //
        // Returns:
        //     True, pokud source obsahuje všechny prvky lookupItems.
        public static bool ContainsAll<T>(this IEnumerable<T> source, IEnumerable<T> lookupItems)
        {
            return !lookupItems.Except(source).Any();
        }
```

## Expected behavior
English comments.

## Note
Thanks for a great library, I use it every day. ⭐
Veselé Vánoce! 🎄

**Comment by oscar230** [comment]
Suggested labels [good first issue](https://github.com/havit/Havit.Blazor/labels/good%20first%20issue) and [documentation](https://github.com/havit/Havit.Blazor/labels/documentation).

**Comment by crdo** [comment]
@oscar230 I think this belongs to https://github.com/havit/HavitFramework rather than here as those methods are part of Havit.Core. 

HAVIT Framework has been originally developed for our purposes only (justifying the Czech comments) and open-sourced later.

We might consider to programatically translate all the comments to english as there will be a lot more that just those mentioned by you in this issue.

**Comment by hakenr** [comment]
Although this is a tiny separate NuGet package (`Havit.Core`) with source code in separate repository (https://github.com/havit/HavitFramework), I agree this should be in English as it is referenced from Havit.Blazor packages.

We will probably translate all the comments in the  https://github.com/havit/HavitFramework repo, but for now, lets start with `Havit.Core` not to include Czech comments in Havit.Blazor packages.

**Comment by oscar230** [comment]
> @oscar230 I think this belongs to https://github.com/havit/HavitFramework rather than here as those methods are part of Havit.Core.
> 
> HAVIT Framework has been originally developed for our purposes only (justifying the Czech comments) and open-sourced later.
> 
> We might consider to programatically translate all the comments to english as there will be a lot more that just those mentioned by you in this issue.

Thanks @crdo I will make sure to remember that for future issues. 🎉

> Although this is a tiny separate NuGet package (`Havit.Core`) with source code in separate repository (https://github.com/havit/HavitFramework), I agree this should be in English as it is referenced from Havit.Blazor packages.
> 
> We will probably translate all the comments in the https://github.com/havit/HavitFramework repo, but for now, lets start with `Havit.Core` not to include Czech comments in Havit.Blazor packages.

Cool, thanks @hakenr ⭐
