### ISSUE TITLE
[HxSidebar] Toggler is not visible when using ResponsiveBreakpoint.None

### ISSUE THREAD

**Issue by alexax578** [havit/Havit.Blazor#710]
When I use `HxSidebar` with ResponsiveBreakpoint set to **SidebarResponsiveBreakpoint.None** the sidebar toggler disappears.
![image](https://github.com/havit/Havit.Blazor/assets/37944469/5ada1b28-22a4-4c66-8175-95ba38ff3975)

**Comment by crdo** [comment]
Moved the d-none to CSS isolation so it can be overloaded by the responsive utility class.
