### ISSUE TITLE
[HxGrid] Add sticky header and scrollbar

### ISSUE THREAD

**Issue by leonardopugliese** [havit/Havit.Blazor#712]
Is it possible in the HxGrid to fix the header at the top when you set a fixed height to scroll as in the following image?

![Schermata del 2023-12-22 17-22-23](https://github.com/havit/Havit.Blazor/assets/96176972/1dfe042f-9c6f-4396-9393-92e10c9f84d0)

Basically I would like what you have demonstrated here but applied to the table tboby
https://havit.blazor.eu/components/HxGrid#InfiniteScroll

Happy Holidays

**Comment by crdo** [comment]
@leonardopugliese I have added examples to the TestApp project with sticky header and first column pivot in https://github.com/havit/Havit.Blazor/commit/f90c5352de9959148b62b57545038661011c14a7
If it proves to be a stable across the browsers, we will add it to the docs in the future.

**Comment by crdo** [comment]
Btw. @alexax578 and @Arnnes you could be interested in this. The solution proposed here is way more elegant than the one we have in 176.BT2 projects.

**Comment by leonardopugliese** [comment]
It seems to work correctly as desired. The mode WITHOUT InfiniteScroll but with pagination also works well (I wanted this mode too).

**Comment by crdo** [comment]
Closing for now. The first demo of sticky header will be on HxListLayout that wraps HxGrid in the next release.
