### ISSUE TITLE
[HxInputTags] To add TagCssClass parameter

### ISSUE THREAD

**Issue by crdo** [havit/Havit.Blazor#72]
To be able to fulfil some design requirements, I need to have a possibility to add custom css class to each Tag, including the AddTag button.

**Comment by hakenr** [comment]
Considering adding `HxBadge.Settings` and `HxInputTags.TagBadgeSettings`. This will allow setting not only CssClass but also `Color`, `TextColor` and `Type` + will bring support for `HxInputTag.Defaults.TagBadgeSettings.CssClass` out of the box.

(The only cons is that it leaks the implementation detail - that we use HxBadge for individual tags - we won't be able to change that later without breaking change.)

**Comment by hakenr** [comment]
commit 270bcef4403c89b37a5e46c233b933225392d73a
