### ISSUE TITLE
[HxGrid][HxAutosuggest] Suggestions and sticky header

### ISSUE THREAD

**Issue by leonardopugliese** [havit/Havit.Blazor#748]
HI! As you can see from the attached image, if I insert an HxAutosuggest  and an HxGrid with sticky header there are display problems (z-index?)

![Screenshot 2024-02-04 195026](https://github.com/havit/Havit.Blazor/assets/96176972/c8722d6e-3beb-44b1-8f41-8602c72f7387)

**Comment by crdo** [comment]
This is not something in our scope. You will always find combinations of HTML that does not work together in its default setup. The `.dropdown-menu` has CSS variable setting its `z-index`. In this case, you simply set higher value that you use for the sticky header, or vice versa (set the sticky header z-index lower that the `.dropdown-menu`).
