### ISSUE TITLE
[HxGrid] Data is never applied or loaded - DataProvider does not appear to be called at any point in component lifecycle

### ISSUE THREAD

**Issue by eklein217** [havit/Havit.Blazor#758]
Using sample code below:
![image](https://github.com/havit/Havit.Blazor/assets/160776335/a4ac1197-ca8f-4fc3-aaf5-e52740385230)

The breakpoint on line 22 is never hit. This leads to a grid which is permanently loading data. There does not appear to be a way to refresh the data manually.

![image](https://github.com/havit/Havit.Blazor/assets/160776335/f37f4f8a-4cd3-4f3f-83ff-6569d98bbc7f)

**Comment by hakenr** [comment]
I think this is a tooling issue (Visual Studio). The Blazor debugging is still a bit bumpy.
Try to run the code without debugging (Ctrl+F5), or without the breakpoint in `GetGridData` method.

**Comment by eklein217** [comment]
@hakenr Appears the same. I do want to point out that my problem here is not with the debugging (though I would hope that debugging would be supported for all components), but the actual grids are failing to load from their data source. I've tried multiple versions of the library, including the most recent. Is there something wrong with my code? It's pulled (almost) directly from the docs.

**Comment by hakenr** [comment]
I just double-checked the scenario you are presenting and I'm unable to reproduce your issue.
Can you provide us with a minimal repro project (GitHub repo) where the issue reproduces?
Thank you

**Comment by eklein217** [comment]
@muipsd That's my current configuration as well.

**Comment by eklein217** [comment]
@hakenr Apologies for the delay. https://github.com/evklein/HavitGridRenderBugFixRepo/ Please check out this repository to see the error in action.

**Comment by hakenr** [comment]
Thanks for preparing the repro. See the PR https://github.com/evklein/HavitGridRenderBugFixRepo/pull/1 for fixes need.
1. You have to enable the interactivity for the app/components. See https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0
2. The `TotalCount` in `DataProvider` response has to have a correct value.

**Comment by eklein217** [comment]
@hakenr Appreciate the help! Might I suggest adding a note on your [Getting Started page](https://havit.blazor.eu/)? Doesn't seem to be any setup difference between wasm and server rendered apps listed.
