### ISSUE TITLE
[HxModal] Dialog Can be Moving in screen 

### ISSUE THREAD

**Issue by GeeSuth** [havit/Havit.Blazor#76]
Hey, 
I think be a good option to make dialog moving like 
https://jqueryui.com/dialog/#default

**Comment by hakenr** [comment]
@crdo, this is probably not supported by Bootstrap 5 Modal. Do we want to investigate custom options?

**Comment by crdo** [comment]
If you need your content visible when displaying some modal-like component use a Offcanvas.

**Comment by hakenr** [comment]
Summary: We currently do want to use pure Bootstrap 5 Modal and the draggability will be supported as far as Bootstrap itself will support it.
