### ISSUE TITLE
[HxAccordion] Accordion not closing when setting rendermode InteractiveServer in <Routes /> component

### ISSUE THREAD

**Issue by AlexGallego7** [havit/Havit.Blazor#762]
I'm working with a .NET 8 Blazor Server App. I need to set the render mode InteractiveServer in the Routes component but at the time of implementing this, the HxAccordion opens itself fine but does not close when clicking again.

`<Routes @rendermode="InteractiveServer" />`

I have also tried to turn off the pre-render with:

`<Routes @rendermode="new InteractiveServerRenderMode(prerender: false)" />`

but this seems to make the bootstrap css to disappear.

Is this a known issue or am I just missing something?

Thanks in advance!

**Comment by hakenr** [comment]
@AlexGallego7 I'm not able to reproduce the issue. Can you provide us with a simple reproduction repro, where I can see the issue?

**Comment by AlexGallego7** [comment]
My mistake, there were hidden references to different versions of bootstrap which caused strange issues. Closing this one.
