### ISSUE TITLE
HxModal Scrolling disabled after modal closed using browser back button

### ISSUE THREAD

**Issue by hgirma** [havit/Havit.Blazor#768]
I'm experiencing an issue with HxModal. When a modal is open and the user navigates away using the browser back button, scrolling on the rest of the page becomes disabled. This persists until the user refreshes the entire site.

You can experience it on the help page

https://havit.blazor.eu/components/HxModal

click open any modal and hit the browser back button

**Comment by hakenr** [comment]
Duplicates #110, waiting for fix in Bootstrap.
