### ISSUE TITLE
[HxInputDate] - Possible add time picker

### ISSUE THREAD

**Issue by petrkasnal** [havit/Havit.Blazor#81]
Hello, thank you for your perfect framework. I have question about input date. Is possibility add time picker or can you tell me how i can do it easiest way? 

Thank you very much :)

**Comment by hakenr** [comment]
Hi @petrkasnal, you can use the [`HxInputDate`](https://havit.blazor.eu/components/HxInputDate) component.
See the documentation for the usage. You can set `CalendarIcon="BootstrapIcon.Calendar"` if you want to show the calendar icon.
Is it what you need?

**Comment by petrkasnal** [comment]
Hi @hakenr, thank you for fast response. No i mean if is any posibility how use HxInputDate with time picker or how can i do it easiest way with your component. I mean something like this 
![image](https://user-images.githubusercontent.com/90285874/155095420-fc058b5f-fc64-4476-a3eb-9e0b266d9d58.png)


Thank you

**Comment by hakenr** [comment]
Aah, I see.
It is currently not prepared as built-in component, you can put together your own using the HxCalendar and HxDropdown.
The request for time-picker is already in backlog - #26.

**Comment by petrkasnal** [comment]
Ok thank you very much.

**Comment by hakenr** [comment]
@petrkasnal Feel free to submit a PR with such a component. ;-)
Your contribution will be more than welcome.
