### ISSUE TITLE
[HxSidebarItem] Allow navigation on expandable items

### ISSUE THREAD

**Issue by crdo** [havit/Havit.Blazor#812]
In some rare cases, after clicking on parent `SidebarItem`, we need to do navigation + expanding child nodes.
In Bootstrap, handling of href on parent `a` is prevented, so I suggest to add `OnClick` parameter as a work-around.

**Comment by hakenr** [comment]
@crdo Instead of `OnClick` (extending the API and allowing all the possible misinterpretations of the behavior), I tried to make the `Href` link work by executing the navigation action manually when needed.

I will publish the proposed solution in a Havit.Blazor prerelease and let's give it a try.
