### ISSUE TITLE
[HxProgressBar] The progress bar is broken when the range differs from 0 to 100

### ISSUE THREAD

**Issue by CryptKat** [havit/Havit.Blazor#813]
Commit 1e7f5dfb2a34d039c00901dc4c8dfabdf334bf46 broke the progress bar when the range differs from 0 to 100.
Take a look at the [documentation](https://havit.blazor.eu/components/HxProgressBar#scale) section
![image](https://github.com/havit/Havit.Blazor/assets/21363661/950d9273-3450-4fae-9f01-c37c154b7f1b)

The `GetNormalizedValue` method needs to be reverted to the previous version.

**Comment by hakenr** [comment]
@CryptKat Thanks for reporting this. Somehow it slipped in when using AI to improve the English in our code and documentation. 🙄
