### ISSUE TITLE
[HxToast] Crash during render tree build when using a high-contrast ThemeColor

### ISSUE THREAD

**Issue by jolaquai** [havit/Havit.Blazor#816]
Title. Repo link with minimal sample that reproduces the issue can be found here: [jolaquai/HxToastDangerMessageProblem](https://github.com/jolaquai/HxToastDangerMessageProblem)

While I have no idea about the nitty-gritty of Blazor or Component development, wading through the Blazor and Havit.Blazor sources showed that the exception comes from [`Havit.Blazor.Components.Web.Bootstrap.HxToast.BuildRenderTree(RenderTreeBuilder)`](https://github.com/havit/Havit.Blazor/blob/a8f4c0abb7a209008c4b31852774c19347317585/Havit.Blazor.Components.Web.Bootstrap/Toasts/HxToast.cs#L131) because for `ThemeColor.Danger`, [`HasContrastColor()` returns `true`](https://github.com/havit/Havit.Blazor/blob/a8f4c0abb7a209008c4b31852774c19347317585/Havit.Blazor.Components.Web.Bootstrap/Toasts/HxToast.cs#L190).

This causes `BuildRenderTree(RenderTreeBuilder)` to attempt to [write `data-bs-theme="dark"`](https://github.com/havit/Havit.Blazor/blob/a8f4c0abb7a209008c4b31852774c19347317585/Havit.Blazor.Components.Web.Bootstrap/Toasts/HxToast.cs#L131) into the "last non-attribute frame" (which is currently a `RenderTreeFrameType.Region`), which obviously fails [`Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AssertCanAddAttribute()`](https://github.com/dotnet/aspnetcore/blob/1e79c9bdc0d2062eaea6e08e476765023bf5fc3a/src/Components/Components/src/Rendering/RenderTreeBuilder.cs#L715-L722).

**Comment by hakenr** [comment]
@crdo Fixed the crash, but probably needs some more work on visual result:
![image](https://github.com/havit/Havit.Blazor/assets/12828888/7e3a691f-3ba1-4173-ac5e-48b265927695)

**Comment by hakenr** [comment]
@jolaquai Thanks for reporting the issue. We were able to reproduce the crash and will fix it for the next release.
