### ISSUE TITLE
[HxInputDate] Cursor shape for CalendarIcon

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#82]
Currently displayed as `text` as there is the `pointer-events: none;` to handle drop-down interactions.
There should be standard cursor for the icon.

**Comment by Harvey1214** [comment]
https://dev.azure.com/havit/DEV/_git/002.HFW-HavitBlazor/commit/0cd70f9204b8726b3d317033bcb6d304fed7a8bd

**Comment by hakenr** [comment]
to be reviewed
