### ISSUE TITLE
[HxInputDate] - Inconsistent styling when used with InputGroups

### ISSUE THREAD

**Issue by DaleCam** [havit/Havit.Blazor#821]
When using input groups with the HxDateInput gives us inconsistent styling. I cant seem to get it looking right.
Below are 2 ways i tried, and the screenshot helps you to see the working HxInputText fields (the Note row) vs the not working HxDateInput (the Last Checked row). 
Here is what I have tried:
```razor
<div class="row mb-2">
    <label class="col-sm-3 pe-0">Last Checked</label>
    <div class="col-sm-9">
        <HxInputDate TValue="DateTime?" @bind-Value="ChangedLocation.DateLastCheckedUtc">
            <InputGroupEndTemplate>
                <span class="input-group-text" @onclick="() => ChangedLocation.DateLastCheckedUtc = null">
                    <i class="fas fa-times"></i>
                </span>
            </InputGroupEndTemplate>
        </HxInputDate>
    </div>
</div>
```
which ends up looking like this (HxInputText above it for comparison): 
![image](https://github.com/havit/Havit.Blazor/assets/4400216/c4b10790-d32c-49f4-9d7f-6057ecce9155)

and also this approach:
```razor
  <div class="row mb-2">
      <label class="col-sm-3 pe-0">Last Checked</label>
      <div class="col-sm-9">
          <div class="input-group">
              <HxInputDate TValue="DateTime?" @bind-Value="ChangedLocation.DateLastCheckedUtc" />
              <span class="input-group-text" @onclick="() => ChangedLocation.DateLastCheckedUtc = null">
                  <i class="fas fa-times"></i>
              </span>
          </div>
      </div>
  </div>
```
which is closer - but doesn't get the 100% width of the col like the HxInputText controls do:
![image](https://github.com/havit/Havit.Blazor/assets/4400216/2f22ffab-975c-422d-83bb-9e97d481368d)

Any ideas? 
Thank you!

**Comment by crdo** [comment]
There is quite extensive test page at BlazorAppTest/Pages/HxInputDateTest.razor where all the variants with InputGroups work just fine.
<img width="980" alt="image" src="https://github.com/havit/Havit.Blazor/assets/1410922/84eea4ad-2505-4151-b67a-f251d267319f">
If you still think there is an issue in our lib, please provide a minimal reproducing repo.

**Comment by DaleCam** [comment]
Thanks @crdo  - I didnt know about those tests - thats helpful thanks. Perhaps im on a different version of bootstrap or there is a subsequent style overriding the bootsrap. Ill do a bit more research and hopefully get back soon.
Thanks again for your reply!
