### ISSUE TITLE
File upload API

### ISSUE THREAD

**Issue by franky1017** [havit/Havit.Blazor#828]
Looking at the file upload component, I noticed this code block:

`		// WASM:
		//var accessTokenResult = await AccessTokenProvider.RequestAccessToken();
		//if (accessTokenResult.Status == AccessTokenResultStatus.Success)
		//{
		//	if (accessTokenResult.TryGetToken(out var token))
		//	{
		//		accessToken = token.Value;
		//	}
		//}
What is this used for? I am using the latest blazor web app (interactive auto mode) so I won't be sure my component is in server or client mode.

How is this access token used by the api end point? Do you have a sample implementation of such api?

Thanks!`

**Comment by franky1017** [comment]
NVM, I figured it out, it's a bearer token! Wish it was documented somewhere :-)

**Comment by hakenr** [comment]
Duplicates #820.
