### ISSUE TITLE
[HxInputDate] Not invoke field change

### ISSUE THREAD

**Issue by petrkasnal** [havit/Havit.Blazor#83]
Hi, i maybe found little bug in component hxinputdate. But i'm not really sure if it is a bug. When is value changed component only notification validation state changed but don't notification field changed. Normally is invoke field change too.  I use it for show/hide submit button. But maybe i haven't right and this is correct behaviour.

Thank you very much. :) 
![image](https://user-images.githubusercontent.com/90285874/155388646-88468da6-98f6-4a79-bfeb-975b8d1e9fed.png)

**Comment by hakenr** [comment]
Hi @petrkasnal,
the `ValueChanged` and `editContext.NotifyFieldChanged` callbacks are called from `CurrentValue` property setter (`InputBase`). These are called only when the value gets parsed correctly.
See https://github.com/dotnet/aspnetcore/blob/e0110ad9ea7e7ba646aff35832fedb5a588c6e1d/src/Components/Web/src/Forms/InputBase.cs#L72-L81

**Comment by petrkasnal** [comment]
@hakenr thank you for response. I understand, but when you insert correctly date and after write something incorrect like text the NotifyFieldChange isn't invoke. And i can't update property FormValid. I update button state on OnFieldChange, beacuse i found many tutorials on this. Or should i update FormValidate property another way? I tried update my property in event OnValidationStateChanged with method Validate But then it's called over and over again. Can you tell me how to do another way please?  When i try your HxInputNumber it works just like that. 

InputNumber: 
![image](https://user-images.githubusercontent.com/90285874/155556060-6a02266b-ac3a-4414-bad4-7cb11102d471.png)

InputDate
![image](https://user-images.githubusercontent.com/90285874/155556509-c74e7c78-00a2-409a-9e1e-7c9a7e423fcc.png)

**Comment by petrkasnal** [comment]
Aaah ok thank you very much :) I'll look forward to it.

I try it like this. But it's logicaly again call this method to infinite. How i can do it correctly please? Thank you
![image](https://user-images.githubusercontent.com/90285874/155584221-473bc6eb-f004-4759-81aa-ab686fcc89dc.png)

**Comment by petrkasnal** [comment]
> @jirikanda The bahavior of `HxInputNumber` and `HxInputDate` should be aligned.

Thank you very much :)

**Comment by hakenr** [comment]
Not fixed/verified yet, just a comment for my colleague. :-D

**Comment by jirikanda** [comment]
Implementation details:
* HxInputNumber sets value using the CurrentValueAsString property setter.
* HxInputDate sets value using the CurrentValue property setter.

The small difference can be hidden in [this line in CurrentValue setter](https://github.com/dotnet/aspnetcore/blob/47334b76dccb4eee3a886d8b974f589399f0b506/src/Components/Web/src/Forms/InputBase.cs#L74) - it means when the value is fixed (modified) to the previosly valid value, CurrentValue does not notify the change.

But when you implement the form well, I believe it works as expected.

```
@page "/Issue83Test"

<h1>Issue 83</h1>

<EditForm EditContext="@numberEditContext">
    <HxInputNumber @bind-Value="@numberModel.Value" Label="Number" />
    <HxButton Text="Submit" Enabled="@(!numberEditContext.GetValidationMessages().Any())" Color="ThemeColor.Primary" />
</EditForm>

<EditForm EditContext="@dateEditContext">
    <HxInputDate @bind-Value="@dateModel.Value" Label="Date" />
    <HxButton Text="Submit" Enabled="@(!dateEditContext.GetValidationMessages().Any())" Color="ThemeColor.Primary" />
</EditForm>

@code
{
    private EditContext numberEditContext;
    private GenericModel<int> numberModel;

    private EditContext dateEditContext;
    private GenericModel<DateTime> dateModel;

    private void HandleValidationStateChanged(object sender, ValidationStateChangedEventArgs args)
    {
        StateHasChanged();
    }

    protected override void OnInitialized()
    {
        base.OnInitialized();

        numberModel = new GenericModel<int>();
        numberEditContext = new EditContext(numberModel);
        numberEditContext.OnValidationStateChanged += HandleValidationStateChanged;

        dateModel = new GenericModel<DateTime>();
        dateEditContext = new EditContext(numberModel);
        dateEditContext.OnValidationStateChanged += HandleValidationStateChanged;
    }

    private class GenericModel<T>
    {
        public T Value { get; set; }
    }
}
```
