### ISSUE TITLE
[HxSidebar] HxSidebarItem.OnClick event

### ISSUE THREAD

**Issue by franky1017** [havit/Havit.Blazor#837]
I am using the HxSidebar component and instead of linking to a page, I would like to set the OnClick event of the HxSidebarItem. But I was not able to find such event. Is this by design?

**Comment by crdo** [comment]
Yes, it is not there by design.

**Comment by hakenr** [comment]
@franky1017 What would you like to achieve with `HxSidebarItem.OnClick`?

**Comment by franky1017** [comment]
I am using the sidebar as a list and when clicking on it, the right panel
would show details of the item.

I’ve switched to use list but I just love the look and feel of the sidebar
with auto hide and mobile menu features.

**Comment by hakenr** [comment]
Although I understand your scenario, the `HxSidebar` is still a very specific and complex component designed solely for the main navigation of the entire application. There are many other issues you might encounter if you try to use it differently.

I’ll take your feedback into account if we decide to do a major overhaul of the sidebar component.

**Comment by hakenr** [comment]
In the end, we decided to reconsider the original approach. For advanced scenarios where specific logic is needed in the `OnClick` event, we will add new parameters to `HxSidebarItem`:
- `OnClick`
- `OnClickPreventDefault`
- `OnClickStopPropagation`

Hopefully, this won't cause more confusion than it brings utility.

**Comment by crdo** [comment]
I think this can be closed.
