### ISSUE TITLE
HxSelect - ValueChanged AND bind-Value conflicts

### ISSUE THREAD

**Issue by JranZu** [havit/Havit.Blazor#84]
I am trying to use the HxSelect component.  After an option is selected I need to make an Async call to get data from our database. 

`<HxSelect Data="@OurInfo" TextSelector="@(d => d.Name)"
          @bind-Value=SelectedInfo
          TItem="OurInfoDto" TValue="OurInfoDto"
          ValueChanged="SelectedInfoChanged"
          Nullable="true" NullText="-- choose info --" NullDataText="Loading info..." />`
          
The issue is that the @bind-Value is required, it crashes during runtime if it's not provided.  However - you also can't use the ValueChanged event along with the @bind-Value, you get a runtime error saying:

> The component parameter 'ValueChanged' is used two or more times for this component. Parameters must be unique (case-insensitive). The component parameter 'ValueChanged' is generated by the '@bind-Value' directive attribute.

I can get around this by adding a call to `SelectedInfoChanged` in the `SelectedInfo` setter, but that is not the "right" way to do thing.

**Comment by hakenr** [comment]
@JranZu,
the usage should be
```razor
<HxSelect
  Data="@OurInfo"
  TextSelector="@(d => d.Name)"
  Value="SelectedInfo"
  ValueExpression="@(() => SelectedInfo)"
  TItem="OurInfoDto"
  TValue="OurInfoDto"
  ValueChanged="SelectedInfoChanged"
  Nullable="true"
  NullText="-- choose info --" 
  NullDataText="Loading info..." />

@code {
  private async Task SelectedInfoChanged(OurInfoDto newValue)
  {
    SelectedInfo = newValue;
    
   // do whatever you need here
   await ...
  }
}
```

**Comment by JranZu** [comment]
Thanks, that fixed it.
