### ISSUE TITLE
[HxGrid] New progress indicator

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#842]
It turns out that the squashed HTML structure (#465) still has some glitches (#839), so we decided to replace the current "circle" `HxProgressIndicator` used in `HxGrid` with a prettier (hopefully) linear indicator in the grid header:
![2024-06-25_17-43-53](https://github.com/havit/Havit.Blazor/assets/12828888/0515b6ca-596e-4a0a-9de5-902b28636f83)

**Comment by rqx110** [comment]
This is great. But when the header invisible(by the table scroll), the progress indicator is also invisible!

**Comment by hakenr** [comment]
@rqx110 You are correct, and we are aware of this. We believe most grids should be using `sticky-top` when scrollable.

We think the scenario where the progress indicator should be shown (i.e., a long-running operation > `HxGrid.ProgressIndicatorDelay` (default is 300ms)) and the header is scrolled away from the viewport is quite rare, so we decided to sacrifice it for now (the previous version was suffering from the same issue).

We should definitely fine-tune the demo, probably with `sticky-top` to avoid this issue.
