### ISSUE TITLE
[HxTabPanel] does not work with AuthorizeView anymore

### ISSUE THREAD

**Issue by Arnnes** [havit/Havit.Blazor#848]
From version 4.6.8, `HxTab` is not displaying when using `AuthorizeView`. The example is visible in the feature branch feature/issue-484.

**Comment by hakenr** [comment]
The `HxTabPanel` implementation (registration of child components) has been updated to align with `QuickGrid` (used as a reference implementation from the Blazor team). The new implementation does not support wrapping components inside the `HxTabPanel.ChildContent`. Instead, `HxTab` components must be placed directly inside the `ChildContent`.

`AuthorizeView` is no longer supported in this scenario. Any dynamic behavior must be implemented using `@if` blocks or the `HxTab.Visible` attribute.

This is a breaking change, but the new setup makes sense to me. The `HxTabPanel.ChildContent` is not for rendering "any" content but an implementation detail to ensure the markup structure of `HxTabPanel` and `HxTab` functions correctly.

**Comment by hakenr** [comment]
...will state this in documentation, to avoid confusion.
