### ISSUE TITLE
[HxTooltip, HxPopover] Allow passing Container parameter as ElementReference

### ISSUE THREAD

**Issue by alexax578** [havit/Havit.Blazor#854]
https://getbootstrap.com/docs/5.3/components/tooltips/#options

Options allow `element` type for container parameter.

I think we should implement one new parameter - `ContainerElement` of type `ElementReference`. Either `Container` or `ContainerElement` parameter can be set, but not both at the same time.

This would allow us to implement a pattern where we render tooltip body inside its trigger element. This would hopefully make the tooltip visible when we hover inside it.

**Comment by hakenr** [comment]
For these super-rare scenarios, I prefer to allow the `#elementId` pattern to be passed to the `string Container` parameter value (and resolve the `element` inside our JS for this pattern) instead of adding a new parameter.
I think we've already used this pattern somewhere.

**Comment by hakenr** [comment]
Well, it seems Bootstrap itself does some basic `container` resolution:
https://github.com/twbs/bootstrap/blob/e20cc0d660f72c12befbfcbe90eef2aa39655c48/js/src/tooltip.js#L559
https://github.com/twbs/bootstrap/blob/e20cc0d660f72c12befbfcbe90eef2aa39655c48/js/src/util/index.js#L86-L97

...which means we don't need to. :-D
