### ISSUE TITLE
[HxGrid] Multiselect with checkboxes demo is broken

### ISSUE THREAD

**Issue by crdo** [havit/Havit.Blazor#858]
The checkbox state is out of sync with the rest of the demo
https://localhost:5001/components/HxGrid#multiselect
![ScreenRecording2024-07-17at9 52 02-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/1e79e2b3-2ec3-476f-8fd7-be4d8025858e)

**Comment by github-michl** [comment]
For better navigation when solving a problem. https://github.com/havit/Havit.Blazor/blob/5c24c27b36ed30421ecba57956dcd53383457b17/Havit.Blazor.Components.Web.Bootstrap/Grids/HxGrid.razor#L146 returns **GridCellTemplate** but before **OnParametersSet** is executed in **HxMultiSelectGridColumnInternal**. So the status is displayed one change later. Maybe not having the **SelectedDataItems** in two instances, but just one current source of truth might help.

**Comment by econner20** [comment]
Issue still exists in latest build 4.6.12

**Comment by StarGazer202424** [comment]
> Issue still exists in latest build 4.6.12

I am also getting this issue in latest build.

@hakenr any update on this?

Also is there away to restore what are checked with persisting state?

**Comment by hakenr** [comment]
Publishing in `4.6.13-pre1` for testing.
Any feedback is welcome, not just on this specific outcome but also on any other findings regarding the changes to the `HxGrid` implementation.

**Comment by StarGazer202424** [comment]
> Publishing in `4.6.13-pre1` for testing. Any feedback is welcome, not just on this specific outcome but also on any other findings regarding the changes to the `HxGrid` implementation.


I  will play around with it.  What else did you change?

**Comment by hakenr** [comment]
> I will play around with it. What else did you change?
Just the internal implementation of the HxGrid, where the grid's rendering is now "deferred" in the rendering queue.
It's a small change in terms of scope, but it might have unexpected effects on the behavior of HxGrid.

**Comment by econner20** [comment]
This looks to have resolved the multiselect checkbox issue for me.

**Comment by hakenr** [comment]
@econner20 Thanks for confirmation.

**Comment by StarGazer202424** [comment]
> This looks to have resolved the multiselect checkbox issue for me.

Same here, I am working on an implementation of the grid will report back if I notice anything not working.

**Comment by hakenr** [comment]
@StarGazer202424 Thanks for confirmation.
