### ISSUE TITLE
[HxInputDate] - Adding onBlur on HxInputDate leads to double-clicking issue on popup calendar

### ISSUE THREAD

**Issue by StarGazer202424** [havit/Havit.Blazor#859]
Hi

I have taken the example of the Havit demo page

```
<HxInputDate Label="Date" @bind-Value="@value" @onblur="Test" />

@code {
    public DateTime value { get; set; }
}

```
When you click in the controls and the calendar pops up and choose any date. The date chosen is filled on first click into the inputbox.

When you add an "onblur" event to the HxInputDate something happens and you must now click on the same date twcie to get the same previous result of the date being filled in the input box.

```
<HxInputDate Label="Date" @bind-Value="@value" @onblur="Test" />

@code {
    public DateTime value { get; set; }

    protected void Test()
    {
        // do something
    }
}
```

I am using Havit version 4.6.11 

Expected Result:

When using the HxInputDate I expect to be able to add an "onblur" event on it and be able to still use the popup calendar and be able to click only once to choose a date.

**Comment by hakenr** [comment]
Hello @StarGazer202424,

Thanks for reporting this. This is a well-known `onblur` issue - it's how browsers behave when triggering the `onClick` event. The `EventCallback` subscribed to `onblur` causes the component to re-render, and the ongoing browser action won't trigger the `onClick` event if the target HTML node changes.

See [this GitHub issue](https://github.com/facebook/react/issues/4210) or [this StackOverflow discussion](https://stackoverflow.com/questions/44142273/react-ul-with-onblur-event-is-preventing-onclick-from-firing-on-li) where a similar issue is being discussed.

Fortunately, I found a bug in our `HxCalendar` implementation where the DOM refresh of weeks and days in the calendar was forced on every re-render. Fixing this bug should prevent the reported issue from occurring in common scenarios (though it still depends on your code in the `onblur` handler - if you mutate the state so the calendar changes, the `onclick` event still won't trigger and the calendar won't work as expected).
