### ISSUE TITLE
HxSelect fire event OnChange

### ISSUE THREAD

**Issue by Kodestuen** [havit/Havit.Blazor#86]
Trying to catch an OnChange event when a dropdown/select changes.

But that seems impossible, you can only use @bind-Value.

But for my use case I want to filter another HxSelect, and then I really need to catch a OnChange event.

The documentation/examples does not indicate is possible, but hopes I'm wrong :-)

Best,
CU

**Comment by hakenr** [comment]
@Kodestuen, `@bind` in Blazor is just a syntactic sugar for  `Value` and `ValueChanged` parameters (+ `ValueExpression` where applicable).
You can use the `ValueChanged` event-callback directly to act on value change:

```razor
<HxSelect ... Value="valueField" ValueChanged="HandleValueChanged" ValueExpression="() => valueField" />
@code {
  private async Task HandleValueChanged(<TValue> newValue)
  {
    valueField = newValue;
    // do whatever you need here
  }
}
```

More details: https://docs.microsoft.com/en-us/aspnet/core/blazor/components/data-binding

**Comment by Kodestuen** [comment]
Arhh you are a friend, tried :

`<HxSelect ... Value="valueField" ValueChanged="HandleValueChanged" />`

But was missing the `ValueExpression="() => valueField"` part.

Now I'm a bit more enlightened, so thank you so much!
