### ISSUE TITLE
[HxInputText] error with array

### ISSUE THREAD

**Issue by romaluca** [havit/Havit.Blazor#874]
I have an array of strings, **Place.Sites**, that I'm trying to manage using the **HxInputText** component. My current code looks like this:
```
@for (int x=0; x < Place.Sites.Count();x++)
        {
            int i = x;
        <p>
            <HxInputText Label="Sites" @bind-Value="Place.Sites[i]" />
        </p>
        }

```
However, this code raises the following error:

> InvalidOperationException: Sequence contains no elements
> System.Linq.ThrowHelper.ThrowNoElementsException()
> System.Linq.Enumerable.Single<TSource>(IEnumerable<TSource> source)
> Havit.Blazor.Components.Web.Bootstrap.HxInputBase<TValue>.GetValueAttribute<TAttribute>()
> Havit.Blazor.Components.Web.Bootstrap.HxInputTextBase.BuildRenderInput(RenderTreeBuilder builder)
> Havit.Blazor.Components.Web.Bootstrap.HxInputBase<TValue>.Havit.Blazor.Components.Web.Bootstrap.Internal.IFormValueComponent.RenderValue(RenderTreeBuilder builder)

if I switch to the standard InputText component, the code works as expected:

```

@for (int x=0; x < Place.Sites.Count();x++)
        {
            int i = x;
        <p>
            <InputText Label="Sites" @bind-Value="Place.Sites[i]" />
        </p>
        }
```

How can i use HxInputText instead of InputText?
Thanks

**Comment by hakenr** [comment]
Thanks for reporting this. I was able to reproduce the issue and it is fixed now. Will be part of next release.
