### ISSUE TITLE
[HxDropdownToggleElement, HxDropdownToggleButton] Allow customization of options passed to Bootstrap dropdown constructor from Blazor component

### ISSUE THREAD

**Issue by alexax578** [havit/Havit.Blazor#875]
I would like to pass custom options to the underlying Bootstrap dropdown component in my own component derived from **HxDropdownToggleElement/HxDropdownToggleButton**.

Bootstrap dropdown options:
https://getbootstrap.com/docs/5.3/components/dropdowns/#options

I also need to be able to extend these options as I work with customized Bootstrap JavaScript.

**Proposed solution:**
Add a virtual method to **HxDropdownToggleElement** and **HxDropdownToggleButton** that returns the configuration which will be supplied to the Bootstrap dropdown when it is created.

This pattern could be implemented for other components as well (Modal, Offcanvas, Carousel...) as it would allow for greater customization in components derived from **Havit.Blazor** components.

**Comment by hakenr** [comment]
@alexax578 released in `4.6.13-pre2` for testing
