### ISSUE TITLE
[HxDropdownItem] Can't set class on <li> element

### ISSUE THREAD

**Issue by robertmclaws** [havit/Havit.Blazor#89]
This one is pretty self-explanatory. I need to be able to set the CSS class on the LI element wrapper. But the LI is hard-coded with no style property.

Could add a ContainerCssClass property that would let me pass that in properly.

Thanks!

**Comment by hakenr** [comment]
@robertmclaws Yes, I already realized that and was waiting for the real scenario where this will be needed/requested.
(BTW: Similar to `HxNav`-family, there is still a chance the `ul-li` will be removed some time.)

I'm still not sure about the naming. Maybe rather `ListItemCssClass`?

**Comment by robertmclaws** [comment]
I actually liked that the ul-li was there, and it worked out really well for our use-case. Essentlailly I needed an HTML-powered Popover, and the HxDropdown with some CSS to remove the caret and disable mouse interactions on the UL solved the problem nicely.

I thought about that property too. The reason I suggested `ContainerCssClass` instead is because, throughout the library, the actual thing you're working with is being dropped into a container element. By using that property instead, it make it more intuitive as you discover there is a container and you need to style it, vs having to use IntelliSense or the docs to figure out which _specific_ property name you need to use.

But you do what you think is best for the platform. Thanks!

**Comment by crdo** [comment]
@robertmclaws haha, this (HTML powered Popover via HxDropdown) is actually pretty ingenious solution, we might try it as well. Such a pity that you can only provide content to the Popover with title/string.

**Comment by hakenr** [comment]
Just added `ContainerCssClass` to all the HxDropdownItem-like components.
Will be included in next release.
