### ISSUE TITLE
[HxSideBar] Menus only opening, not closing?

### ISSUE THREAD

**Issue by rgbinnovation** [havit/Havit.Blazor#902]
Hi just got the HxSideBar menu to work (thanks @hakenr), but for some reason the multi level menus only opens but can't be closed?

There is no error message in the console. You simply cannot collapse the menus.

**Comment by rgbinnovation** [comment]
Never mind, had two Bootstrap references. Removed one and now it works. Geez.

**Comment by hakenr** [comment]
Hello,
I'm not sure what you mean by "multi-level menus" - only one level of expansion is supported.

For supported behavior, check out the demos here: https://havit.blazor.eu/components/HxSidebar. The entire demo site uses an `HxSidebar` as well.

If you have only one level of expansion and still can't collapse it, please send us a repro code so we can investigate further. Note that if you expand another node, previously expanded nodes won't collapse automatically unless you set `MultipleItemsExpansion="false"`.

**Comment by hakenr** [comment]
> Never mind, had two Bootstrap references. Removed one and now it works. Geez.

Thanks for confirmation. Enjoy our components.

**Comment by rgbinnovation** [comment]
Thanks again @hakenr for your quick reply. It's good to know that there is someone out there that can help out. Much appreciated, and it makes me much more comfortable using this component set (great set by the way).
