### ISSUE TITLE
[HxAutosuggest] Both regular and floating label rendered when setting LabelType with Settings/Defaults

### ISSUE THREAD

**Issue by lmmv92** [havit/Havit.Blazor#907]
I have set the default label type as floating with `HxSetup.Defaults.LabelType = LabelType.Floating`;. When I create an HxAutoSuggest component, the label is duplicated, it is correctly generated inside the form-floating div, but also outside of it (like a regular label). If I set the LabelType directly in the component, it works correctly.

**Comment by hakenr** [comment]
@lmmv92 Thanx for reporting this. I was able to reproduce the issue, and it is fixed now. (Will be part of 4.6.18 release.)
