### ISSUE TITLE
[HxGrid] ItemRowHeight is applied only when Infinite Scroll is set

### ISSUE THREAD

**Issue by alexax578** [havit/Havit.Blazor#909]
Currently, height is set on tr elements only when Infinite Scroll is set:
```height="@((ContentNavigationModeEffective == GridContentNavigationMode.InfiniteScroll) ? rowHeight : null)"```

I would consider setting row height independently of the current ContentNavigationMode as it may not be obvious behavior.

Doing so however leads to a breaking change where the default value of 41px would be used for every grid. After discussion with @crdo I suggest removing this default.

Otherwise I would update the documentation of the Parameter to explicitly say that it is only applied when Infinite Scroll is set.

**Comment by hakenr** [comment]
We still expect that most applications will use `InfiniteScroll` 90% of the time, as it is the current standard for UI. 

If we remove the default, users will still want to set an application-wide default for this 90% of cases, so they don't have to specify `ItemRowHeight=".."` on every single grid. Currently, there's no elegant way to support this setup unless we introduce a new setting, something awkward like `HxGrid.Defaults.InfiniteScrollItemRowHeight`.

I checked the API of other grid implementations, and `QuickGrid` also uses the `ItemSize` parameter only for `Virtualize` scenarios.

Based on this, I decided to add a note about it in the parameter/setting documentation and leave the implementation as-is. (Row height can still be controlled via CSS for non-virtualized grids.)
