### ISSUE TITLE
[HxGrid] sorting on IQueryable

### ISSUE THREAD

**Issue by petrkasnal** [havit/Havit.Blazor#91]
Hello,

i use your hxgrid. And i processing data on seperate service. I do pagination, filtering and sorting. I want use your implementation of sorting because i want do it in my service. In your component is this:
```
			#region Sorting
			if ((Sorting != null) && Sorting.Any())
			{
				Contract.Assert(Sorting.All(item => item.SortKeySelector != null), "All sorting items must have set SortKeySelector property.");

				IOrderedEnumerable<TItem> orderedData = (Sorting[0].SortDirection == SortDirection.Ascending)
					? resultData.OrderBy(Sorting[0].SortKeySelector.Compile())
					: resultData.OrderByDescending(Sorting[0].SortKeySelector.Compile());

				for (int i = 1; i < Sorting.Count; i++)
				{
					orderedData = (Sorting[i].SortDirection == SortDirection.Ascending)
						? orderedData.ThenBy(Sorting[i].SortKeySelector.Compile())
						: orderedData.ThenByDescending(Sorting[i].SortKeySelector.Compile());
				}
				resultData = orderedData;
			}
			#endregion
```

But this is working only for IEnumerable. I would like have sorting on iquryable, because filtering and pagination i have. I try your implementation and it doesn't work on IQuryable. I try my custom implementation and it works for only string columns. It doesn't work for int... Do you have any help? Thanks 
  ```
         if (sortingItems != null)
            {
                foreach (var sortingItem in sortingItems)
                {
                    if (sortingItem.SortDirection == Havit.Collections.SortDirection.Descending)
                        source = source.OrderByDescending(sortingItem.SortKeySelector);
                    else
                        source = source.OrderBy(sortingItem.SortKeySelector);
                }
            }

            return source;
```

Do you think you'll ever add support to IQueryable? Thank you very much :)

**Comment by crdo** [comment]
Duplicate with #66

**Comment by petrkasnal** [comment]
Hello, i understand the second part and why isn't good use quryable in frontend. I use dbcontextfactory so It still wouldn't work for me. I should have thought more. But here is still first question maybe more like advice. Do you have implementation of sorting for iquryable in backend? Thank you

**Comment by hakenr** [comment]
we have some helpers but most of the time we code it manually

We use `Havit.Collections.SortItem[]` as Data Transfer Object (DTO) between client and the server. The column is represented with string there + we use `nameof(...)` for better maintainability.

On client-side you map the sorting request to DTO:
```csharp
Sorting = request.Sorting.Select(s => new SortItem(s.SortString, s.SortDirection)).ToArray()
```

...server-side sorting of IQueryable (`OrderBy()` and `OrderByMultiple()` are extension methods from `Havit.Linq.QueryableExt`):
```csharp
		if (Sorting is not null)
		{
			queryable = queryable.OrderByMultiple(Sorting, sortingExpression => sortingExpression switch
			{
				nameof(ClientCardSort.LastName) => new() { cc => cc.LastName, cc => cc.CompanyName },
				nameof(ClientCardSort.City) => new() { cc => cc.Address.City },
				nameof(ClientCardSort.LegalType) => new() { cc => cc.LegalType },
				nameof(ClientCardSort.BirthNumber) => new() { cc => cc.BirthNumber, cc => cc.CompanyNumber },
				nameof(ClientCardSort.Rating) => new() { cc => cc.Rating },
				nameof(ClientCardSort.CardValidity) => new() { cc => cc.Validity },
				nameof(ClientCardSort.LastActivity) => new() { cc => cc.LastModified, cc => cc.LastBtClientCardEventTimestamp },
				nameof(ClientCardSort.BtCreated) => new() { cc => cc.BtCreated },
				_ => throw new InvalidOperationException($"Unknown SortingItem.Expression {sortingExpression}.")
			});
		}
		else
		{
			// default sorting
			queryable= queryable.OrderByDescending(cc => cc.LastModified).ThenByDescending(cc => cc.LastBtClientCardEventTimestamp);
		}
```
(the `OrderBy()` version where you don't have sortings by several columns is simpler, you just return the lambda of the property to use for sorting).

**Comment by hakenr** [comment]
Closing as duplicate.
