### ISSUE TITLE
[HxMultiselect] Multiselect component support

### ISSUE THREAD

**Issue by baneTN** [havit/Havit.Blazor#94]
Hi,
Do you maybe plan support for multiselect component?
Currently we are using HxInputTags in order to get more values selected, but unfortunately this only supports strings, not an object.

Thanks for the great library!

**Comment by hakenr** [comment]
Hi @baneTN,
the multiselect component is on our roadmap, one of the top new features on the list.
It should be [`HxSelect`](https://havit.blazor.eu/components/HxSelect)-like component where every item should have a checkbox to be able to select multiple items.

(In fact, it is already being developed, the UX is prepared but the Blazor component itself is currently on hold waiting for some free capacities to make it done.)

**Comment by hakenr** [comment]
![image](https://user-images.githubusercontent.com/12828888/158711490-81ff48b6-5ceb-4992-ac05-522eb2d63b53.png)

...the name of the component is still open as the same component (or the one based on the same basis) should be able to work in single-select mode without the checkboxes (just as customizable replacement of the native `select` HTML element):

**Comment by hakenr** [comment]
@robertmclaws Any suggestions on the name of the new component(s)?
These will probably have to be two separate components not to mix the IEnumerable (multi-value) vs. single-value API (`Value` parameter).

**Comment by robertmclaws** [comment]
Thanks for asking me! I have a couple ideas, but to help with direction, I have a question: what is your thinking behind making this a new control vs upgrading the existing HxSelect control to support multiple selections?

**Comment by hakenr** [comment]
Well, the `HxSelect` is meant to be just a plain native `select`-`option` implementation (with all the cons and pros) whereas the new component(s) should bring completely custom [Bootstrap dropdown](https://getbootstrap.com/docs/5.0/components/dropdowns/)-based implementation allowing more precise visual tweaks but without all the built-in features of native `select` (e.g. for now we do not aspire to implement full keyboard navigation where you start typing the name and the most-appropriate item will focus, etc.).
The main goal of multiselect version is to bring a better checkbox-based UX for selecting multiple options (in comparison to native `select multiple` where you have to <kbd>Ctrl</kbd>-select the items on most desktop browsers).

**Comment by robertmclaws** [comment]
`HxCheckboxSelect` or `HxMultiSelect` sounds like the best approach.

**Comment by hakenr** [comment]
and for the single-value version of custom select? (not the native one currently implemented as `HxSelect`)
![image](https://user-images.githubusercontent.com/12828888/158843256-830576e2-f0af-4716-8171-7184325547ca.png)

**Comment by crdo** [comment]
@baneTN HxMultiSelect has been implemented, can be already seen in the docs at https://havit.blazor.eu/components/HxMultiSelect and will be part of the upcoming release.
