### ISSUE TITLE
[HxCheckboxList] How to apply css class to checkbox container both in header and item rows?

### ISSUE THREAD

**Issue by HybridSolutions** [havit/Havit.Blazor#95]
Hi,

I need to apply a custom css class to the container of the checkboxes so they get a custom style from a theme I'm using. How can I do that for both the checkbox in the header and for each on that is present in the rows?

This is what I had before using your grid component:

```
<div class="form-check form-check-custom form-check-sm form-check-solid me-2">
	<input class="form-check-input" type="checkbox" value="1">
</div>
```

Also, how can I customize the icons used in the pager first, previous, next and last buttons? I miss options to customize that. It would be very usefull to have opstions like PagerFirstItemCssClass, PagerPreviousItemCssClass and so on. Yes I know I could somehow apply custom style with my own css rules but using a theme it would be easier to be able to apply already existing CSS classes.

Thanks!

**Comment by HybridSolutions** [comment]
> Hi, with `HxInputCheckbox` you should be able to set the `CssClass` and `InputCssClass` parameters. Unfortunately, detailed customization is currently not supported with `HxCheckboxList`, I will put that in implementation queue.
> 
> Regarding the `HxPager` customization, same there, not supported yet. If you are interested in making it customizable, plese file in a separate issue for better tracking.

Both these features are very important because not everyone uses BS icons and uses themes that already provide their icon implementation. Regarding the pager, I don't understand why you chose the path to inject it instead of allowing the optional usage of the Pager component inside a Footer template and then provide a way to wire it to the table with a couple parameters. I created another issue for this.

**Comment by hakenr** [comment]
As of `HxCheckboxList`, let's add new parameters:
* `Func<TItem, string> CssClassSelector`
* `Func<TItem, string> InputCssClassSelector`
* `Func<TItem, string> LabelCssClassSelector`
...and pass the resulting value to underlying `HxInputCheckbox` if the selector is set and returns value.

cc @Harvey1214
