### ISSUE TITLE
[HxGrid] Allow selection only some of the rows with MultiSelectionEnabled="true"

### ISSUE THREAD

**Issue by crdo** [havit/Havit.Blazor#953]
On PWT, we need to be able to set MultiSelectionEnabled="true", but let user to select only some of the rows based on the data.
Visually, some of the rows will have the checkbox and some not.
<img width="1108" alt="image" src="https://github.com/user-attachments/assets/470b6388-9159-4e38-8ead-98d75ee8db83">

**Comment by hakenr** [comment]
Resolved with https://blocks.havit.blazor.eu/grids/multi-selection-customization
