### ISSUE TITLE
[HxSidebar] Menu with subitems is hiding when sidebar is collapsed

### ISSUE THREAD

**Issue by Arnnes** [havit/Havit.Blazor#961]
When the sidebar is collapsed and a menu item has subitems, it becomes difficult to select the subitems because the menu hides too quickly. This issue can be reproduced in the HxSidebar documentation.
![ezgif com-cut](https://github.com/user-attachments/assets/3a4438d2-42d0-4f81-86b8-9a7241376cdb)

**Comment by crdo** [comment]
@Arnnes @hakenr my bad, I removed [one line](https://github.com/havit/Havit.Blazor/commit/97d1bb8104ca81646a6abdf97d6c4b99377b820d#diff-e35d0fdeb47e11acac85f7539048ab58dd344e44de8bc36932b5153fe7289511L72) when implementing the responsive collapse as i thought that `offset=0,0` is default and thus not needed.
