### ISSUE TITLE
[HxListLayout] Chips are related to "inner" component in FilterTemplate

### ISSUE THREAD

**Issue by vaclavek** [havit/Havit.Blazor#962]
If I use a custom component in FilterTemplate where property name is different than original:
![image](https://github.com/user-attachments/assets/6bc4c11f-67e3-466d-8a11-1e4293717ea8)

chips are bound to this component (to property "Value"). See [this Action](https://github.com/havit/Havit.Blazor/blob/83e3a05667cf8b5f9baf753ab5ead4a0416e7d2b/Havit.Blazor.Components.Web.Bootstrap/Forms/HxInputBase.cs#L409C1-L414C5) which is bound to "my custom component model" (in this case property "Value")

If I try to remove this chip:
![image](https://github.com/user-attachments/assets/5f97ab09-951f-44fc-a241-0342e4b15b60)

It cannot be processed, because "model" is different and fails contract "Invalid FieldIdentifier. Check ValueExpression parameter".
I have prepared PR with issue: https://github.com/havit/Havit.Blazor/pull/963

![image](https://github.com/user-attachments/assets/e2bbddeb-4c46-46b3-b405-f1a8a8cbf94a)

**Comment by hakenr** [comment]
This is a known limitation of the current `HxListLayout` design, where `HandleChipRemoveClick` relies on `RemoveAction` actions gathered from the input component.

To resolve this, you have two options:
1. Don’t wrap the `HxSelect`. Instead, derive your component from `HxSelectBase` (this is not applicable to all components, but in the repro scenario, it’s the simplest solution).
2. Set `<HxSelect GenerateChip="false" />` and add `<HxChipGenerator />` to your custom component.

**Comment by vaclavek** [comment]
Oh, all right.
Compoent was used for demonstration only. I will use custom HxChipGenerator ...
Thank you for explanation :)
