### ISSUE TITLE
[HxAutosuggest] ReferenceError: dropdown is not defined

### ISSUE THREAD

**Issue by lmmv92** [havit/Havit.Blazor#964]
While using HXAutosuggest, I encounter the error 'Uncaught ReferenceError: dropdown is not defined,' even in the demo. It doesn’t always happen, just sometimes, so I’m unsure what is causing it.
![image](https://github.com/user-attachments/assets/dfc9bd68-89b4-4278-a08f-80861c83ada6)

**Comment by hakenr** [comment]
@lmmv92 Thanx for reporting this.
Fixed, will be published in next release (within hours/days).
