### ISSUE TITLE
[HxFileInput] max size validation 

### ISSUE THREAD

**Issue by petrkasnal** [havit/Havit.Blazor#98]
Hello, is any posibility to add validation for max size in FileInput? 

Thank you

**Comment by hakenr** [comment]
You can use the `MaxFileSize` parameter
https://havit.blazor.eu/components/HxInputFile#LimitFileSizeAndTypes
```razor
<HxInputFile MaxFileSize="500000" />
```

**Comment by petrkasnal** [comment]
@hakenr thank you for response. I use this, but its not return me any validation. Do you have any example of this please? Thank you

**Comment by hakenr** [comment]
The `HxInputFile` component does not interact with `<EditForm />` (`EditContext`) and is not intended to take part in the classic form-validation workflow.

Currently, trying to upload a file bigger than the `MaxFileSize` limit emits a warning to the console, does not upload such file and signals such file with `OnFileUploaded` callback where the status code is set to 413 with a explanatory response message.

https://github.com/havit/Havit.Blazor/blob/18ca3a804043fd2e0a9dabfcbf6d42787260292a/Havit.Blazor.Components.Web/wwwroot/HxInputFileCore.js#L33-L45

If you need a custom visual signalization of such files, you have to either use the `OnChange` callback and check the file sizes on your own, or use the `OnFileUploaded` callback where you will check for 413 and act accordingly.

**Comment by petrkasnal** [comment]
I understand, so the solution is to do the validation manually. Which I didn't want to do, but I understand that it can't be done any other way, because it's not a bind in the editform. Thank you very much :)
